
package sirh;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

public class AprivConsola extends javax.swing.JFrame {


    public AprivConsola() {
        initComponents();
        setDefaultCloseOperation(0);
        Iniciar();
    }
    
    private void Limpiar(JTable tabla){
        while(tabla.getRowCount()>0){
            ((DefaultTableModel) tabla.getModel()).removeRow(0);
        }
    }
    
    private void Iniciar(){
        fecha.setText(fechaActual());
        usuario.setText(Acceso.getClaveUsuario());
        txtNombre.setText(Acceso.getNombreUsuario());
        txtEmpresa.setText(Acceso.getEmpresaUsuario());
        txtNumero.setText(String.valueOf(Contr.getNumTrabaja()));
        txtTrabaja.setText(Contr.getNomTrabaja());
        txtContrato.setText(Contr.getNcoTrabaja());
        
        int RegTra = Contr.getNumTrabaja();
        String NumCon = Contr.getNcoTrabaja();
        Limpiar(tablaapriv);
        DefaultTableModel modelo=(DefaultTableModel) tablaapriv.getModel();
        Apriv e1=new Apriv();
        e1.LlenarDatos(modelo, RegTra, NumCon);
        
        causa.removeAllItems();
        causa.addItem("");
        Apriv e2=new Apriv();
        e2.LlenarCausa(causa);
        fecini.setDate(null);
        horini.setText("");
        fecter.setDate(null);
        horter.setText("");
        patgen.setText("C:/SIRH/AUSENCIAS/AUSENCIAS.GIF");
        justif.removeAllItems();
        justif.addItem("");
        Apriv e3=new Apriv();
        e3.LlenarSino(justif);
        caracte.setText("");
        patjus.setText("C:/SIRH/AUSENCIAS/AUSENCIAS.GIF");
        reanuda.removeAllItems();
        reanuda.addItem("");
        Apriv e4=new Apriv();
        e4.LlenarSino(reanuda);
        fecrea.setDate(null);
        horrea.setText("");
        pervac.setText("");
        observa.setText("");
        status.setText("");
        crear.setEnabled(true);
        causa.setEnabled(true);
        fecini.setEnabled(true);
    }
    
    public static String fechaActual(){
        Date fecha= new Date();
        SimpleDateFormat formatoFecha=new SimpleDateFormat("dd/MM/YYYY HH:mm:ss");
        return formatoFecha.format(fecha);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaapriv = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        causa = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        fecini = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        horini = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        fecter = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        horter = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        patgen = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        justif = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        caracte = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        patjus = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        reanuda = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        fecrea = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();
        horrea = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        pervac = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        observa = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        status = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        fecha = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        crear = new javax.swing.JButton();
        actualizar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtEmpresa = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        txtTrabaja = new javax.swing.JTextField();
        txtContrato = new javax.swing.JTextField();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SNTIAISCRM Sistema de Recursos Humanos");
        setMaximumSize(new java.awt.Dimension(810, 561));
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        tablaapriv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Causa", "Fecha Inicio", "Hora Inicio", "Fecha Término", "Hora Término"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaapriv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaaprivMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaapriv);

        jLabel2.setForeground(new java.awt.Color(204, 0, 51));
        jLabel2.setText("Causa:");

        jLabel3.setForeground(new java.awt.Color(204, 0, 51));
        jLabel3.setText("Fecha Inicio:");

        jLabel4.setText("Hora Inicio:");

        jLabel5.setForeground(new java.awt.Color(204, 0, 51));
        jLabel5.setText("Fec Término:");

        jLabel6.setText("Hora Término:");

        jLabel7.setText("Docto Gen:");

        patgen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                patgenMouseClicked(evt);
            }
        });

        jLabel8.setText("Justificante:");

        jLabel9.setText("Caracterist:");

        jLabel10.setText("Docto Just:");

        patjus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                patjusMouseClicked(evt);
            }
        });

        jLabel11.setText("Reanudación:");

        jLabel12.setForeground(new java.awt.Color(204, 0, 51));
        jLabel12.setText("Fec Reanuda:");

        jLabel13.setText("Hora Reanuda:");

        jLabel14.setText("Per Vacacional:");

        jLabel15.setText("Observa:");

        jLabel16.setText("Status:");

        status.setEditable(false);

        jLabel17.setText("Fecha:");

        fecha.setEditable(false);

        jLabel18.setText("Usuario:");

        usuario.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel4))
                                        .addGap(32, 32, 32))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(causa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(horini, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(fecter, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE))
                                    .addComponent(fecini, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addGap(33, 33, 33))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel8)
                                            .addGap(28, 28, 28)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6))
                                        .addGap(19, 19, 19)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(patjus, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(caracte, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(justif, javax.swing.GroupLayout.Alignment.LEADING, 0, 238, Short.MAX_VALUE)
                                    .addComponent(patgen, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(horter))))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(reanuda, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fecrea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(horrea)
                            .addComponent(pervac)
                            .addComponent(observa)
                            .addComponent(status)
                            .addComponent(fecha)
                            .addComponent(usuario))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(causa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(reanuda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(fecini, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(horini, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel13)
                            .addComponent(horrea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(fecter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel14)
                                .addComponent(pervac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(fecrea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(horter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(patgen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(justif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(caracte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(patjus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(observa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        crear.setText("Crear");
        crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearActionPerformed(evt);
            }
        });

        actualizar.setText("Actualizar");
        actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarActionPerformed(evt);
            }
        });

        eliminar.setText("Eliminar");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(crear)
                .addGap(18, 18, 18)
                .addComponent(actualizar)
                .addGap(18, 18, 18)
                .addComponent(eliminar)
                .addGap(18, 18, 18)
                .addComponent(cancelar)
                .addGap(18, 18, 18)
                .addComponent(salir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crear)
                    .addComponent(actualizar)
                    .addComponent(eliminar)
                    .addComponent(cancelar)
                    .addComponent(salir))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel1.setText("MOVIMIENTOS DE AUSENCIAS, PERMISOS, RETARDOS, INCAPACIDADES Y VACACIONES");

        txtEmpresa.setEditable(false);
        txtEmpresa.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        txtEmpresa.setForeground(new java.awt.Color(204, 0, 0));
        txtEmpresa.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtEmpresa.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtNombre.setEditable(false);
        txtNombre.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(204, 0, 0));
        txtNombre.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtNombre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtNumero.setEditable(false);

        txtTrabaja.setEditable(false);

        txtContrato.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTrabaja)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmpresa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTrabaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearActionPerformed
        try{
            Apriv e=new Apriv();
            String dcausa=causa.getSelectedItem().toString();
            if(dcausa.isEmpty()){
                JOptionPane.showMessageDialog(this, "Se requiere una causa de la APRIV, verifique .....");
                Iniciar();
            }
            else{
                if(fecini.getDate() == null){
                    JOptionPane.showMessageDialog(this, "Se requiere la fecha de inicio de la APRIV, verifique .....");
                    fecini.grabFocus();
                }
                else{
                    if(fecter.getDate() == null){
                        JOptionPane.showMessageDialog(this, "Se requiere la fecha de término de la APRIV, verifique .....");
                        fecter.grabFocus();
                    }
                    else{
                        if(fecrea.getDate() == null){
                            JOptionPane.showMessageDialog(this, "Se requiere la fecha de reanudación de la APRIV, verifique .....");
                            fecrea.grabFocus();
                        }
                        else{
                            int añoi=fecini.getCalendar().get(Calendar.YEAR);
                            int mesi=fecini.getCalendar().get(Calendar.MONTH)+1;
                            int diai=fecini.getCalendar().get(Calendar.DAY_OF_MONTH);
                            String dfecini=(añoi+"/"+mesi+"/"+diai);
                            String dhorini=horini.getText().toUpperCase();
                            int añot=fecter.getCalendar().get(Calendar.YEAR);
                            int mest=fecter.getCalendar().get(Calendar.MONTH)+1;
                            int diat=fecter.getCalendar().get(Calendar.DAY_OF_MONTH);
                            String dfecter=(añot+"/"+mest+"/"+diat);
                            String dhorter=horter.getText().toUpperCase();
                            String dpatgen=patgen.getText().toUpperCase();
                            String djustif=justif.getSelectedItem().toString();
                            String dcaracte=caracte.getText().toUpperCase();
                            String dpatjus=patjus.getText().toUpperCase();
                            String dreanuda=reanuda.getSelectedItem().toString();
                            int añor=fecrea.getCalendar().get(Calendar.YEAR);
                            int mesr=fecrea.getCalendar().get(Calendar.MONTH)+1;
                            int diar=fecrea.getCalendar().get(Calendar.DAY_OF_MONTH);
                            String dfecrea=(añor+"/"+mesr+"/"+diar);
                            String dhorrea=horrea.getText().toUpperCase();
                            String dpervac=pervac.getText().toUpperCase();
                            String dobserva=observa.getText().toUpperCase();
                            e.Agregar(Contr.getNumTrabaja(), Contr.getNomTrabaja(), Contr.getRfcTrabaja(), Contr.getPatTrabaja(),
                                      Contr.getStcTrabaja(), Contr.getFesTrabaja(), Contr.getNcoTrabaja(), Contr.getCemTrabaja(),
                                      Contr.getNemTrabaja(), Contr.getCdeTrabaja(), Contr.getNdeTrabaja(), Contr.getCseTrabaja(),
                                      Contr.getNseTrabaja(), Contr.getCcaTrabaja(), Contr.getNcaTrabaja(), Contr.getSxdTrabaja(),
                                      Contr.getCtuTrabaja(), Contr.getNtuTrabaja(), Contr.getCtiTrabaja(), Contr.getNtiTrabaja(),
                                      Contr.getFinTrabaja(), Contr.getFteTrabaja(), dcausa, dfecini, dhorini, dfecter, dhorter, dpatgen,
                                      djustif, dcaracte, dpatjus, dreanuda, dfecrea, dhorrea, dpervac, dobserva, Acceso.getClaveUsuario());
                            JOptionPane.showMessageDialog(this, "Registro creado .....");
                            Iniciar();
                        }
                    }
                }
            }
        }
        catch(NumberFormatException nfe){
            System.out.println("No hay fechas: "+nfe);
        }
    }//GEN-LAST:event_crearActionPerformed

    private void actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarActionPerformed
        try{
            Apriv e=new Apriv();
            String dcausa=causa.getSelectedItem().toString();
            if(dcausa.isEmpty()){
                JOptionPane.showMessageDialog(this, "Se requiere una causa de la APRIV, verifique .....");
                Iniciar();
            }
            else{
                if(fecini.getDate() == null){
                    JOptionPane.showMessageDialog(this, "Se requiere la fecha de inicio de la APRIV, verifique .....");
                    fecini.grabFocus();
                }
                else{
                    if(fecter.getDate() == null){
                        JOptionPane.showMessageDialog(this, "Se requiere la fecha de término de la APRIV, verifique .....");
                        fecter.grabFocus();
                    }
                    else{
                        if(fecrea.getDate() == null){
                            JOptionPane.showMessageDialog(this, "Se requiere la fecha de reanudación de la APRIV, verifique .....");
                            fecrea.grabFocus();
                        }
                        else{
                            int añoi=fecini.getCalendar().get(Calendar.YEAR);
                            int mesi=fecini.getCalendar().get(Calendar.MONTH)+1;
                            int diai=fecini.getCalendar().get(Calendar.DAY_OF_MONTH);
                            String dfecini=(añoi+"/"+mesi+"/"+diai);
                            String dhorini=horini.getText().toUpperCase();
                            int añot=fecter.getCalendar().get(Calendar.YEAR);
                            int mest=fecter.getCalendar().get(Calendar.MONTH)+1;
                            int diat=fecter.getCalendar().get(Calendar.DAY_OF_MONTH);
                            String dfecter=(añot+"/"+mest+"/"+diat);
                            String dhorter=horter.getText().toUpperCase();
                            String dpatgen=patgen.getText().toUpperCase();
                            String djustif=justif.getSelectedItem().toString();
                            String dcaracte=caracte.getText().toUpperCase();
                            String dpatjus=patjus.getText().toUpperCase();
                            String dreanuda=reanuda.getSelectedItem().toString();
                            int añor=fecrea.getCalendar().get(Calendar.YEAR);
                            int mesr=fecrea.getCalendar().get(Calendar.MONTH)+1;
                            int diar=fecrea.getCalendar().get(Calendar.DAY_OF_MONTH);
                            String dfecrea=(añor+"/"+mesr+"/"+diar);
                            String dhorrea=horrea.getText().toUpperCase();
                            String dpervac=pervac.getText().toUpperCase();
                            String dobserva=observa.getText().toUpperCase();
                            e.Actualizar(Contr.getNumTrabaja(), Contr.getNomTrabaja(), Contr.getRfcTrabaja(), Contr.getPatTrabaja(),
                                         Contr.getStcTrabaja(), Contr.getFesTrabaja(), Contr.getNcoTrabaja(), Contr.getCemTrabaja(),
                                         Contr.getNemTrabaja(), Contr.getCdeTrabaja(), Contr.getNdeTrabaja(), Contr.getCseTrabaja(),
                                         Contr.getNseTrabaja(), Contr.getCcaTrabaja(), Contr.getNcaTrabaja(), Contr.getSxdTrabaja(),
                                         Contr.getCtuTrabaja(), Contr.getNtuTrabaja(), Contr.getCtiTrabaja(), Contr.getNtiTrabaja(),
                                         Contr.getFinTrabaja(), Contr.getFteTrabaja(), dcausa, dfecini, dhorini, dfecter, dhorter, dpatgen,
                                         djustif, dcaracte, dpatjus, dreanuda, dfecrea, dhorrea, dpervac, dobserva, Acceso.getClaveUsuario());
                            JOptionPane.showMessageDialog(this, "Registro actualizado .....");
                            Iniciar();
                        }
                    }
                }
            }
        }
        catch(NumberFormatException nfe){
            System.out.println("No hay fechas: "+nfe);
        }
    }//GEN-LAST:event_actualizarActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        Apriv e=new Apriv();
        int dnumtra=Contr.getNumTrabaja();
        String dnumcon=Contr.getNcoTrabaja();
        String dcausa=causa.getSelectedItem().toString();
        if(dcausa.isEmpty()){
            JOptionPane.showMessageDialog(this, "Se requiere una causa de la APRIV, verifique .....");
            Iniciar();
        }
        else{
            if(fecini.getDate() == null){
                JOptionPane.showMessageDialog(this, "Se requiere la fecha de inicio de la APRIV, verifique .....");
                fecini.grabFocus(); 
            }
            else{
                if(fecter.getDate() == null){
                    JOptionPane.showMessageDialog(this, "Se requiere la fecha de término de la APRIV, verifique .....");
                    fecter.grabFocus();
                }
                else{
                    String dhorini=horini.getText();
                    String dhorter=horter.getText();
                    int añoi=fecini.getCalendar().get(Calendar.YEAR);
                    int mesi=fecini.getCalendar().get(Calendar.MONTH)+1;
                    int diai=fecini.getCalendar().get(Calendar.DAY_OF_MONTH);
                    String dfini=(añoi+"/"+mesi+"/"+diai);
                    int añot=fecter.getCalendar().get(Calendar.YEAR);
                    int mest=fecter.getCalendar().get(Calendar.MONTH)+1;
                    int diat=fecter.getCalendar().get(Calendar.DAY_OF_MONTH);
                    String dfter=(añot+"/"+mest+"/"+diat);
                    e.Eliminar(dnumtra, dnumcon, dcausa, dfini, dhorini, dfter, dhorter, Acceso.getClaveUsuario());
                    JOptionPane.showMessageDialog(this, "Registro eliminado .....");
                    Iniciar();
                }
            }
        }
    }//GEN-LAST:event_eliminarActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        Iniciar();
    }//GEN-LAST:event_cancelarActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        this.dispose();
    }//GEN-LAST:event_salirActionPerformed

    private void tablaaprivMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaaprivMouseClicked
        DefaultTableModel modelo= (DefaultTableModel) tablaapriv.getModel();
        causa.setSelectedItem(modelo.getValueAt(tablaapriv.getSelectedRow(), 0)+"");
        String fini = (modelo.getValueAt(tablaapriv.getSelectedRow(), 1)+"");
        if("null".equals(fini)){
            System.out.println("La fecha de inicio esta vacia .....");
        }
        else{
            SimpleDateFormat formatofecha1=new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            try{
                Date fecha1 = formatofecha1.parse(fini);
                fecini.setDate(fecha1);
            }
            catch(ParseException pe1){
            System.out.println("Error Parse1: "+pe1.getMessage());
            }
        }
        horini.setText(modelo.getValueAt(tablaapriv.getSelectedRow(), 2)+"");
        String fter = (modelo.getValueAt(tablaapriv.getSelectedRow(), 3)+"");
        if("null".equals(fter)){
            System.out.println("La fecha de término esta vacia .....");
        }
        else{
            SimpleDateFormat formatofecha2=new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            try{
                Date fecha2 = formatofecha2.parse(fter);
                fecter.setDate(fecha2);
            }
            catch(ParseException pe2){
            System.out.println("Error Parse2: "+pe2.getMessage());
            }
        }
        horter.setText(modelo.getValueAt(tablaapriv.getSelectedRow(), 4)+"");
        
        int dnumtra=Contr.getNumTrabaja();
        String dnumcon=Contr.getNcoTrabaja();
        String dcausa=causa.getSelectedItem().toString();
        String dhorini=horini.getText();
        String dhorter=horter.getText();
        Apriv com=new Apriv();
        Object[] datos1=com.Comple(dnumtra, dnumcon, dcausa, fini, dhorini, fter, dhorter);
        patgen.setText(datos1[0]+"");
        justif.setSelectedItem(datos1[1]+"");
        caracte.setText(datos1[2]+"");
        patjus.setText(datos1[3]+"");
        reanuda.setSelectedItem(datos1[4]+"");
        String frea = datos1[5]+"";
        if("null".equals(frea)){
            System.out.println("La fecha de reanudación esta vacia .....");
        }
        else{
            SimpleDateFormat formatofecha3=new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            try{
                Date fecha3 = formatofecha3.parse(frea);
                fecrea.setDate(fecha3);
            }
            catch(ParseException pe3){
                System.out.println("Error Parse3: "+pe3.getMessage());
            }
        }
        horrea.setText(datos1[6]+"");
        pervac.setText(datos1[7]+"");
        observa.setText(datos1[8]+"");
        status.setText(datos1[9]+"");
        fecha.setText(datos1[10]+"");
        usuario.setText(datos1[11]+"");
        crear.setEnabled(false);
        causa.setEnabled(false);
        fecini.setEnabled(false);
    }//GEN-LAST:event_tablaaprivMouseClicked

    private void patgenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_patgenMouseClicked
        Apriv.setPath1Usuario(patgen.getText().toUpperCase());
        VAprivConsola1 object=new VAprivConsola1();
        object.setVisible(true);
    }//GEN-LAST:event_patgenMouseClicked

    private void patjusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_patjusMouseClicked
        Apriv.setPath2Usuario(patjus.getText().toUpperCase());
        VAprivConsola2 object=new VAprivConsola2();
        object.setVisible(true);
    }//GEN-LAST:event_patjusMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AprivConsola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AprivConsola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AprivConsola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AprivConsola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AprivConsola().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizar;
    private javax.swing.JButton cancelar;
    private javax.swing.JTextField caracte;
    private javax.swing.JComboBox causa;
    private javax.swing.JButton crear;
    private javax.swing.JButton eliminar;
    private javax.swing.JTextField fecha;
    private com.toedter.calendar.JDateChooser fecini;
    private com.toedter.calendar.JDateChooser fecrea;
    private com.toedter.calendar.JDateChooser fecter;
    private javax.swing.JTextField horini;
    private javax.swing.JTextField horrea;
    private javax.swing.JTextField horter;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox justif;
    private javax.swing.JTextField observa;
    private javax.swing.JTextField patgen;
    private javax.swing.JTextField patjus;
    private javax.swing.JTextField pervac;
    private javax.swing.JComboBox reanuda;
    private javax.swing.JButton salir;
    private javax.swing.JTextField status;
    private javax.swing.JTable tablaapriv;
    private javax.swing.JTextField txtContrato;
    private javax.swing.JTextField txtEmpresa;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtTrabaja;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
