
package sirh;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

public class BenefAConsola extends javax.swing.JFrame {


    public BenefAConsola() {
        initComponents();
        setDefaultCloseOperation(0);
        Iniciar();
    }

    private void Limpiar(JTable tabla){
        while(tabla.getRowCount()>0){
            ((DefaultTableModel) tabla.getModel()).removeRow(0);
        }
    }
    
    private void Iniciar(){
        fecha.setText(fechaActual());
        usuario.setText(Acceso.getClaveUsuario());
        txtNombre.setText(Acceso.getNombreUsuario());
        txtEmpresa.setText(Acceso.getEmpresaUsuario());
        txtRfc.setText(TrabaA.getRfcUsuario());
        txtTrabaja.setText(TrabaA.getNomTrabaja());
        
        String RegFed = TrabaA.getRfcUsuario();
        Limpiar(tablabenef);
        DefaultTableModel modelo=(DefaultTableModel) tablabenef.getModel();
        BenefA e=new BenefA();
        e.LlenarDatos(modelo, RegFed);
        
        tipo.removeAllItems();
        tipo.addItem("");
        BenefA e1=new BenefA();
        e1.LlenarTipo(tipo);
        paterno.setText("");
        materno.setText("");
        nombre.setText("");
        fnacim.setDate(null);
        sexo.removeAllItems();
        sexo.addItem("");
        BenefA e2=new BenefA();
        e2.LlenarSexo(sexo);
        porcentaje.setText("");
        observa.setText("");
        status.setText("");
        crear.setEnabled(true);
        tipo.setEnabled(true);
        materno.setEnabled(true);
        paterno.setEnabled(true);
        nombre.setEnabled(true);
    }
    
    public static String fechaActual(){
        Date fecha= new Date();
        SimpleDateFormat formatoFecha=new SimpleDateFormat("dd/MM/YYYY HH:mm:ss");
        return formatoFecha.format(fecha);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablabenef = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        tipo = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        paterno = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        materno = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        fnacim = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        sexo = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        porcentaje = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        observa = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        status = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        fecha = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        crear = new javax.swing.JButton();
        actualizar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtEmpresa = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtRfc = new javax.swing.JTextField();
        txtTrabaja = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SNTIAISCRM Sistema de Recursos Humanos");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        tablabenef.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tipo", "Paterno", "Materno", "Nombre", "Fecha Nacim.", "Sexo", "Porcentaje", "Observaciones", "Status", "Ultima Fecha", "Ultimo Usuario"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablabenef.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablabenefMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablabenef);

        jLabel2.setForeground(new java.awt.Color(204, 0, 51));
        jLabel2.setText("Tipo Pariente:");

        jLabel3.setForeground(new java.awt.Color(204, 0, 51));
        jLabel3.setText("Paterno:");

        jLabel4.setForeground(new java.awt.Color(204, 0, 51));
        jLabel4.setText("Materno:");

        jLabel5.setForeground(new java.awt.Color(204, 0, 51));
        jLabel5.setText("Nombre:");

        jLabel6.setForeground(new java.awt.Color(204, 0, 51));
        jLabel6.setText("Nacimiento:");

        jLabel7.setText("Sexo:");

        jLabel8.setText("Porcentaje:");

        porcentaje.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                porcentajeKeyTyped(evt);
            }
        });

        jLabel9.setText("Observaciones:");

        jLabel10.setText("Status:");

        status.setEditable(false);

        jLabel11.setText("Fecha:");

        fecha.setEditable(false);

        jLabel12.setText("Usuario:");

        usuario.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nombre)
                            .addComponent(paterno)
                            .addComponent(materno, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(porcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(observa, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6))
                                .addGap(37, 37, 37)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fnacim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(sexo, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel10))
                                .addGap(28, 28, 28))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(23, 23, 23)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(usuario, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                            .addComponent(fecha, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(status, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)
                        .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6))
                    .addComponent(fnacim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(materno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(porcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(observa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        crear.setText("Crear");
        crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearActionPerformed(evt);
            }
        });

        actualizar.setText("Actualizar");
        actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarActionPerformed(evt);
            }
        });

        eliminar.setText("Eliminar");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addComponent(crear)
                .addGap(18, 18, 18)
                .addComponent(actualizar)
                .addGap(18, 18, 18)
                .addComponent(eliminar)
                .addGap(18, 18, 18)
                .addComponent(cancelar)
                .addGap(18, 18, 18)
                .addComponent(salir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crear)
                    .addComponent(actualizar)
                    .addComponent(eliminar)
                    .addComponent(cancelar)
                    .addComponent(salir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("MOVIMIENTOS DE BENEFICIARIOS (Aspirantes)");

        txtEmpresa.setEditable(false);
        txtEmpresa.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        txtEmpresa.setForeground(new java.awt.Color(204, 0, 0));
        txtEmpresa.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtEmpresa.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtNombre.setEditable(false);
        txtNombre.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(204, 0, 0));
        txtNombre.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtNombre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtRfc.setEditable(false);

        txtTrabaja.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtRfc, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTrabaja, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 182, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmpresa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRfc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTrabaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablabenefMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablabenefMouseClicked
        DefaultTableModel modelo= (DefaultTableModel) tablabenef.getModel();
        tipo.setSelectedItem(modelo.getValueAt(tablabenef.getSelectedRow(), 0)+"");
        paterno.setText(modelo.getValueAt(tablabenef.getSelectedRow(), 1)+"");
        materno.setText(modelo.getValueAt(tablabenef.getSelectedRow(), 2)+"");
        nombre.setText(modelo.getValueAt(tablabenef.getSelectedRow(), 3)+"");
        String fecini = (modelo.getValueAt(tablabenef.getSelectedRow(), 4)+"");
        if("null".equals(fecini)){
            System.out.println("La fecha de nacimiento esta vacia .....");
        }
        else{
            SimpleDateFormat formatofecha1=new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            try{
                Date fecha1 = formatofecha1.parse(fecini);
                fnacim.setDate(fecha1);
            }
            catch(ParseException pe1){
                System.out.println("Error Parse1: "+pe1.getMessage());
            }
        }
        sexo.setSelectedItem(modelo.getValueAt(tablabenef.getSelectedRow(), 5)+"");
        porcentaje.setText(modelo.getValueAt(tablabenef.getSelectedRow(), 6)+"");
        observa.setText(modelo.getValueAt(tablabenef.getSelectedRow(), 7)+"");
        status.setText(modelo.getValueAt(tablabenef.getSelectedRow(), 8)+"");
        fecha.setText(modelo.getValueAt(tablabenef.getSelectedRow(), 9)+"");
        usuario.setText(modelo.getValueAt(tablabenef.getSelectedRow(), 10)+"");
        crear.setEnabled(false);
        tipo.setEnabled(false);
        materno.setEnabled(false);
        paterno.setEnabled(false);
        nombre.setEnabled(false);
    }//GEN-LAST:event_tablabenefMouseClicked

    private void crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearActionPerformed
        BenefA e=new BenefA();
        String dtipo=tipo.getSelectedItem().toString();
        if(dtipo.isEmpty()){
            JOptionPane.showMessageDialog(this, "Se requiere un tipo de parentesco, verifique .....");
            tipo.grabFocus();
        }
        else{
            String dpaterno=paterno.getText().toUpperCase();
            if(dpaterno.isEmpty()){
                JOptionPane.showMessageDialog(this, "Se requiere un apellido paterno (1), verifique .....");
                paterno.grabFocus();
            }
            else{
                if(dpaterno.trim().equals("")){
                    JOptionPane.showMessageDialog(this, "Se requiere un apellido paterno (2), verifique .....");
                    paterno.setText("");
                    paterno.grabFocus();
                }
                else{
                    String dmaterno=materno.getText().toUpperCase();
                    if(dmaterno.isEmpty()){
                        JOptionPane.showMessageDialog(this, "Se requiere un apellido materno (1), verifique .....");
                        materno.grabFocus();
                    }
                    else{
                        if(dmaterno.trim().equals("")){
                            JOptionPane.showMessageDialog(this, "Se requiere un apellido materno (2), verifique .....");
                            materno.setText("");
                            materno.grabFocus();
                        }
                        else{
                            String dnombre=nombre.getText().toUpperCase();
                            if(dnombre.isEmpty()){
                                JOptionPane.showMessageDialog(this, "Se requiere un nombre (1), verifique .....");
                                nombre.grabFocus();
                            }
                            else{
                                if(dnombre.trim().equals("")){
                                    JOptionPane.showMessageDialog(this, "Se requiere un nombre (2), verifique .....");
                                    nombre.setText("");
                                    nombre.grabFocus();
                                }
                                else{
                                    if(fnacim.getDate() == null){
                                        JOptionPane.showMessageDialog(this, "Se requiere la fecha de nacimiento, verifique .....");
                                        fnacim.grabFocus();
                                    }
                                    else{
                                        int añoi=fnacim.getCalendar().get(Calendar.YEAR);
                                        int mesi=fnacim.getCalendar().get(Calendar.MONTH)+1;
                                        int diai=fnacim.getCalendar().get(Calendar.DAY_OF_MONTH);
                                        String dfnacim=(añoi+"/"+mesi+"/"+diai); 
                                        String dsexo=sexo.getSelectedItem().toString();
                                        Float dporcentaje=Float.parseFloat(porcentaje.getText());
                                        String dobserva=observa.getText().toUpperCase();
                                        e.Agregar(TrabaA.getRfcUsuario(), dtipo, dpaterno, dmaterno, dnombre, dfnacim, dsexo,
                                                  dporcentaje, dobserva, Acceso.getClaveUsuario());
                                        JOptionPane.showMessageDialog(this, "Registro creado .....");
                                        Iniciar();
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_crearActionPerformed

    private void actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarActionPerformed
        BenefA e=new BenefA();
        String dtipo=tipo.getSelectedItem().toString();
        if(dtipo.isEmpty()){
            JOptionPane.showMessageDialog(this, "Se requiere un tipo de parentesco, verifique .....");
            tipo.grabFocus();
        }
        else{
            String dpaterno=paterno.getText().toUpperCase();
            if(dpaterno.isEmpty()){
                JOptionPane.showMessageDialog(this, "Se requiere un apellido paterno (1), verifique .....");
                paterno.grabFocus();
            }
            else{
                if(dpaterno.trim().equals("")){
                    JOptionPane.showMessageDialog(this, "Se requiere un apellido paterno (2), verifique .....");
                    paterno.setText("");
                    paterno.grabFocus();
                }
                else{
                    String dmaterno=materno.getText().toUpperCase();
                    if(dmaterno.isEmpty()){
                        JOptionPane.showMessageDialog(this, "Se requiere un apellido materno (1), verifique .....");
                        materno.grabFocus();
                    }
                    else{
                        if(dmaterno.trim().equals("")){
                            JOptionPane.showMessageDialog(this, "Se requiere un apellido materno (2), verifique .....");
                            materno.setText("");
                            materno.grabFocus();
                        }
                        else{
                            String dnombre=nombre.getText().toUpperCase();
                            if(dnombre.isEmpty()){
                                JOptionPane.showMessageDialog(this, "Se requiere un nombre (1), verifique .....");
                                nombre.grabFocus();
                            }
                            else{
                                if(dnombre.trim().equals("")){
                                    JOptionPane.showMessageDialog(this, "Se requiere un nombre (2), verifique .....");
                                    nombre.setText("");
                                    nombre.grabFocus();
                                }
                                else{
                                    if(fnacim.getDate() == null){
                                        JOptionPane.showMessageDialog(this, "Se requiere la fecha de nacimiento, verifique .....");
                                        fnacim.grabFocus();
                                    }
                                    else{
                                        int añoi=fnacim.getCalendar().get(Calendar.YEAR);
                                        int mesi=fnacim.getCalendar().get(Calendar.MONTH)+1;
                                        int diai=fnacim.getCalendar().get(Calendar.DAY_OF_MONTH);
                                        String dfnacim=(añoi+"/"+mesi+"/"+diai); 
                                        String dsexo=sexo.getSelectedItem().toString();
                                        Float dporcentaje=Float.parseFloat(porcentaje.getText());
                                        String dobserva=observa.getText().toUpperCase();
                                        e.Actualizar(TrabaA.getRfcUsuario(), dtipo, dpaterno, dmaterno, dnombre, dfnacim, dsexo,
                                                    dporcentaje, dobserva, Acceso.getClaveUsuario());
                                        JOptionPane.showMessageDialog(this, "Registro actualizado .....");
                                        Iniciar();
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_actualizarActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        BenefA e=new BenefA();
        String dpaterno=paterno.getText().toUpperCase();
        if(dpaterno.isEmpty()){
            JOptionPane.showMessageDialog(this, "Se requiere un apellido paterno (1), verifique .....");
            paterno.grabFocus();
        }
        else{
            if(dpaterno.trim().equals("")){
                JOptionPane.showMessageDialog(this, "Se requiere un apellido paterno (2), verifique .....");
                paterno.setText("");
                paterno.grabFocus();
            }
            else{
                String dmaterno=materno.getText().toUpperCase();
                if(dmaterno.isEmpty()){
                    JOptionPane.showMessageDialog(this, "Se requiere un apellido materno (1), verifique .....");
                    materno.grabFocus();
                }
                else{
                    if(dmaterno.trim().equals("")){
                        JOptionPane.showMessageDialog(this, "Se requiere un apellido materno (2), verifique .....");
                        materno.setText("");
                        materno.grabFocus();
                    }
                    else{
                        String dnombre=nombre.getText().toUpperCase();
                        if(dnombre.isEmpty()){
                            JOptionPane.showMessageDialog(this, "Se requiere un nombre (1), verifique .....");
                            nombre.grabFocus();
                        }
                        else{
                            if(dnombre.trim().equals("")){
                                JOptionPane.showMessageDialog(this, "Se requiere un nombre (2), verifique .....");
                                nombre.setText("");
                                nombre.grabFocus();
                            }
                            else{
                                e.Eliminar(TrabaA.getRfcUsuario(), dpaterno, dmaterno, dnombre, Acceso.getClaveUsuario());
                                JOptionPane.showMessageDialog(this, "Registro eliminado .....");
                                Iniciar();
                            }
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_eliminarActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        this.dispose();
    }//GEN-LAST:event_salirActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        Iniciar();
    }//GEN-LAST:event_cancelarActionPerformed

    private void porcentajeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_porcentajeKeyTyped
        char car = evt.getKeyChar();
        if((car<'0' || car>'9') && (car != '.'))
        {
            evt.consume();
        }
    }//GEN-LAST:event_porcentajeKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BenefAConsola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BenefAConsola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BenefAConsola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BenefAConsola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BenefAConsola().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizar;
    private javax.swing.JButton cancelar;
    private javax.swing.JButton crear;
    private javax.swing.JButton eliminar;
    private javax.swing.JTextField fecha;
    private com.toedter.calendar.JDateChooser fnacim;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField materno;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField observa;
    private javax.swing.JTextField paterno;
    private javax.swing.JTextField porcentaje;
    private javax.swing.JButton salir;
    private javax.swing.JComboBox sexo;
    private javax.swing.JTextField status;
    private javax.swing.JTable tablabenef;
    private javax.swing.JComboBox tipo;
    private javax.swing.JTextField txtEmpresa;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRfc;
    private javax.swing.JTextField txtTrabaja;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
