
package sirh;

import java.awt.Image;
import java.net.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

public class cContrConsola extends javax.swing.JFrame {


    public cContrConsola() {
        initComponents();
        //setDefaultCloseOperation(0);
        Iniciar();
    }
    
    private void Limpiar(JTable tabla){
        while(tabla.getRowCount()>0){
            ((DefaultTableModel) tabla.getModel()).removeRow(0);
        }
    }
    
    private void Iniciar(){
        try {
            Limpiar(tablatraba);
            Limpiar(tablacontr);
            busnum.setText("");
            bustraba.setText("");
            buscontra.setText("");
            
            String lugarImagen="FTP://SIRH.DYNDNS.ORG/TRABAJADORES/SINFOTO.GIF";
            Image icon=new javax.swing.ImageIcon(new URL(lugarImagen)).getImage().getScaledInstance(txtImagen.getWidth(), txtImagen.getWidth(), Image.SCALE_DEFAULT);
            Icon imagen=new ImageIcon(icon);
            txtImagen.setIcon(imagen);
            
            numcon.setText("");
            stacon.setText("");
            fecsta.setText("");
            cveemp.setText("");
            nomemp.setText("");
            cvedep.setText("");
            nomdep.setText("");
            cvesec.setText("");
            nomsec.setText("");
            cvecat.setText("");
            nomcat.setText("");
            suecat.setText("");
            cvetur.setText("");
            nomtur.setText("");
            cvetip.setText("");
            nomtip.setText("");
            finicio.setText("");
            ftermino.setText("");
            cvesup.setText("");
            nomsup.setText("");
            path.setText("");
            observa.setText("");
            
            fecha.setText("");
            usuario.setText("");
            txtNombre.setText(Acceso.getNombreUsuario());
            txtEmpresa.setText(Acceso.getEmpresaUsuario());
        } catch (MalformedURLException ex) {
            Logger.getLogger(cContrConsola.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablatraba = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        txtImagen = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablacontr = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        numcon = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        stacon = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        fecsta = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cveemp = new javax.swing.JTextField();
        nomemp = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cvedep = new javax.swing.JTextField();
        nomdep = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cvesec = new javax.swing.JTextField();
        nomsec = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cvecat = new javax.swing.JTextField();
        nomcat = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        suecat = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        cvetur = new javax.swing.JTextField();
        nomtur = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        cvetip = new javax.swing.JTextField();
        nomtip = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        finicio = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        ftermino = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        cvesup = new javax.swing.JTextField();
        nomsup = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        path = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        observa = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        status = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        fecha = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        apriv = new javax.swing.JButton();
        preypre = new javax.swing.JButton();
        sanci = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        busnum = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        bustraba = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        buscontra = new javax.swing.JTextField();
        salir = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtEmpresa = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SNTIAISCRM Sistema de Recursos Humanos");
        setMaximumSize(new java.awt.Dimension(1100, 650));
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        tablatraba.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Núm Trab", "Nombre Trab", "RFC Trab", "Status Trab", "Fech Status", "Path Foto", "Num Ctto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablatraba.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablatrabaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablatraba);

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        txtImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtImagen, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        tablacontr.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Num Ctto", "Status Ctto", "Empresa", "Departamento", "Sección", "Categoría", "Turno", "Tipo Ctto", "Inicio", "Término"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablacontr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablacontrMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablacontr);

        jLabel6.setText("Número Contrato:");

        numcon.setEditable(false);

        jLabel7.setText("Status Contrato:");

        stacon.setEditable(false);

        jLabel8.setText("Fecha Status:");

        fecsta.setEditable(false);

        jLabel9.setText("Empresa:");

        cveemp.setEditable(false);

        nomemp.setEditable(false);

        jLabel10.setText("Departamento:");

        cvedep.setEditable(false);

        nomdep.setEditable(false);

        jLabel11.setText("Sección:");

        cvesec.setEditable(false);

        nomsec.setEditable(false);

        jLabel12.setText("Categoría:");

        cvecat.setEditable(false);
        cvecat.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        nomcat.setEditable(false);

        jLabel13.setText("Sueldo Diario:");

        suecat.setEditable(false);

        jLabel14.setText("Turno:");

        cvetur.setEditable(false);

        nomtur.setEditable(false);

        jLabel15.setText("Tipo Contrato:");

        cvetip.setEditable(false);

        nomtip.setEditable(false);

        jLabel16.setText("Fecha Inicio:");

        finicio.setEditable(false);

        jLabel17.setText("Fecha Término:");

        ftermino.setEditable(false);

        jLabel18.setText("Superv Cargo:");

        cvesup.setEditable(false);

        nomsup.setEditable(false);

        jLabel19.setText("Path:");

        path.setEditable(false);
        path.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pathMouseClicked(evt);
            }
        });
        path.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pathActionPerformed(evt);
            }
        });

        jLabel20.setText("Observa:");

        observa.setEditable(false);

        jLabel21.setText("Status:");

        status.setEditable(false);

        jLabel22.setText("Fecha:");

        fecha.setEditable(false);

        jLabel23.setText("Usuario:");

        usuario.setEditable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1058, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(numcon)
                            .addComponent(stacon)
                            .addComponent(fecsta)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(cvecat, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nomcat, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE))
                            .addComponent(suecat)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cveemp, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                                    .addComponent(cvedep)
                                    .addComponent(cvesec))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nomsec)
                                    .addComponent(nomdep)
                                    .addComponent(nomemp))))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel18))
                                .addGap(21, 21, 21)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(74, 74, 74)
                                        .addComponent(nomsup))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cvetur, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                                            .addComponent(cvetip))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(nomtur)
                                            .addComponent(nomtip)))
                                    .addComponent(ftermino, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(finicio, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addComponent(jLabel19)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel20)
                                        .addGap(50, 50, 50))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel21)
                                        .addGap(60, 60, 60)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cvesup, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel22)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel23)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(path, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                                        .addComponent(observa, javax.swing.GroupLayout.Alignment.TRAILING)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(numcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(cvetur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomtur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(stacon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(cvetip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomtip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(fecsta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(finicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cveemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(ftermino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cvedep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomdep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(cvesup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomsup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cvesec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomsec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(path, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cvecat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomcat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(observa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(suecat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        apriv.setForeground(new java.awt.Color(0, 0, 153));
        apriv.setText("Ausencias, Permisos, Retardos, Incapacidades y Vacaciones");
        apriv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aprivActionPerformed(evt);
            }
        });

        preypre.setForeground(new java.awt.Color(0, 0, 153));
        preypre.setText("Premios y Prestaciones");
        preypre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preypreActionPerformed(evt);
            }
        });

        sanci.setForeground(new java.awt.Color(0, 0, 153));
        sanci.setText("Sanciones");
        sanci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sanciActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(231, 231, 231)
                .addComponent(apriv)
                .addGap(18, 18, 18)
                .addComponent(preypre)
                .addGap(18, 18, 18)
                .addComponent(sanci)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apriv)
                    .addComponent(preypre)
                    .addComponent(sanci))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jLabel1.setText("Número de Trabajador:");

        busnum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                busnumMouseClicked(evt);
            }
        });
        busnum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                busnumKeyPressed(evt);
            }
        });

        jLabel2.setText("Nombre Trabajador:");

        bustraba.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bustrabaMouseClicked(evt);
            }
        });
        bustraba.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bustrabaKeyPressed(evt);
            }
        });

        jLabel3.setText("Número de Contrato:");

        buscontra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buscontraMouseClicked(evt);
            }
        });
        buscontra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                buscontraKeyPressed(evt);
            }
        });

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(busnum, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bustraba, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buscontra, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(busnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(bustraba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(buscontra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("BUSQUEDA DE CONTRATOS DE TRABAJADORES");

        txtEmpresa.setEditable(false);
        txtEmpresa.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        txtEmpresa.setForeground(new java.awt.Color(204, 0, 0));
        txtEmpresa.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtEmpresa.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtNombre.setEditable(false);
        txtNombre.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(204, 0, 0));
        txtNombre.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtNombre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pathActionPerformed
        // NO SE UTILIZA
    }//GEN-LAST:event_pathActionPerformed

    private void aprivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aprivActionPerformed
        cAprivConsola object=new cAprivConsola();
        object.setLocationRelativeTo(null);
        object.setVisible(true);
    }//GEN-LAST:event_aprivActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        this.dispose();
    }//GEN-LAST:event_salirActionPerformed

    private void preypreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preypreActionPerformed
        cPryprConsola object=new cPryprConsola();
        object.setLocationRelativeTo(null);
        object.setVisible(true);
    }//GEN-LAST:event_preypreActionPerformed

    private void sanciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sanciActionPerformed
        cSanciConsola object=new cSanciConsola();
        object.setLocationRelativeTo(null);
        object.setVisible(true);
    }//GEN-LAST:event_sanciActionPerformed

    private void busnumKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_busnumKeyPressed
        cContr e=new cContr();
        Limpiar(tablatraba);
        DefaultTableModel modelo= (DefaultTableModel) tablatraba.getModel();
        e.BusNum(modelo, busnum.getText().toUpperCase());
    }//GEN-LAST:event_busnumKeyPressed

    private void busnumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_busnumMouseClicked
        Iniciar();
    }//GEN-LAST:event_busnumMouseClicked

    private void bustrabaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bustrabaKeyPressed
        cContr e=new cContr();
        Limpiar(tablatraba);
        DefaultTableModel modelo= (DefaultTableModel) tablatraba.getModel();
        e.BusNum(modelo, bustraba.getText().toUpperCase());
    }//GEN-LAST:event_bustrabaKeyPressed

    private void bustrabaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bustrabaMouseClicked
        Iniciar();
    }//GEN-LAST:event_bustrabaMouseClicked

    private void buscontraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscontraKeyPressed
        cContr e=new cContr();
        Limpiar(tablatraba);
        DefaultTableModel modelo= (DefaultTableModel) tablatraba.getModel();
        e.BusNum(modelo, buscontra.getText().toUpperCase());
    }//GEN-LAST:event_buscontraKeyPressed

    private void buscontraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscontraMouseClicked
        Iniciar();
    }//GEN-LAST:event_buscontraMouseClicked

    private void tablatrabaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablatrabaMouseClicked
        try {
            DefaultTableModel modelo= (DefaultTableModel) tablatraba.getModel();
            int NumTra = Integer.parseInt(modelo.getValueAt(tablatraba.getSelectedRow(), 0)+"");
            String NomTra = modelo.getValueAt(tablatraba.getSelectedRow(), 1)+"";
            cContr.setNumTrabaja(NumTra);
            cContr.setNomTrabaja(NomTra);
            String lugarImagen = modelo.getValueAt(tablatraba.getSelectedRow(), 5)+"";
            
            
            Image icon=new javax.swing.ImageIcon(new URL(lugarImagen)).getImage().getScaledInstance(txtImagen.getWidth(), txtImagen.getWidth(), Image.SCALE_DEFAULT);
            Icon imagen=new ImageIcon(icon);
            txtImagen.setIcon(imagen);
            
            cContr e=new cContr();
            Limpiar(tablacontr);
            DefaultTableModel modelo1= (DefaultTableModel) tablacontr.getModel();
            e.LlenarDatos(modelo1, NumTra);
        } catch (MalformedURLException ex) {
            Logger.getLogger(cContrConsola.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tablatrabaMouseClicked

    private void tablacontrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablacontrMouseClicked
        DefaultTableModel modelo1= (DefaultTableModel) tablacontr.getModel();
        numcon.setText(modelo1.getValueAt(tablacontr.getSelectedRow(), 0)+"");
        cContr.setNcoTrabaja(numcon.getText());
        stacon.setText(modelo1.getValueAt(tablacontr.getSelectedRow(), 1)+"");
        nomemp.setText(modelo1.getValueAt(tablacontr.getSelectedRow(), 2)+"");
        nomdep.setText(modelo1.getValueAt(tablacontr.getSelectedRow(), 3)+"");
        nomsec.setText(modelo1.getValueAt(tablacontr.getSelectedRow(), 4)+"");
        nomcat.setText(modelo1.getValueAt(tablacontr.getSelectedRow(), 5)+"");
        nomtur.setText(modelo1.getValueAt(tablacontr.getSelectedRow(), 6)+"");
        nomtip.setText(modelo1.getValueAt(tablacontr.getSelectedRow(), 7)+"");
        finicio.setText(modelo1.getValueAt(tablacontr.getSelectedRow(), 8)+"");
        ftermino.setText(modelo1.getValueAt(tablacontr.getSelectedRow(), 9)+"");
        
        cContr com2=new cContr();
        Object[] datos1=com2.Comple(numcon.getText());
        fecsta.setText(datos1[0]+"");
        cveemp.setText(datos1[1]+"");
        cvedep.setText(datos1[2]+"");
        cvesec.setText(datos1[3]+"");
        cvecat.setText(datos1[4]+"");
        suecat.setText(datos1[5]+"");
        cvetur.setText(datos1[6]+"");
        cvetip.setText(datos1[7]+"");
        cvesup.setText(datos1[8]+"");
        nomsup.setText(datos1[9]+"");
        path.setText(datos1[10]+"");
        observa.setText(datos1[11]+"");
        status.setText(datos1[12]+"");
        fecha.setText(datos1[13]+"");
        usuario.setText(datos1[14]+"");
    }//GEN-LAST:event_tablacontrMouseClicked

    private void pathMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pathMouseClicked
        cContr.setPathUsuario(path.getText().toUpperCase());
        cVContrConsola object=new cVContrConsola();
        object.setVisible(true);
    }//GEN-LAST:event_pathMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cContrConsola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cContrConsola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cContrConsola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cContrConsola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cContrConsola().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton apriv;
    private javax.swing.JTextField buscontra;
    private javax.swing.JTextField busnum;
    private javax.swing.JTextField bustraba;
    private javax.swing.JTextField cvecat;
    private javax.swing.JTextField cvedep;
    private javax.swing.JTextField cveemp;
    private javax.swing.JTextField cvesec;
    private javax.swing.JTextField cvesup;
    private javax.swing.JTextField cvetip;
    private javax.swing.JTextField cvetur;
    private javax.swing.JTextField fecha;
    private javax.swing.JTextField fecsta;
    private javax.swing.JTextField finicio;
    private javax.swing.JTextField ftermino;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nomcat;
    private javax.swing.JTextField nomdep;
    private javax.swing.JTextField nomemp;
    private javax.swing.JTextField nomsec;
    private javax.swing.JTextField nomsup;
    private javax.swing.JTextField nomtip;
    private javax.swing.JTextField nomtur;
    private javax.swing.JTextField numcon;
    private javax.swing.JTextField observa;
    private javax.swing.JTextField path;
    private javax.swing.JButton preypre;
    private javax.swing.JButton salir;
    private javax.swing.JButton sanci;
    private javax.swing.JTextField stacon;
    private javax.swing.JTextField status;
    private javax.swing.JTextField suecat;
    private javax.swing.JTable tablacontr;
    private javax.swing.JTable tablatraba;
    private javax.swing.JTextField txtEmpresa;
    private javax.swing.JLabel txtImagen;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
