
package sirh;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

public class ChofeConsola extends javax.swing.JFrame {


    public ChofeConsola() {
        initComponents();
        setDefaultCloseOperation(0);
        Iniciar();
    }
    
    private void Limpiar(JTable tabla){
        while(tabla.getRowCount()>0){
            ((DefaultTableModel) tabla.getModel()).removeRow(0);
        }
    }
    
    private void Iniciar(){
        Limpiar(tablachofe);
        DefaultTableModel modelo=(DefaultTableModel) tablachofe.getModel();
        Chofe e1=new Chofe();
        e1.LlenarDatos(modelo);
        rfc.setText("");
        curp.setText("");
        paterno.setText("");
        materno.setText("");
        nombre.setText("");
        fecnac.setDate(null);
        sexo.removeAllItems();
        sexo.addItem("");
        Chofe e2=new Chofe();
        e2.LlenarSexo(sexo);
        maxim.setText("");
        civil.removeAllItems();
        civil.addItem("");
        Chofe e3=new Chofe();
        e3.LlenarCivil(civil);
        teldom.setText("");
        telcel.setText("");
        correo.setText("");
        pais.removeAllItems();
        pais.addItem("");
        Chofe e4=new Chofe();
        e4.LlenarPadom(pais);
        estado.removeAllItems();
        estado.addItem("");
        mundel.removeAllItems();
        mundel.addItem("");
        pobla.removeAllItems();
        pobla.addItem("");
        colonia.removeAllItems();
        colonia.addItem("");
        calle.setText("");
        numext.setText("");
        numint.setText("");
        codpos.setText("");
        
        Limpiar(tablachofe1);
        busrfc.setText("");
        buspat.setText("");
        busmat.setText("");
        busnom.setText("");
        rfc1.setText("");
        curp1.setText("");
        paterno1.setText("");
        materno1.setText("");
        nombre1.setText("");
        fecnac1.setText("");
        sexo1.setText("");
        maxim1.setText("");
        civil1.setText("");
        teldom1.setText("");
        telcel1.setText("");
        correo1.setText("");
        pais1.setText("");
        estado1.setText("");
        mundel1.setText("");
        pobla1.setText("");
        colonia1.setText("");
        calle.setText("");
        numext.setText("");
        numint.setText("");
        codpos.setText("");
        fecha1.setText("");
        usuario1.setText("");
        
        fecha.setText(fechaActual());
        usuario.setText(Acceso.getClaveUsuario());
        txtNombre.setText(Acceso.getNombreUsuario());
        txtEmpresa.setText(Acceso.getEmpresaUsuario());
        crear.setEnabled(true);
        rfc.setEnabled(true);
        
    }
    
    public static String fechaActual(){
        Date fecha= new Date();
        SimpleDateFormat formatoFecha=new SimpleDateFormat("dd/MM/YYYY HH:mm:ss");
        return formatoFecha.format(fecha);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtEmpresa = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablachofe1 = new javax.swing.JTable();
        jLabel26 = new javax.swing.JLabel();
        busrfc = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        buspat = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        busmat = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        busnom = new javax.swing.JTextField();
        salir1 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        rfc1 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        curp1 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        paterno1 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        materno1 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        nombre1 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        maxim1 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        teldom1 = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        telcel1 = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        correo1 = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        calle1 = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        numext1 = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        numint1 = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        codpos1 = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        fecha1 = new javax.swing.JTextField();
        jLabel53 = new javax.swing.JLabel();
        usuario1 = new javax.swing.JTextField();
        fecnac1 = new javax.swing.JTextField();
        sexo1 = new javax.swing.JTextField();
        civil1 = new javax.swing.JTextField();
        pais1 = new javax.swing.JTextField();
        estado1 = new javax.swing.JTextField();
        mundel1 = new javax.swing.JTextField();
        pobla1 = new javax.swing.JTextField();
        colonia1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablachofe = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        rfc = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        curp = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        paterno = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        materno = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        fecnac = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        sexo = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        maxim = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        civil = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        teldom = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        telcel = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        correo = new javax.swing.JTextField();
        crear = new javax.swing.JButton();
        actualizar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        pais = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        estado = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        mundel = new javax.swing.JComboBox();
        jLabel18 = new javax.swing.JLabel();
        pobla = new javax.swing.JComboBox();
        jLabel19 = new javax.swing.JLabel();
        colonia = new javax.swing.JComboBox();
        jLabel20 = new javax.swing.JLabel();
        calle = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        numext = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        numint = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        codpos = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        fecha = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SNTIAISCRM Sistema de Recursos Humanos");
        setMaximumSize(new java.awt.Dimension(908, 600));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("CHOFERES DE TRANSPORTE DE PERSONAL");

        txtEmpresa.setEditable(false);
        txtEmpresa.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        txtEmpresa.setForeground(new java.awt.Color(204, 0, 0));
        txtEmpresa.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtEmpresa.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtNombre.setEditable(false);
        txtNombre.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(204, 0, 0));
        txtNombre.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtNombre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tablachofe1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RFC", "CURP", "Apellido Paterno", "Apellido Materno", "Nombre(s)", "Status", "Ultima Fecha", "Ultimo Usuario"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablachofe1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablachofe1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablachofe1);

        jLabel26.setText("RFC:");

        busrfc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                busrfcMouseClicked(evt);
            }
        });
        busrfc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                busrfcKeyPressed(evt);
            }
        });

        jLabel27.setText("Paterno:");

        buspat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buspatMouseClicked(evt);
            }
        });
        buspat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                buspatKeyPressed(evt);
            }
        });

        jLabel28.setText("Materno:");

        busmat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                busmatMouseClicked(evt);
            }
        });
        busmat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                busmatKeyPressed(evt);
            }
        });

        jLabel29.setText("Nombre:");

        busnom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                busnomMouseClicked(evt);
            }
        });
        busnom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                busnomKeyPressed(evt);
            }
        });

        salir1.setText("Salir");
        salir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salir1ActionPerformed(evt);
            }
        });

        jLabel30.setText("RFC:");

        rfc1.setEditable(false);

        jLabel31.setText("CURP:");

        curp1.setEditable(false);

        jLabel32.setText("A. Paterno:");

        paterno1.setEditable(false);

        jLabel33.setText("A. Materno:");

        materno1.setEditable(false);

        jLabel34.setText("Nombre(s):");

        nombre1.setEditable(false);

        jLabel35.setText("Fec. Nacim:");

        jLabel36.setText("Género:");

        jLabel37.setText("Max Estudios:");

        maxim1.setEditable(false);

        jLabel38.setText("Estado Civil:");

        jLabel39.setText("Teléfono:");

        teldom1.setEditable(false);

        jLabel40.setText("Celular:");

        telcel1.setEditable(false);

        jLabel41.setText("Correo:");

        correo1.setEditable(false);

        jLabel42.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel42.setText("Domicilio Particular");

        jLabel43.setText("País:");

        jLabel44.setText("Estado:");

        jLabel45.setText("Mun/Del:");

        jLabel46.setText("Población:");

        jLabel47.setText("Colonia:");

        jLabel48.setText("Calle:");

        calle1.setEditable(false);

        jLabel49.setText("Num. Ext:");

        numext1.setEditable(false);

        jLabel50.setText("Num. Int:");

        numint1.setEditable(false);

        jLabel51.setText("Código Postal:");

        codpos1.setEditable(false);
        codpos1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                codpos1KeyTyped(evt);
            }
        });

        jLabel52.setText("Fecha:");

        fecha1.setEditable(false);

        jLabel53.setText("Usuario:");

        usuario1.setEditable(false);

        fecnac1.setEditable(false);

        sexo1.setEditable(false);

        civil1.setEditable(false);

        pais1.setEditable(false);

        estado1.setEditable(false);

        mundel1.setEditable(false);

        pobla1.setEditable(false);

        colonia1.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addGap(18, 18, 18)
                        .addComponent(busrfc, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel27)
                        .addGap(18, 18, 18)
                        .addComponent(buspat, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel28)
                        .addGap(18, 18, 18)
                        .addComponent(busmat, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel29)
                        .addGap(18, 18, 18)
                        .addComponent(busnom, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                        .addComponent(salir1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel37)
                                    .addComponent(jLabel38)
                                    .addComponent(jLabel39)
                                    .addComponent(jLabel40)
                                    .addComponent(jLabel41))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(teldom1)
                                            .addComponent(telcel1)
                                            .addComponent(correo1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(maxim1, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                                            .addComponent(civil1))
                                        .addGap(23, 23, 23))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel30)
                                    .addComponent(jLabel31)
                                    .addComponent(jLabel32)
                                    .addComponent(jLabel33)
                                    .addComponent(jLabel34)
                                    .addComponent(jLabel35)
                                    .addComponent(jLabel36))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(rfc1)
                                    .addComponent(curp1)
                                    .addComponent(paterno1)
                                    .addComponent(materno1)
                                    .addComponent(nombre1)
                                    .addComponent(fecnac1)
                                    .addComponent(sexo1, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel42)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel43)
                                    .addComponent(jLabel44)
                                    .addComponent(jLabel45)
                                    .addComponent(jLabel46)
                                    .addComponent(jLabel47)
                                    .addComponent(jLabel48)
                                    .addComponent(jLabel49)
                                    .addComponent(jLabel50)
                                    .addComponent(jLabel51)
                                    .addComponent(jLabel52)
                                    .addComponent(jLabel53))
                                .addGap(36, 36, 36)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(usuario1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                    .addComponent(fecha1)
                                    .addComponent(numint1)
                                    .addComponent(numext1)
                                    .addComponent(calle1)
                                    .addComponent(pais1)
                                    .addComponent(estado1)
                                    .addComponent(mundel1)
                                    .addComponent(pobla1)
                                    .addComponent(colonia1)
                                    .addComponent(codpos1, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(busrfc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27)
                    .addComponent(buspat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28)
                    .addComponent(busmat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29)
                    .addComponent(busnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salir1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(rfc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel42))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(curp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel43)
                    .addComponent(pais1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(paterno1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel44)
                    .addComponent(estado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(materno1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel45)
                    .addComponent(mundel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel46)
                    .addComponent(pobla1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel35)
                        .addComponent(fecnac1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel47)
                        .addComponent(colonia1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel36)
                        .addComponent(sexo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel48)
                        .addComponent(calle1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(maxim1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel49)
                    .addComponent(numext1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(jLabel50)
                    .addComponent(numint1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(civil1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel39)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(teldom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel51)
                        .addComponent(codpos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(telcel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel52)
                    .addComponent(fecha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel41)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(correo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel53)
                        .addComponent(usuario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Búsqueda", jPanel1);

        tablachofe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RFC", "CURP", "Apellido Paterno", "Apellido Materno", "Nombre(s)", "Status", "Ultima Fecha", "Ultimo Usuario"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablachofe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablachofeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablachofe);

        jLabel2.setForeground(new java.awt.Color(204, 0, 51));
        jLabel2.setText("RFC:");

        jLabel3.setText("CURP:");

        jLabel4.setText("A. Paterno:");

        jLabel5.setText("A. Materno:");

        jLabel6.setText("Nombre(s):");

        jLabel7.setForeground(new java.awt.Color(204, 0, 51));
        jLabel7.setText("Fec. Nacim:");

        jLabel8.setText("Género:");

        jLabel9.setText("Max Estudios:");

        jLabel10.setText("Estado Civil:");

        jLabel11.setText("Teléfono:");

        jLabel12.setText("Celular:");

        jLabel13.setText("Correo:");

        crear.setText("Crear");
        crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearActionPerformed(evt);
            }
        });

        actualizar.setText("Actualizar");
        actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarActionPerformed(evt);
            }
        });

        eliminar.setText("Eliminar");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Domicilio Particular");

        jLabel15.setText("País:");

        pais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paisActionPerformed(evt);
            }
        });

        jLabel16.setText("Estado:");

        estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoActionPerformed(evt);
            }
        });

        jLabel17.setText("Mun/Del:");

        mundel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mundelActionPerformed(evt);
            }
        });

        jLabel18.setText("Población:");

        pobla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poblaActionPerformed(evt);
            }
        });

        jLabel19.setText("Colonia:");

        jLabel20.setText("Calle:");

        jLabel21.setText("Num. Ext:");

        jLabel22.setText("Num. Int:");

        jLabel23.setText("Código Postal:");

        codpos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                codposKeyTyped(evt);
            }
        });

        jLabel24.setText("Fecha:");

        fecha.setEditable(false);

        jLabel25.setText("Usuario:");

        usuario.setEditable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(teldom)
                                            .addComponent(telcel)
                                            .addComponent(correo, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(civil, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(maxim, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(23, 23, 23))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(rfc)
                                    .addComponent(curp)
                                    .addComponent(paterno)
                                    .addComponent(materno)
                                    .addComponent(nombre)
                                    .addComponent(fecnac, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                                    .addComponent(sexo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel25))
                                .addGap(36, 36, 36)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(usuario)
                                    .addComponent(fecha)
                                    .addComponent(numint)
                                    .addComponent(numext)
                                    .addComponent(calle)
                                    .addComponent(pais, 0, 300, Short.MAX_VALUE)
                                    .addComponent(estado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(mundel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(pobla, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(colonia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(codpos))))
                        .addGap(17, 17, 17)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addComponent(crear)
                .addGap(18, 18, 18)
                .addComponent(actualizar)
                .addGap(18, 18, 18)
                .addComponent(eliminar)
                .addGap(18, 18, 18)
                .addComponent(cancelar)
                .addGap(18, 18, 18)
                .addComponent(salir)
                .addContainerGap(250, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(rfc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(curp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(pais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(paterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(materno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(mundel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(pobla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(fecnac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel19)
                        .addComponent(colonia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel20)
                        .addComponent(calle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(maxim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(numext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(civil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(numint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(teldom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel23)
                        .addComponent(codpos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(telcel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel25)
                        .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crear)
                    .addComponent(actualizar)
                    .addComponent(eliminar)
                    .addComponent(cancelar)
                    .addComponent(salir))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Movimientos", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearActionPerformed
        Chofe e=new Chofe();
        String drfc=rfc.getText().toUpperCase();
        if(drfc.isEmpty()){
            JOptionPane.showMessageDialog(this, "Se requiere un Rfc, verifique .....");
            rfc.grabFocus();
        }
        else{
            if(fecnac.getDate() == null){
                JOptionPane.showMessageDialog(this, "Se requiere una fecha de nacimiento, verifique .....");
                fecnac.grabFocus();
            }
            else{
                String dcurp=curp.getText().toUpperCase();
                String dpaterno=paterno.getText().toUpperCase();
                String dmaterno=materno.getText().toUpperCase();
                String dnombre=nombre.getText().toUpperCase();
                String dsexo=sexo.getSelectedItem().toString();
                int año=fecnac.getCalendar().get(Calendar.YEAR);
                int mes=fecnac.getCalendar().get(Calendar.MONTH)+1;
                int dia=fecnac.getCalendar().get(Calendar.DAY_OF_MONTH);
                String dnacim=(año+"/"+mes+"/"+dia);
                String dgrado=maxim.getText().toUpperCase();
                String dcivil=civil.getSelectedItem().toString();
                String dpais=pais.getSelectedItem().toString();
                String destado=estado.getSelectedItem().toString();
                String dmundel=mundel.getSelectedItem().toString();
                String dpobla=pobla.getSelectedItem().toString();
                String dcolonia=colonia.getSelectedItem().toString();
                String dcalle=calle.getText().toUpperCase();
                String dnumext=numext.getText().toUpperCase();
                String dnumint=numint.getText().toUpperCase();
                int dcodpos=Integer.parseInt(codpos.getText().toUpperCase());
                String dteldom=teldom.getText().toUpperCase();
                String dtelcel=telcel.getText().toUpperCase();
                String dcorreo=correo.getText().toUpperCase();
                e.Agregar(drfc, dcurp, dpaterno, dmaterno, dnombre, dsexo, dnacim, dgrado, dcivil, dpais, destado, dmundel, dpobla,
                          dcolonia, dcalle, dnumext, dnumint, dcodpos, dteldom, dtelcel, dcorreo, Acceso.getClaveUsuario());
                JOptionPane.showMessageDialog(this, "Registro creado .....");
                Iniciar();
            }
        } 
    }//GEN-LAST:event_crearActionPerformed

    private void actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarActionPerformed
        Chofe e=new Chofe();
        String drfc=rfc.getText().toUpperCase();
        if(drfc.isEmpty()){
            JOptionPane.showMessageDialog(this, "Se requiere un Rfc, verifique .....");
            rfc.grabFocus();
        }
        else{
            if(fecnac.getDate() == null){
                JOptionPane.showMessageDialog(this, "Se requiere una fecha de nacimiento, verifique .....");
                fecnac.grabFocus();
            }
            else{
                String dcurp=curp.getText().toUpperCase();
                String dpaterno=paterno.getText().toUpperCase();
                String dmaterno=materno.getText().toUpperCase();
                String dnombre=nombre.getText().toUpperCase();
                String dsexo=sexo.getSelectedItem().toString();
                int año=fecnac.getCalendar().get(Calendar.YEAR);
                int mes=fecnac.getCalendar().get(Calendar.MONTH)+1;
                int dia=fecnac.getCalendar().get(Calendar.DAY_OF_MONTH);
                String dnacim=(año+"/"+mes+"/"+dia);
                String dgrado=maxim.getText().toUpperCase();
                String dcivil=civil.getSelectedItem().toString();
                String dpais=pais.getSelectedItem().toString();
                String destado=estado.getSelectedItem().toString();
                String dmundel=mundel.getSelectedItem().toString();
                String dpobla=pobla.getSelectedItem().toString();
                String dcolonia=colonia.getSelectedItem().toString();
                String dcalle=calle.getText().toUpperCase();
                String dnumext=numext.getText().toUpperCase();
                String dnumint=numint.getText().toUpperCase();
                int dcodpos=Integer.parseInt(codpos.getText().toUpperCase());
                String dteldom=teldom.getText().toUpperCase();
                String dtelcel=telcel.getText().toUpperCase();
                String dcorreo=correo.getText().toUpperCase();
                e.Actualizar(drfc, dcurp, dpaterno, dmaterno, dnombre, dsexo, dnacim, dgrado, dcivil, dpais, destado, dmundel, dpobla,
                             dcolonia, dcalle, dnumext, dnumint, dcodpos, dteldom, dtelcel, dcorreo, Acceso.getClaveUsuario());
                JOptionPane.showMessageDialog(this, "Registro actualizado .....");
                Iniciar();
            }
        }
    }//GEN-LAST:event_actualizarActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        Chofe e=new Chofe();
        e.Eliminar(rfc.getText().toUpperCase(), Acceso.getClaveUsuario());
        JOptionPane.showMessageDialog(this, "Registro eliminado .....");
        Iniciar();
    }//GEN-LAST:event_eliminarActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        Iniciar();
    }//GEN-LAST:event_cancelarActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        this.dispose();
    }//GEN-LAST:event_salirActionPerformed

    private void tablachofeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablachofeMouseClicked
        DefaultTableModel modelo= (DefaultTableModel) tablachofe.getModel();
        rfc.setText(modelo.getValueAt(tablachofe.getSelectedRow(), 0)+"");
        curp.setText(modelo.getValueAt(tablachofe.getSelectedRow(), 1)+"");
        paterno.setText(modelo.getValueAt(tablachofe.getSelectedRow(), 2)+"");
        materno.setText(modelo.getValueAt(tablachofe.getSelectedRow(), 3)+"");
        nombre.setText(modelo.getValueAt(tablachofe.getSelectedRow(), 4)+"");
        fecha.setText(modelo.getValueAt(tablachofe.getSelectedRow(), 6)+"");
        usuario.setText(modelo.getValueAt(tablachofe.getSelectedRow(), 7)+"");
        crear.setEnabled(false);
        rfc.setEnabled(false);
        
        String RegFed = rfc.getText();
        String PaAc = paterno.getText();
        String MaAc = materno.getText();
        String NoAc = nombre.getText();
        
        Chofe com=new Chofe();
        Object[] datos=com.Comple(RegFed, PaAc, MaAc, NoAc);
        sexo.setSelectedItem(datos[0]+"");
        String fnacim = datos[1]+"";
        SimpleDateFormat formatofecha=new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        try{
            Date fecha1 = formatofecha.parse(fnacim);
            fecnac.setDate(fecha1);
        }
        catch(ParseException pe1){
            System.out.println("Error Parse1: "+pe1.getMessage());
        }
        maxim.setText(datos[2]+"");
        civil.setSelectedItem(datos[3]+"");
        pais.setSelectedItem(datos[4]+"");
        estado.setSelectedItem(datos[5]+"");
        mundel.setSelectedItem(datos[6]+"");
        pobla.setSelectedItem(datos[7]+"");
        colonia.setSelectedItem(datos[8]+"");
        calle.setText(datos[9]+"");
        numext.setText(datos[10]+"");
        numint.setText(datos[11]+"");
        codpos.setText(datos[12]+"");
        teldom.setText(datos[13]+"");
        telcel.setText(datos[14]+"");
        correo.setText(datos[15]+"");
    }//GEN-LAST:event_tablachofeMouseClicked

    private void paisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paisActionPerformed
        estado.removeAllItems();
        estado.addItem("");
        mundel.removeAllItems();
        mundel.addItem("");
        pobla.removeAllItems();
        pobla.addItem("");
        colonia.removeAllItems();
        colonia.addItem("");
        String paiseleccionado=pais.getSelectedItem()+"";
        Chofe ee1=new Chofe();
        ee1.LlenarEsdom(estado, paiseleccionado);
    }//GEN-LAST:event_paisActionPerformed

    private void estadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadoActionPerformed
        mundel.removeAllItems();
        mundel.addItem("");
        pobla.removeAllItems();
        pobla.addItem("");
        colonia.removeAllItems();
        colonia.addItem("");
        String paiseleccionado=pais.getSelectedItem()+"";
        String edoseleccionado=estado.getSelectedItem()+"";
        Datos ee2=new Datos();
        ee2.LlenarMddom(mundel, paiseleccionado, edoseleccionado);
    }//GEN-LAST:event_estadoActionPerformed

    private void mundelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mundelActionPerformed
        pobla.removeAllItems();
        pobla.addItem("");
        colonia.removeAllItems();
        colonia.addItem("");
        String paiseleccionado=pais.getSelectedItem()+"";
        String edoseleccionado=estado.getSelectedItem()+"";
        String mundelseleccionado=mundel.getSelectedItem()+"";
        Datos ee3=new Datos();
        ee3.LlenarPodom(pobla, paiseleccionado, edoseleccionado, mundelseleccionado);
    }//GEN-LAST:event_mundelActionPerformed

    private void poblaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poblaActionPerformed
        colonia.removeAllItems();
        colonia.addItem("");
        String paiseleccionado=pais.getSelectedItem()+"";
        String edoseleccionado=estado.getSelectedItem()+"";
        String mundelseleccionado=mundel.getSelectedItem()+"";
        String poblaseleccionado=pobla.getSelectedItem()+"";
        Datos ee4=new Datos();
        ee4.LlenarCodom(colonia, paiseleccionado, edoseleccionado, mundelseleccionado, poblaseleccionado);
    }//GEN-LAST:event_poblaActionPerformed

    private void codposKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codposKeyTyped
        char car = evt.getKeyChar();
        if((car<'0' || car>'9')) evt.consume();
    }//GEN-LAST:event_codposKeyTyped

    private void tablachofe1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablachofe1MouseClicked
        DefaultTableModel modelo= (DefaultTableModel) tablachofe1.getModel();
        rfc1.setText(modelo.getValueAt(tablachofe1.getSelectedRow(), 0)+"");
        curp1.setText(modelo.getValueAt(tablachofe1.getSelectedRow(), 1)+"");
        paterno1.setText(modelo.getValueAt(tablachofe1.getSelectedRow(), 2)+"");
        materno1.setText(modelo.getValueAt(tablachofe1.getSelectedRow(), 3)+"");
        nombre1.setText(modelo.getValueAt(tablachofe1.getSelectedRow(), 4)+"");
        fecha1.setText(modelo.getValueAt(tablachofe1.getSelectedRow(), 6)+"");
        usuario1.setText(modelo.getValueAt(tablachofe1.getSelectedRow(), 7)+"");
        
        String RegFed1 = rfc1.getText();
        String PaAc1 = paterno1.getText();
        String MaAc1 = materno1.getText();
        String NoAc1 = nombre1.getText();
        
        Chofe com=new Chofe();
        Object[] datos=com.Comple(RegFed1, PaAc1, MaAc1, NoAc1);
        sexo1.setText(datos[0]+"");
        fecnac1.setText(datos[1]+"");
        maxim1.setText(datos[2]+"");
        civil1.setText(datos[3]+"");
        pais1.setText(datos[4]+"");
        estado1.setText(datos[5]+"");
        mundel1.setText(datos[6]+"");
        pobla1.setText(datos[7]+"");
        colonia1.setText(datos[8]+"");
        calle1.setText(datos[9]+"");
        numext1.setText(datos[10]+"");
        numint1.setText(datos[11]+"");
        codpos1.setText(datos[12]+"");
        teldom1.setText(datos[13]+"");
        telcel1.setText(datos[14]+"");
        correo1.setText(datos[15]+"");
    }//GEN-LAST:event_tablachofe1MouseClicked

    private void busrfcKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_busrfcKeyPressed
        Chofe e=new Chofe();
        Limpiar(tablachofe1);
        DefaultTableModel modelo= (DefaultTableModel) tablachofe1.getModel();
        e.BusRfc(modelo, busrfc.getText().toUpperCase());
    }//GEN-LAST:event_busrfcKeyPressed

    private void busrfcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_busrfcMouseClicked
        Iniciar();
    }//GEN-LAST:event_busrfcMouseClicked

    private void buspatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buspatKeyPressed
        Chofe e=new Chofe();
        Limpiar(tablachofe1);
        DefaultTableModel modelo= (DefaultTableModel) tablachofe1.getModel();
        e.BusPat(modelo, buspat.getText().toUpperCase());
    }//GEN-LAST:event_buspatKeyPressed

    private void buspatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buspatMouseClicked
        Iniciar();
    }//GEN-LAST:event_buspatMouseClicked

    private void busmatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_busmatKeyPressed
        Chofe e=new Chofe();
        Limpiar(tablachofe1);
        DefaultTableModel modelo= (DefaultTableModel) tablachofe1.getModel();
        e.BusMat(modelo, busmat.getText().toUpperCase());
    }//GEN-LAST:event_busmatKeyPressed

    private void busmatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_busmatMouseClicked
        Iniciar();
    }//GEN-LAST:event_busmatMouseClicked

    private void busnomKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_busnomKeyPressed
        Chofe e=new Chofe();
        Limpiar(tablachofe1);
        DefaultTableModel modelo= (DefaultTableModel) tablachofe1.getModel();
        e.BusNom(modelo, busnom.getText().toUpperCase());
    }//GEN-LAST:event_busnomKeyPressed

    private void busnomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_busnomMouseClicked
        Iniciar();
    }//GEN-LAST:event_busnomMouseClicked

    private void salir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salir1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_salir1ActionPerformed

    private void codpos1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codpos1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_codpos1KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChofeConsola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChofeConsola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChofeConsola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChofeConsola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChofeConsola().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizar;
    private javax.swing.JTextField busmat;
    private javax.swing.JTextField busnom;
    private javax.swing.JTextField buspat;
    private javax.swing.JTextField busrfc;
    private javax.swing.JTextField calle;
    private javax.swing.JTextField calle1;
    private javax.swing.JButton cancelar;
    private javax.swing.JComboBox civil;
    private javax.swing.JTextField civil1;
    private javax.swing.JTextField codpos;
    private javax.swing.JTextField codpos1;
    private javax.swing.JComboBox colonia;
    private javax.swing.JTextField colonia1;
    private javax.swing.JTextField correo;
    private javax.swing.JTextField correo1;
    private javax.swing.JButton crear;
    private javax.swing.JTextField curp;
    private javax.swing.JTextField curp1;
    private javax.swing.JButton eliminar;
    private javax.swing.JComboBox estado;
    private javax.swing.JTextField estado1;
    private javax.swing.JTextField fecha;
    private javax.swing.JTextField fecha1;
    private com.toedter.calendar.JDateChooser fecnac;
    private javax.swing.JTextField fecnac1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField materno;
    private javax.swing.JTextField materno1;
    private javax.swing.JTextField maxim;
    private javax.swing.JTextField maxim1;
    private javax.swing.JComboBox mundel;
    private javax.swing.JTextField mundel1;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField nombre1;
    private javax.swing.JTextField numext;
    private javax.swing.JTextField numext1;
    private javax.swing.JTextField numint;
    private javax.swing.JTextField numint1;
    private javax.swing.JComboBox pais;
    private javax.swing.JTextField pais1;
    private javax.swing.JTextField paterno;
    private javax.swing.JTextField paterno1;
    private javax.swing.JComboBox pobla;
    private javax.swing.JTextField pobla1;
    private javax.swing.JTextField rfc;
    private javax.swing.JTextField rfc1;
    private javax.swing.JButton salir;
    private javax.swing.JButton salir1;
    private javax.swing.JComboBox sexo;
    private javax.swing.JTextField sexo1;
    private javax.swing.JTable tablachofe;
    private javax.swing.JTable tablachofe1;
    private javax.swing.JTextField telcel;
    private javax.swing.JTextField telcel1;
    private javax.swing.JTextField teldom;
    private javax.swing.JTextField teldom1;
    private javax.swing.JTextField txtEmpresa;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField usuario;
    private javax.swing.JTextField usuario1;
    // End of variables declaration//GEN-END:variables
}
