
package sirh;

import java.awt.Image;
import java.text.*;
import java.util.*;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

public class ContrConsola extends javax.swing.JFrame {


    public ContrConsola() {
        initComponents();
        setResizable(false);
        setDefaultCloseOperation(0);
        Iniciar();
    }
    
    private void Limpiar(JTable tabla){
        while(tabla.getRowCount()>0){
            ((DefaultTableModel) tabla.getModel()).removeRow(0);
        }
    }

    private void Iniciar(){
        Limpiar(tablacontr);
        numtra.setText("0");
        nomtra.setText("");
        rfctra.setText("");
        statra.setText("");
        fsttra.setText("");
        pattra.setText("");
        String lugarImagen="";
        lugarImagen=pattra.getText();
        Image icon=new ImageIcon(lugarImagen).getImage().getScaledInstance(txtImagen.getWidth(), txtImagen.getWidth(), Image.SCALE_DEFAULT);
        Icon imagen=new ImageIcon(icon);
        txtImagen.setIcon(imagen);
        numcon.setText("");
        stacon.removeAllItems();
        stacon.addItem("");
        Contr e1=new Contr();
        e1.LlenarStacon(stacon);
        fecsta.setDate(null);
        cveemp.removeAllItems();
        cveemp.addItem("");
        Contr e2=new Contr();
        e2.LlenarEmpresa(cveemp);
        nomemp.setText("");
        cvedep.removeAllItems();
        cvedep.addItem("");
        Contr e3=new Contr();
        e3.LlenarDepartamento(cvedep);
        nomdep.setText("");
        cvesec.setText("");
        nomsec.setText("");
        cvecat.removeAllItems();
        cvecat.addItem("");
        Contr e4=new Contr();
        e4.LlenarCategoria(cvecat);
        nomcat.setText("");
        suecat.setText("");
        cvetur.removeAllItems();
        cvetur.addItem("");
        Contr e5=new Contr();
        e5.LlenarTurno(cvetur);
        nomtur.setText("");
        cvetip.removeAllItems();
        cvetip.addItem("");
        Contr e6=new Contr();
        e6.LlenarTipo(cvetip);
        nomtip.setText("");
        finicio.setDate(null);
        ftermino.setDate(null);
        cvesup.removeAllItems();
        cvesup.addItem("");
        Contr e7=new Contr();
        e7.LlenarSuper(cvesup);
        nomsup.setText("");
        path.setText("C:/SIRH/CONTRATOS/CONTRATOS.GIF");
        observa.setText("");
        crear.setEnabled(true);
        numcon.setEnabled(true);
        numtra.setEnabled(true);
        numtra.grabFocus();
       
        fecha.setText(fechaActual());
        usuario.setText(Acceso.getClaveUsuario());
        txtNombre.setText(Acceso.getNombreUsuario());
        txtEmpresa.setText(Acceso.getEmpresaUsuario());
    }
    
    public static String fechaActual(){
        Date fecha= new Date();
        SimpleDateFormat formatoFecha=new SimpleDateFormat("dd/MM/YYYY HH:mm:ss");
        return formatoFecha.format(fecha);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel27 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtEmpresa = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        apriv = new javax.swing.JButton();
        preypre = new javax.swing.JButton();
        sanci = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nomtra = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        rfctra = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        statra = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        fsttra = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        pattra = new javax.swing.JTextField();
        numtra = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablacontr = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        crear = new javax.swing.JButton();
        actualizar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        txtImagen = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        numcon = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        stacon = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        fecsta = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        cveemp = new javax.swing.JComboBox();
        nomemp = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cvedep = new javax.swing.JComboBox();
        nomdep = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        nomsec = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        cvecat = new javax.swing.JComboBox();
        nomcat = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        cvetur = new javax.swing.JComboBox();
        nomtur = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        cvetip = new javax.swing.JComboBox();
        nomtip = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        suecat = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        finicio = new com.toedter.calendar.JDateChooser();
        ftermino = new com.toedter.calendar.JDateChooser();
        cvesup = new javax.swing.JComboBox();
        nomsup = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        path = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        observa = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        status = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        fecha = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();
        cvesec = new javax.swing.JTextField();

        jLabel27.setText("jLabel27");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SNTIAISCRM Sistema de Recursos Humanos");
        setMaximumSize(new java.awt.Dimension(1100, 650));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("CONTRATOS DE TRABAJADORES");

        txtEmpresa.setEditable(false);
        txtEmpresa.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        txtEmpresa.setForeground(new java.awt.Color(204, 0, 0));
        txtEmpresa.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtEmpresa.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtNombre.setEditable(false);
        txtNombre.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(204, 0, 0));
        txtNombre.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtNombre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        apriv.setForeground(new java.awt.Color(0, 0, 153));
        apriv.setText("Ausencias, Permisos, Retardos, Incapacidades y Vacaciones");
        apriv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aprivActionPerformed(evt);
            }
        });

        preypre.setForeground(new java.awt.Color(0, 0, 153));
        preypre.setText("Premios y Prestaciones");
        preypre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preypreActionPerformed(evt);
            }
        });

        sanci.setForeground(new java.awt.Color(0, 0, 153));
        sanci.setText("Sanciones");
        sanci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sanciActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(241, 241, 241)
                .addComponent(apriv)
                .addGap(18, 18, 18)
                .addComponent(preypre)
                .addGap(18, 18, 18)
                .addComponent(sanci)
                .addContainerGap(256, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apriv)
                    .addComponent(preypre)
                    .addComponent(sanci))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jLabel2.setForeground(new java.awt.Color(204, 0, 51));
        jLabel2.setText("Num. Trabajador:");

        jLabel3.setText("Nombre:");

        nomtra.setEditable(false);

        jLabel4.setText("RFC:");

        rfctra.setEditable(false);

        jLabel5.setText("Status Trabajador:");

        statra.setEditable(false);

        jLabel6.setText("Fecha Status:");

        fsttra.setEditable(false);

        jLabel7.setText("Path Foto:");

        pattra.setEditable(false);

        numtra.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                numtraFocusLost(evt);
            }
        });
        numtra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numtraActionPerformed(evt);
            }
        });
        numtra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numtraKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomtra, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                    .addComponent(rfctra)
                    .addComponent(numtra))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pattra, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fsttra, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(27, 27, 27)
                        .addComponent(statra, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(statra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numtra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nomtra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(fsttra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(rfctra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(pattra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        tablacontr.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Num. Contr.", "Status Contr.", "Empresa", "Departamento", "Sección", "Categoria", "Turno", "Tipo Contr.", "Inicio", "Término"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablacontr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablacontrMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablacontr);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        crear.setText("Crear");
        crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearActionPerformed(evt);
            }
        });

        actualizar.setText("Actualizar");
        actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarActionPerformed(evt);
            }
        });

        eliminar.setText("Eliminar");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(actualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(crear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(salir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(crear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(actualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(salir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        txtImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtImagen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(txtImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jLabel9.setForeground(new java.awt.Color(204, 0, 51));
        jLabel9.setText("Número Contrato:");

        jLabel10.setForeground(new java.awt.Color(204, 0, 51));
        jLabel10.setText("Status Contrato:");

        jLabel11.setForeground(new java.awt.Color(204, 0, 51));
        jLabel11.setText("Fecha Status:");

        jLabel12.setText("Empresa:");

        cveemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cveempActionPerformed(evt);
            }
        });

        nomemp.setEditable(false);

        jLabel13.setText("Departamento:");

        cvedep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cvedepActionPerformed(evt);
            }
        });

        nomdep.setEditable(false);

        jLabel14.setText("Sección:");

        nomsec.setEditable(false);

        jLabel15.setText("Categoría:");

        cvecat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cvecatActionPerformed(evt);
            }
        });

        nomcat.setEditable(false);

        jLabel16.setForeground(new java.awt.Color(204, 0, 51));
        jLabel16.setText("Fecha Inicio:         ");

        cvetur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cveturActionPerformed(evt);
            }
        });

        nomtur.setEditable(false);

        jLabel17.setText("Tipo Contrato:");

        cvetip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cvetipActionPerformed(evt);
            }
        });

        nomtip.setEditable(false);

        jLabel18.setText("Sueldo Diario:");

        suecat.setEditable(false);

        jLabel19.setText("Turno:");

        jLabel20.setForeground(new java.awt.Color(204, 0, 51));
        jLabel20.setText("Fecha Término:    ");

        jLabel21.setText("Supervisor Cargo:");

        cvesup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cvesupActionPerformed(evt);
            }
        });

        nomsup.setEditable(false);

        jLabel22.setText("Path Contrato:");

        path.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pathMouseClicked(evt);
            }
        });

        jLabel23.setText("Observa:");

        jLabel24.setText("Status:");

        status.setEditable(false);

        jLabel25.setText("Fecha:");

        fecha.setEditable(false);

        jLabel26.setText("Usuario:");

        usuario.setEditable(false);

        cvesec.setEditable(false);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(cveemp, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomemp, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                    .addComponent(numcon)
                    .addComponent(stacon, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fecsta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(cvedep, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomdep))
                    .addComponent(suecat)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cvesec)
                            .addComponent(cvecat, 0, 89, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomcat)
                            .addComponent(nomsec))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cvetur, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cvetip, 0, 93, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nomtur)
                                    .addComponent(nomtip)))
                            .addComponent(finicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ftermino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fecha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(cvesup, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nomsup))
                            .addComponent(path)
                            .addComponent(observa))))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(numcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cvetur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nomtur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(stacon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel17)
                                        .addComponent(cvetip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(nomtip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(fecsta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(finicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cveemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nomemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel20))
                    .addComponent(ftermino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(cvedep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomdep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(cvesup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomsup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(nomsec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(path, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cvesec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(cvecat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomcat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(observa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(suecat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                            .addComponent(txtEmpresa, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearActionPerformed
        try{
            Contr e=new Contr();
            int dnumtra=0;
            dnumtra=Integer.parseInt(numtra.getText().toUpperCase());
            if(dnumtra == 0){
                JOptionPane.showMessageDialog(this, "Se requiere un número de trabajador, verifique .....");
                Iniciar();
            }
            else{
                String dstacon=stacon.getSelectedItem().toString();
                if(dstacon.isEmpty()){
                    JOptionPane.showMessageDialog(this, "Se requiere un status del contrato, verifique .....");
                    stacon.grabFocus();
                }
                else{
                    if(fecsta.getDate() == null){
                        JOptionPane.showMessageDialog(this, "Se requieren la fecha del status del contrato, verifique .....");
                        fecsta.grabFocus();
                    }
                    else{
                        if(finicio.getDate() == null){
                            JOptionPane.showMessageDialog(this, "Se requieren la fecha de inicio del contrato, verifique .....");
                            finicio.grabFocus();
                        }
                        else{
                            if(ftermino.getDate() == null){
                                JOptionPane.showMessageDialog(this, "Se requieren la fecha de término del contrato, verifique .....");
                                ftermino.grabFocus();
                            }
                            else{
                                String dnumcon=numcon.getText().toUpperCase();
                                if(dnumcon.isEmpty()){
                                    JOptionPane.showMessageDialog(this, "Se requiere un número de contrato (1), verifique .....");
                                    numcon.grabFocus();
                                }
                                else{
                                    if(dnumcon.trim().equals("")){
                                        JOptionPane.showMessageDialog(this, "Se requiere un número de contrato (2), verifique .....");
                                        numcon.setText("");
                                        numcon.grabFocus();
                                    }
                                    else{
                                        String dnomtra=nomtra.getText().toUpperCase();
                                        String drfctra=rfctra.getText().toUpperCase();
                                        String dstatra=statra.getText().toUpperCase();
                                        String dfsttra=fsttra.getText().toUpperCase();
                                        String dpattra=pattra.getText().toUpperCase();
                                        int años=fecsta.getCalendar().get(Calendar.YEAR);
                                        int mess=fecsta.getCalendar().get(Calendar.MONTH)+1;
                                        int dias=fecsta.getCalendar().get(Calendar.DAY_OF_MONTH);
                                        String dfecsta=(años+"/"+mess+"/"+dias);
                                        String dcveemp=cveemp.getSelectedItem().toString();
                                        String dnomemp=nomemp.getText().toUpperCase();
                                        String dcvedep=cvedep.getSelectedItem().toString();
                                        String dnomdep=nomdep.getText().toUpperCase();
                                        String dcvesec=cvesec.getText().toUpperCase();
                                        String dnomsec=nomsec.getText().toUpperCase();
                                        String dcvecat=cvecat.getSelectedItem().toString();
                                        String dnomcat=nomcat.getText().toUpperCase();
                                        Float dsuecat=Float.parseFloat(suecat.getText().toUpperCase());
                                        String dcvetur=cvetur.getSelectedItem().toString();
                                        String dnomtur=nomtur.getText().toUpperCase();
                                        String dcvetip=cvetip.getSelectedItem().toString();
                                        String dnomtip=nomtip.getText().toUpperCase();
                                        int añoi=finicio.getCalendar().get(Calendar.YEAR);
                                        int mesi=finicio.getCalendar().get(Calendar.MONTH)+1;
                                        int diai=finicio.getCalendar().get(Calendar.DAY_OF_MONTH);
                                        String dfinicio=(añoi+"/"+mesi+"/"+diai);
                                        int añot=ftermino.getCalendar().get(Calendar.YEAR);
                                        int mest=ftermino.getCalendar().get(Calendar.MONTH)+1;
                                        int diat=ftermino.getCalendar().get(Calendar.DAY_OF_MONTH);
                                        String dftermino=(añot+"/"+mest+"/"+diat);
                                        String dcvesup=cvesup.getSelectedItem().toString();
                                        String dnomsup=nomsup.getText().toUpperCase();
                                        String dpath=path.getText().toUpperCase();
                                        String dobserva=observa.getText().toUpperCase();
                                        e.Agregar(dnumtra, dnomtra, drfctra, dstatra, dfsttra, dpattra, dstacon, dfecsta, dnumcon, dcveemp,
                                                  dnomemp, dcvedep, dnomdep, dcvesec, dnomsec, dcvecat, dnomcat, dsuecat, dcvetur, dnomtur,
                                                  dcvetip, dnomtip, dfinicio, dftermino, dcvesup, dnomsup, dpath, dobserva, Acceso.getClaveUsuario());
                                        JOptionPane.showMessageDialog(this, "Registro creado .....");
                                        Iniciar();
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
        catch(NumberFormatException nfe){
            System.out.println("No hay número: "+nfe);
        }
    }//GEN-LAST:event_crearActionPerformed

    private void actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarActionPerformed
        Contr e=new Contr();
        int dnumtra=0;
        dnumtra=Integer.parseInt(numtra.getText().toUpperCase());
        if(dnumtra == 0){
            JOptionPane.showMessageDialog(this, "Se requiere un número de trabajador, verifique .....");
            Iniciar();
        }
        else{
            String dstacon=stacon.getSelectedItem().toString();
            if(dstacon.isEmpty()){
                JOptionPane.showMessageDialog(this, "Se requiere un status del contrato, verifique .....");
                stacon.grabFocus();
            }
            else{
                if(fecsta.getDate() == null){
                    JOptionPane.showMessageDialog(this, "Se requieren la fecha del status del contrato, verifique .....");
                    fecsta.grabFocus();
                }
                else{
                    if(finicio.getDate() == null){
                        JOptionPane.showMessageDialog(this, "Se requieren la fecha de inicio del contrato, verifique .....");
                        finicio.grabFocus();
                    }
                    else{
                        if(ftermino.getDate() == null){
                            JOptionPane.showMessageDialog(this, "Se requieren la fecha de término del contrato, verifique .....");
                            ftermino.grabFocus();
                        }
                        else{
                            String dnumcon=numcon.getText().toUpperCase();
                            if(dnumcon.isEmpty()){
                                JOptionPane.showMessageDialog(this, "Se requiere un número de contrato (1), verifique .....");
                                numcon.grabFocus();
                            }
                            else{
                                if(dnumcon.trim().equals("")){
                                    JOptionPane.showMessageDialog(this, "Se requiere un número de contrato (2), verifique .....");
                                    numcon.setText("");
                                    numcon.grabFocus();
                                }
                                else{
                                    String dnomtra=nomtra.getText().toUpperCase();
                                    String drfctra=rfctra.getText().toUpperCase();
                                    String dstatra=statra.getText().toUpperCase();
                                    String dfsttra=fsttra.getText().toUpperCase();
                                    String dpattra=pattra.getText().toUpperCase();
                                    int años=fecsta.getCalendar().get(Calendar.YEAR);
                                    int mess=fecsta.getCalendar().get(Calendar.MONTH)+1;
                                    int dias=fecsta.getCalendar().get(Calendar.DAY_OF_MONTH);
                                    String dfecsta=(años+"/"+mess+"/"+dias);
                                    String dcveemp=cveemp.getSelectedItem().toString();
                                    String dnomemp=nomemp.getText().toUpperCase();
                                    String dcvedep=cvedep.getSelectedItem().toString();
                                    String dnomdep=nomdep.getText().toUpperCase();
                                    String dcvesec=cvesec.getText().toUpperCase();
                                    String dnomsec=nomsec.getText().toUpperCase();
                                    String dcvecat=cvecat.getSelectedItem().toString();
                                    String dnomcat=nomcat.getText().toUpperCase();
                                    Float dsuecat=Float.parseFloat(suecat.getText().toUpperCase());
                                    String dcvetur=cvetur.getSelectedItem().toString();
                                    String dnomtur=nomtur.getText().toUpperCase();
                                    String dcvetip=cvetip.getSelectedItem().toString();
                                    String dnomtip=nomtip.getText().toUpperCase();
                                    int añoi=finicio.getCalendar().get(Calendar.YEAR);
                                    int mesi=finicio.getCalendar().get(Calendar.MONTH)+1;
                                    int diai=finicio.getCalendar().get(Calendar.DAY_OF_MONTH);
                                    String dfinicio=(añoi+"/"+mesi+"/"+diai);
                                    int añot=ftermino.getCalendar().get(Calendar.YEAR);
                                    int mest=ftermino.getCalendar().get(Calendar.MONTH)+1;
                                    int diat=ftermino.getCalendar().get(Calendar.DAY_OF_MONTH);
                                    String dftermino=(añot+"/"+mest+"/"+diat);
                                    String dcvesup=cvesup.getSelectedItem().toString();
                                    String dnomsup=nomsup.getText().toUpperCase();
                                    String dpath=path.getText().toUpperCase();
                                    String dobserva=observa.getText().toUpperCase();
                                    e.Actualizar(dnumtra, dnomtra, drfctra, dstatra, dfsttra, dpattra, dstacon, dfecsta, dnumcon, dcveemp,
                                                 dnomemp, dcvedep, dnomdep, dcvesec, dnomsec, dcvecat, dnomcat, dsuecat, dcvetur, dnomtur,
                                                 dcvetip, dnomtip, dfinicio, dftermino, dcvesup, dnomsup, dpath, dobserva, Acceso.getClaveUsuario());
                                    JOptionPane.showMessageDialog(this, "Registro actualizado .....");
                                    Iniciar();
                                }
                            }
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_actualizarActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        Contr e=new Contr();
        int dnumtra=Integer.parseInt(numtra.getText().toUpperCase());
        String dnumcon=numcon.getText().toUpperCase();
        e.Eliminar(dnumtra, dnumcon, Acceso.getClaveUsuario());
        JOptionPane.showMessageDialog(this, "Registro eliminado .....");
        Iniciar();
    }//GEN-LAST:event_eliminarActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        Iniciar();
    }//GEN-LAST:event_cancelarActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        this.dispose();
    }//GEN-LAST:event_salirActionPerformed

    private void aprivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aprivActionPerformed
        String dnumtra=numtra.getText().toUpperCase();
        String dnumcon=numcon.getText().toUpperCase();
        if(dnumtra.isEmpty() || dnumcon.isEmpty()){
            JOptionPane.showMessageDialog(this, "Falta un número de trabajador y/o un número de contrato, verifique .....");
            Iniciar();
        }
        else{
            Cargar();
            AprivConsola object=new AprivConsola();
            object.setLocationRelativeTo(null);
            object.setVisible(true);
        }
    }//GEN-LAST:event_aprivActionPerformed

    private void preypreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preypreActionPerformed
        String dnumtra=numtra.getText().toUpperCase();
        String dnumcon=numcon.getText().toUpperCase();
        if(dnumtra.isEmpty() || dnumcon.isEmpty()){
            JOptionPane.showMessageDialog(this, "Falta un número de trabajador y/o un número de contrato, verifique .....");
            Iniciar();
        }
        else{
            Cargar();
            PryprConsola object=new PryprConsola();
            object.setLocationRelativeTo(null);
            object.setVisible(true);
        }
    }//GEN-LAST:event_preypreActionPerformed

    private void sanciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sanciActionPerformed
        String dnumtra=numtra.getText().toUpperCase();
        String dnumcon=numcon.getText().toUpperCase();
        if(dnumtra.isEmpty() || dnumcon.isEmpty()){
            JOptionPane.showMessageDialog(this, "Falta un número de trabajador y/o un número de contrato, verifique .....");
            Iniciar();
        }
        else{
            Cargar();
            SanciConsola object=new SanciConsola();
            object.setLocationRelativeTo(null);
            object.setVisible(true);
        }
    }//GEN-LAST:event_sanciActionPerformed

    private void Cargar(){
        Contr.setNomTrabaja(nomtra.getText().toUpperCase());
        Contr.setRfcTrabaja(rfctra.getText().toUpperCase());
        Contr.setPatTrabaja(pattra.getText().toUpperCase());
        Contr.setStcTrabaja(statra.getText().toUpperCase());
        Contr.setFesTrabaja(fsttra.getText().toUpperCase());
        Contr.setNcoTrabaja(numcon.getText().toUpperCase());
        Contr.setCemTrabaja(cveemp.getSelectedItem().toString());
        Contr.setNemTrabaja(nomemp.getText().toUpperCase());
        Contr.setCdeTrabaja(cvedep.getSelectedItem().toString());
        Contr.setNdeTrabaja(nomdep.getText().toUpperCase());
        Contr.setCseTrabaja(cvesec.getText().toUpperCase());
        Contr.setNseTrabaja(nomsec.getText().toUpperCase());
        Contr.setCcaTrabaja(cvecat.getSelectedItem().toString());
        Contr.setNcaTrabaja(nomcat.getText().toUpperCase());
        Contr.setSxdTrabaja(Float.parseFloat(suecat.getText().toUpperCase()));
        Contr.setCtuTrabaja(cvetur.getSelectedItem().toString());
        Contr.setNtuTrabaja(nomtur.getText().toUpperCase());
        Contr.setCtiTrabaja(cvetip.getSelectedItem().toString());
        Contr.setNtiTrabaja(nomtip.getText().toUpperCase());
        
        if(finicio.getDate() == null){
            Contr.setFinTrabaja(null);
        }
        else{
            int añoi=finicio.getCalendar().get(Calendar.YEAR);
            int mesi=finicio.getCalendar().get(Calendar.MONTH)+1;
            int diai=finicio.getCalendar().get(Calendar.DAY_OF_MONTH);
            Contr.setFinTrabaja(añoi+"/"+mesi+"/"+diai);
        }
        
        if(ftermino.getDate() == null){
            Contr.setFteTrabaja(null);
        }
        else{
            int añot=ftermino.getCalendar().get(Calendar.YEAR);
            int mest=ftermino.getCalendar().get(Calendar.MONTH)+1;
            int diat=ftermino.getCalendar().get(Calendar.DAY_OF_MONTH);
            Contr.setFteTrabaja(añot+"/"+mest+"/"+diat);
        }
    }
    
    private void tablacontrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablacontrMouseClicked
        DefaultTableModel modelo= (DefaultTableModel) tablacontr.getModel();
        numcon.setText(modelo.getValueAt(tablacontr.getSelectedRow(), 0)+"");
        stacon.setSelectedItem(modelo.getValueAt(tablacontr.getSelectedRow(), 1)+"");
        nomemp.setText(modelo.getValueAt(tablacontr.getSelectedRow(), 2)+"");
        nomdep.setText(modelo.getValueAt(tablacontr.getSelectedRow(), 3)+"");
        nomsec.setText(modelo.getValueAt(tablacontr.getSelectedRow(), 4)+"");
        nomcat.setText(modelo.getValueAt(tablacontr.getSelectedRow(), 5)+"");
        nomtur.setText(modelo.getValueAt(tablacontr.getSelectedRow(), 6)+"");
        nomtip.setText(modelo.getValueAt(tablacontr.getSelectedRow(), 7)+"");
        String fecini = (modelo.getValueAt(tablacontr.getSelectedRow(), 8)+"");
        if("null".equals(fecini)){
            System.out.println("La fecha de inicio esta vacia .....");
        }
        else{
            SimpleDateFormat formatofecha1=new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            try{
                Date fecha1 = formatofecha1.parse(fecini);
                finicio.setDate(fecha1);
            }
            catch(ParseException pe1){
            System.out.println("Error Parse1: "+pe1.getMessage());
            }
        }
        String fecter = (modelo.getValueAt(tablacontr.getSelectedRow(), 9)+"");
        if("null".equals(fecter)){
            System.out.println("La fecha de término esta vacia .....");
        }
        else{
            SimpleDateFormat formatofecha2=new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            try{
                Date fecha2 = formatofecha2.parse(fecter);
                ftermino.setDate(fecha2);
            }
            catch(ParseException pe2){
            System.out.println("Error Parse2: "+pe2.getMessage());
            }
        }
        
        Contr com2=new Contr();
        int dnumtra=Integer.parseInt(numtra.getText().toUpperCase());
        Object[] datos1=com2.Comple(dnumtra, numcon.getText());
        String fstat = datos1[0]+"";
        if("null".equals(fstat)){
            System.out.println("La fecha del status esta vacia .....");
        }
        else{
            SimpleDateFormat formatofecha3=new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            try{
                Date fecha3 = formatofecha3.parse(fstat);
                fecsta.setDate(fecha3);
            }
            catch(ParseException pe3){
                System.out.println("Error Parse3: "+pe3.getMessage());
            }
        }
        cveemp.setSelectedItem(datos1[1]+"");
        cvedep.setSelectedItem(datos1[2]+"");
        cvesec.setText(datos1[3]+"");
        cvecat.setSelectedItem(datos1[4]+"");
        suecat.setText(datos1[5]+"");
        cvetur.setSelectedItem(datos1[6]+"");
        cvetip.setSelectedItem(datos1[7]+"");
        cvesup.setSelectedItem(datos1[8]+"");
        nomsup.setText(datos1[9]+"");
        path.setText(datos1[10]+"");
        observa.setText(datos1[11]+"");
        status.setText(datos1[12]+"");
        fecha.setText(datos1[13]+"");
        usuario.setText(datos1[14]+"");
        crear.setEnabled(false);
        numcon.setEnabled(false);
    }//GEN-LAST:event_tablacontrMouseClicked

    private void cveempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cveempActionPerformed
        String claveseleccionada=cveemp.getSelectedItem()+"";
        Contr e=new Contr();
        Object[] datos2=e.Empresa(claveseleccionada);
        nomemp.setText(datos2[0]+"");
    }//GEN-LAST:event_cveempActionPerformed

    private void cvedepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cvedepActionPerformed
        String claveseleccionada=cvedep.getSelectedItem()+"";
        Contr e=new Contr();
        Object[] datos3=e.Depto(claveseleccionada);
        nomdep.setText(datos3[0]+"");
        cvesec.setText(datos3[1]+"");
        nomsec.setText(datos3[2]+"");
    }//GEN-LAST:event_cvedepActionPerformed

    private void cvecatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cvecatActionPerformed
        String claveseleccionada=cvecat.getSelectedItem()+"";
        Contr e=new Contr();
        Object[] datos4=e.Categ(claveseleccionada);
        nomcat.setText(datos4[0]+"");
        suecat.setText(datos4[1]+"");
    }//GEN-LAST:event_cvecatActionPerformed

    private void cveturActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cveturActionPerformed
        String claveseleccionada=cvetur.getSelectedItem()+"";
        Contr e=new Contr();
        Object[] datos5=e.Turno(claveseleccionada);
        nomtur.setText(datos5[0]+"");
    }//GEN-LAST:event_cveturActionPerformed

    private void cvetipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cvetipActionPerformed
        String claveseleccionada=cvetip.getSelectedItem()+"";
        Contr e=new Contr();
        Object[] datos6=e.Tipo(claveseleccionada);
        nomtip.setText(datos6[0]+"");
    }//GEN-LAST:event_cvetipActionPerformed

    private void cvesupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cvesupActionPerformed
        String claveseleccionada=cvesup.getSelectedItem()+"";
        Contr e=new Contr();
        Object[] datos7=e.Super(claveseleccionada);
        nomsup.setText(datos7[0]+"");
    }//GEN-LAST:event_cvesupActionPerformed

    private void numtraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numtraActionPerformed
        // NO SIRVE
    }//GEN-LAST:event_numtraActionPerformed

    private void numtraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numtraKeyTyped
        char car = evt.getKeyChar();
        if((car<'0' || car>'9')) evt.consume();
    }//GEN-LAST:event_numtraKeyTyped

    private void numtraFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_numtraFocusLost
        //String valnumtra=numtra.getText().toUpperCase();
        try{
            int dnumtra=0;
            dnumtra=Integer.parseInt(numtra.getText().toUpperCase());
            if(dnumtra == 0){
                JOptionPane.showMessageDialog(this, "Necesita proporcionar un número de trabajador válido, verifique .....");
                numtra.grabFocus();
            }
            else{
                Contr val= new Contr();
                Object[] datos=val.Datos(dnumtra);
                String checa=datos[0]+"";
                Contr.setNumTrabaja(dnumtra);
            
                if(checa.trim().equals("null")){
                    JOptionPane.showMessageDialog(this, "Este número de trabajador no existe .....");
                    Iniciar();
                }
                else{
                    numtra.setText(datos[0]+"");
                    nomtra.setText(datos[1]+"");
                    rfctra.setText(datos[2]+"");
                    statra.setText(datos[3]+"");
                    fsttra.setText(datos[4]+"");
                    pattra.setText(datos[5]+"");
                    String lugarImagen="";
                    lugarImagen=pattra.getText();
                    Image icon=new ImageIcon(lugarImagen).getImage().getScaledInstance(txtImagen.getWidth(), txtImagen.getWidth(), Image.SCALE_DEFAULT);
                    Icon imagen=new ImageIcon(icon);
                    txtImagen.setIcon(imagen);
                
                    DefaultTableModel modelo=(DefaultTableModel) tablacontr.getModel();
                    Contr e=new Contr();
                    e.LlenarDatos(modelo, dnumtra);
                    //numcon.grabFocus();
                    numtra.setEnabled(false);
                }
            }
        }
        catch(NumberFormatException nfe){
            System.out.println("No hay número: "+nfe);
        }
    }//GEN-LAST:event_numtraFocusLost

    private void pathMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pathMouseClicked
        Contr.setPathUsuario(path.getText().toUpperCase());
        VContrConsola object=new VContrConsola();
        object.setVisible(true);
    }//GEN-LAST:event_pathMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContrConsola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContrConsola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContrConsola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContrConsola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ContrConsola().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizar;
    private javax.swing.JButton apriv;
    private javax.swing.JButton cancelar;
    private javax.swing.JButton crear;
    private javax.swing.JComboBox cvecat;
    private javax.swing.JComboBox cvedep;
    private javax.swing.JComboBox cveemp;
    private javax.swing.JTextField cvesec;
    private javax.swing.JComboBox cvesup;
    private javax.swing.JComboBox cvetip;
    private javax.swing.JComboBox cvetur;
    private javax.swing.JButton eliminar;
    private javax.swing.JTextField fecha;
    private com.toedter.calendar.JDateChooser fecsta;
    private com.toedter.calendar.JDateChooser finicio;
    private javax.swing.JTextField fsttra;
    private com.toedter.calendar.JDateChooser ftermino;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nomcat;
    private javax.swing.JTextField nomdep;
    private javax.swing.JTextField nomemp;
    private javax.swing.JTextField nomsec;
    private javax.swing.JTextField nomsup;
    private javax.swing.JTextField nomtip;
    private javax.swing.JTextField nomtra;
    private javax.swing.JTextField nomtur;
    private javax.swing.JTextField numcon;
    private javax.swing.JTextField numtra;
    private javax.swing.JTextField observa;
    private javax.swing.JTextField path;
    private javax.swing.JTextField pattra;
    private javax.swing.JButton preypre;
    private javax.swing.JTextField rfctra;
    private javax.swing.JButton salir;
    private javax.swing.JButton sanci;
    private javax.swing.JComboBox stacon;
    private javax.swing.JTextField statra;
    private javax.swing.JTextField status;
    private javax.swing.JTextField suecat;
    private javax.swing.JTable tablacontr;
    private javax.swing.JTextField txtEmpresa;
    private javax.swing.JLabel txtImagen;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
