
package sirh;

import java.awt.Image;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

public class cTrabaConsola extends javax.swing.JFrame {


    public cTrabaConsola() throws MalformedURLException {
        initComponents();
        //setDefaultCloseOperation(0);
        Iniciar();
    }

    private void Limpiar(JTable tabla){
        while(tabla.getRowCount()>0){
            ((DefaultTableModel) tabla.getModel()).removeRow(0);
        }
    }
    
    private void Iniciar() throws MalformedURLException{
        try {
        Limpiar(tablatraba);
        busnum.setText("");
        buspat.setText("");
        busmat.setText("");
        busnom.setText("");
        numtra.setText("");
        rfc.setText("");
        curp.setText("");
        statra.setText("");
        fstatra.setText("");
        paterno.setText("");
        materno.setText("");
        nombre.setText("");
        path.setText("");
        String lugarImagen="FTP://SIRH.DYNDNS.ORG/TRABAJADORES/SINFOTO.GIF";
        lugarImagen=path.getText();
        Image icon=new javax.swing.ImageIcon(new URL(lugarImagen)).getImage().getScaledInstance(txtImagen.getWidth(), txtImagen.getWidth(), Image.SCALE_DEFAULT);
        Icon imagen=new ImageIcon(icon);
        txtImagen.setIcon(imagen);
        fnacim.setText("");
        sexo.setText("");
        nacion.setText("");
        fing.setText("");
        fpla.setText("");
        fcam.setText("");
        frei.setText("");
        observa.setText("");
        status.setText("");
        fecha.setText("");
        usuario.setText("");
        txtNombre.setText(Acceso.getNombreUsuario());
        txtEmpresa.setText(Acceso.getEmpresaUsuario());
        }catch(Exception ex){
            System.out.println(ex.getMessage());
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        busnum = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        buspat = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        busmat = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        busnom = new javax.swing.JTextField();
        salir = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablatraba = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        numtra = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        rfc = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        curp = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        statra = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        fstatra = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        paterno = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        materno = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        path = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        fnacim = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        sexo = new javax.swing.JTextField();
        nacion = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        fing = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        fpla = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        fcam = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        frei = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        observa = new javax.swing.JTextField();
        usuario = new javax.swing.JTextField();
        fecha = new javax.swing.JTextField();
        status = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txtImagen = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        datper = new javax.swing.JButton();
        documenta = new javax.swing.JButton();
        escolar = new javax.swing.JButton();
        famil = new javax.swing.JButton();
        exper = new javax.swing.JButton();
        benefi = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtEmpresa = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SNTIAISCRM Sistema de Recursos Humanos");
        setMaximumSize(new java.awt.Dimension(1000, 650));
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jLabel2.setText("Número Trabajador:");

        busnum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                busnumMouseClicked(evt);
            }
        });
        busnum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                busnumKeyPressed(evt);
            }
        });

        jLabel3.setText("Paterno:");

        buspat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buspatMouseClicked(evt);
            }
        });
        buspat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                buspatKeyPressed(evt);
            }
        });

        jLabel4.setText("Materno:");

        busmat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                busmatMouseClicked(evt);
            }
        });
        busmat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                busmatKeyPressed(evt);
            }
        });

        jLabel5.setText("Nombre:");

        busnom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                busnomMouseClicked(evt);
            }
        });
        busnom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                busnomKeyPressed(evt);
            }
        });

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(busnum, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buspat, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(busmat, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(busnom, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(busnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(buspat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(busmat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(busnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salir))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        tablatraba.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Número", "Paterno", "Materno", "Nombre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablatraba.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablatrabaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablatraba);

        jLabel6.setText("Número:");

        numtra.setEditable(false);

        jLabel7.setText("RFC:");

        rfc.setEditable(false);

        jLabel8.setText("CURP:");

        curp.setEditable(false);

        jLabel9.setText("Status Trab:");

        statra.setEditable(false);

        jLabel10.setText("Fecha Stat:");

        fstatra.setEditable(false);

        jLabel11.setText("Paterno:");

        paterno.setEditable(false);

        jLabel12.setText("Materno:");

        materno.setEditable(false);

        jLabel13.setText("Nombre:");

        nombre.setEditable(false);

        jLabel14.setText("Path Foto:");

        path.setEditable(false);

        jLabel15.setText("Fec Nac:");

        fnacim.setEditable(false);

        jLabel16.setText("Género:");

        jLabel17.setText("Nacionalidad:");

        sexo.setEditable(false);

        nacion.setEditable(false);

        jLabel18.setText("F. Ingreso:");

        fing.setEditable(false);

        jLabel19.setText("F. Planta:");

        fpla.setEditable(false);

        jLabel20.setText("F. Cambio:");

        fcam.setEditable(false);

        jLabel21.setText("R. Reingreso:");

        frei.setEditable(false);

        jLabel22.setText("Observa:");

        observa.setEditable(false);

        usuario.setEditable(false);

        fecha.setEditable(false);

        status.setEditable(false);

        jLabel23.setText("Status:");

        jLabel24.setText("Fecha:");

        jLabel25.setText("Usuario:");

        txtImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtImagen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel8))
                                    .addGap(35, 35, 35))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addGap(16, 16, 16)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15))
                                .addGap(20, 20, 20)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(statra)
                            .addComponent(numtra, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rfc, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(curp)
                            .addComponent(fstatra)
                            .addComponent(paterno)
                            .addComponent(materno)
                            .addComponent(nombre)
                            .addComponent(path)
                            .addComponent(fnacim, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25)
                            .addComponent(jLabel16))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(status)
                            .addComponent(fecha)
                            .addComponent(usuario, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                            .addComponent(frei)
                            .addComponent(nacion)
                            .addComponent(fing)
                            .addComponent(fpla)
                            .addComponent(fcam)
                            .addComponent(observa)
                            .addComponent(sexo))
                        .addGap(35, 35, 35)
                        .addComponent(txtImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(numtra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(rfc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)
                            .addComponent(nacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(curp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18)
                            .addComponent(fing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(statra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19)
                            .addComponent(fpla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(fstatra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20)
                            .addComponent(fcam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(paterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21)
                            .addComponent(frei, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(materno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel22)
                        .addComponent(observa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(path, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(fnacim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addGap(88, 88, 88))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        datper.setForeground(new java.awt.Color(0, 0, 153));
        datper.setText("Datos Personales");
        datper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datperActionPerformed(evt);
            }
        });

        documenta.setForeground(new java.awt.Color(0, 0, 153));
        documenta.setText("Documentación");
        documenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                documentaActionPerformed(evt);
            }
        });

        escolar.setForeground(new java.awt.Color(0, 0, 153));
        escolar.setText("Escolaridad");
        escolar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                escolarActionPerformed(evt);
            }
        });

        famil.setForeground(new java.awt.Color(0, 0, 153));
        famil.setText("Familiares");
        famil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                familActionPerformed(evt);
            }
        });

        exper.setForeground(new java.awt.Color(0, 0, 153));
        exper.setText("Experiencia");
        exper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                experActionPerformed(evt);
            }
        });

        benefi.setForeground(new java.awt.Color(0, 0, 153));
        benefi.setText("Beneficiarios");
        benefi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                benefiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(datper)
                .addGap(18, 18, 18)
                .addComponent(documenta)
                .addGap(18, 18, 18)
                .addComponent(escolar)
                .addGap(18, 18, 18)
                .addComponent(famil)
                .addGap(18, 18, 18)
                .addComponent(exper)
                .addGap(18, 18, 18)
                .addComponent(benefi)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(datper)
                    .addComponent(documenta)
                    .addComponent(escolar)
                    .addComponent(famil)
                    .addComponent(exper)
                    .addComponent(benefi))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("BUSQUEDA DE TRABAJADORES");

        txtEmpresa.setEditable(false);
        txtEmpresa.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        txtEmpresa.setForeground(new java.awt.Color(204, 0, 0));
        txtEmpresa.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtEmpresa.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtNombre.setEditable(false);
        txtNombre.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(204, 0, 0));
        txtNombre.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtNombre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 466, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        this.dispose();
    }//GEN-LAST:event_salirActionPerformed

    private void busnumKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_busnumKeyPressed
        cTraba e=new cTraba();
        Limpiar(tablatraba);
        DefaultTableModel modelo= (DefaultTableModel) tablatraba.getModel();
        e.BusNum(modelo, busnum.getText().toUpperCase());
    }//GEN-LAST:event_busnumKeyPressed

    private void busnumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_busnumMouseClicked
        try {
            Iniciar();
        } catch (MalformedURLException ex) {
            Logger.getLogger(cTrabaConsola.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_busnumMouseClicked

    private void buspatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buspatKeyPressed
        cTraba e=new cTraba();
        Limpiar(tablatraba);
        DefaultTableModel modelo= (DefaultTableModel) tablatraba.getModel();
        e.BusPat(modelo, buspat.getText().toUpperCase());
    }//GEN-LAST:event_buspatKeyPressed

    private void buspatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buspatMouseClicked
        try {
            Iniciar();
        } catch (MalformedURLException ex) {
            Logger.getLogger(cTrabaConsola.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buspatMouseClicked

    private void busmatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_busmatKeyPressed
        cTraba e=new cTraba();
        Limpiar(tablatraba);
        DefaultTableModel modelo= (DefaultTableModel) tablatraba.getModel();
        e.BusMat(modelo, busmat.getText().toUpperCase());
    }//GEN-LAST:event_busmatKeyPressed

    private void busmatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_busmatMouseClicked
        try {
            Iniciar();
        } catch (MalformedURLException ex) {
            Logger.getLogger(cTrabaConsola.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_busmatMouseClicked

    private void busnomKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_busnomKeyPressed
        cTraba e=new cTraba();
        Limpiar(tablatraba);
        DefaultTableModel modelo= (DefaultTableModel) tablatraba.getModel();
        e.BusNom(modelo, busnom.getText().toUpperCase());
    }//GEN-LAST:event_busnomKeyPressed

    private void busnomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_busnomMouseClicked
        try {
            Iniciar();
        } catch (MalformedURLException ex) {
            Logger.getLogger(cTrabaConsola.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_busnomMouseClicked

    private void datperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datperActionPerformed
        try{
            int dnumtra=0;
            dnumtra=Integer.parseInt(numtra.getText().toUpperCase());
            System.out.println("Si hay número: "+dnumtra);
            if(dnumtra == 0){
                JOptionPane.showMessageDialog(this, "Necesita proporcionar un número de trabajador válido, verifique .....");
                Iniciar();
            }
            else{
                cDatosConsola object=new cDatosConsola();
                object.setLocationRelativeTo(null);
                object.setVisible(true);
                }   
        }
        catch(NumberFormatException nfe){
            System.out.println("No hay número: "+nfe);
        } catch (MalformedURLException ex) {
            Logger.getLogger(cTrabaConsola.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_datperActionPerformed

    private void documentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_documentaActionPerformed
        try{
            int dnumtra=0;
            dnumtra=Integer.parseInt(numtra.getText().toUpperCase());
            System.out.println("Si hay número: "+dnumtra);
            if(dnumtra == 0){
                JOptionPane.showMessageDialog(this, "Necesita proporcionar un número de trabajador válido, verifique .....");
                Iniciar();
            }
            else{
                cDocumConsola object=new cDocumConsola();
                object.setLocationRelativeTo(null);
                object.setVisible(true);
                }   
        }
        catch(NumberFormatException nfe){
            System.out.println("No hay número: "+nfe);
        } catch (MalformedURLException ex) {
            Logger.getLogger(cTrabaConsola.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_documentaActionPerformed

    private void escolarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_escolarActionPerformed
        try{
            int dnumtra=0;
            dnumtra=Integer.parseInt(numtra.getText().toUpperCase());
            System.out.println("Si hay número: "+dnumtra);
            if(dnumtra == 0){
                JOptionPane.showMessageDialog(this, "Necesita proporcionar un número de trabajador válido, verifique .....");
                Iniciar();
            }
            else{
                cEscolConsola object=new cEscolConsola();
                object.setLocationRelativeTo(null);
                object.setVisible(true);
                }   
        }
        catch(NumberFormatException nfe){
            System.out.println("No hay número: "+nfe);
        } catch (MalformedURLException ex) {
            Logger.getLogger(cTrabaConsola.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_escolarActionPerformed

    private void familActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_familActionPerformed
        try{
            int dnumtra=0;
            dnumtra=Integer.parseInt(numtra.getText().toUpperCase());
            System.out.println("Si hay número: "+dnumtra);
            if(dnumtra == 0){
                JOptionPane.showMessageDialog(this, "Necesita proporcionar un número de trabajador válido, verifique .....");
                Iniciar();
            }
            else{
                cFamilConsola object=new cFamilConsola();
                object.setLocationRelativeTo(null);
                object.setVisible(true);
                }   
        }
        catch(NumberFormatException nfe){
            System.out.println("No hay número: "+nfe);
        } catch (MalformedURLException ex) {
            Logger.getLogger(cTrabaConsola.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_familActionPerformed

    private void experActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_experActionPerformed
        try{
            int dnumtra=0;
            dnumtra=Integer.parseInt(numtra.getText().toUpperCase());
            System.out.println("Si hay número: "+dnumtra);
            if(dnumtra == 0){
                JOptionPane.showMessageDialog(this, "Necesita proporcionar un número de trabajador válido, verifique .....");
                Iniciar();
            }
            else{
                cExperConsola object=new cExperConsola();
                object.setLocationRelativeTo(null);
                object.setVisible(true);
                }   
        }
        catch(NumberFormatException nfe){
            System.out.println("No hay número: "+nfe);
        } catch (MalformedURLException ex) {
            Logger.getLogger(cTrabaConsola.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_experActionPerformed

    private void benefiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_benefiActionPerformed
        try{
            int dnumtra=0;
            dnumtra=Integer.parseInt(numtra.getText().toUpperCase());
            System.out.println("Si hay número: "+dnumtra);
            if(dnumtra == 0){
                JOptionPane.showMessageDialog(this, "Necesita proporcionar un número de trabajador válido, verifique .....");
                Iniciar();
            }
            else{
                cBenefConsola object=new cBenefConsola();
                object.setLocationRelativeTo(null);
                object.setVisible(true);
                }   
        }
        catch(NumberFormatException nfe){
            System.out.println("No hay número: "+nfe);
        } catch (MalformedURLException ex) {
            Logger.getLogger(cTrabaConsola.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_benefiActionPerformed

    private void tablatrabaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablatrabaMouseClicked
        try {
            DefaultTableModel modelo= (DefaultTableModel) tablatraba.getModel();
            numtra.setText(modelo.getValueAt(tablatraba.getSelectedRow(), 0)+"");
            paterno.setText(modelo.getValueAt(tablatraba.getSelectedRow(), 1)+"");
            materno.setText(modelo.getValueAt(tablatraba.getSelectedRow(), 2)+"");
            nombre.setText(modelo.getValueAt(tablatraba.getSelectedRow(), 3)+"");
            
            int NuTr=Integer.parseInt(numtra.getText().toUpperCase());
            String PaAc = paterno.getText();
            String MaAc = materno.getText();
            String NoAc = nombre.getText();
            
            cTraba com=new cTraba();
            Object[] datos1=com.Comple(NuTr, PaAc, MaAc, NoAc);
            //numtra.setText(datos1[0]+"");
            rfc.setText(datos1[1]+"");
            curp.setText(datos1[2]+"");
            statra.setText(datos1[3]+"");
            fstatra.setText(datos1[4]+"");
            //paterno.setText(datos1[5]+"");
            //materno.setText(datos1[6]+"");
            //nombre.setText(datos1[7]+"");
            path.setText(datos1[8]+"");
            fnacim.setText(datos1[9]+"");
            sexo.setText(datos1[10]+"");
            nacion.setText(datos1[11]+"");
            fing.setText(datos1[12]+"");
            fpla.setText(datos1[13]+"");
            fcam.setText(datos1[14]+"");
            frei.setText(datos1[15]+"");
            observa.setText(datos1[16]+"");
            status.setText(datos1[17]+"");
            fecha.setText(datos1[18]+"");
            usuario.setText(datos1[19]+"");
            
            String lugarImagen="";
            lugarImagen=path.getText();
            Image icon=new javax.swing.ImageIcon(new URL(lugarImagen)).getImage().getScaledInstance(txtImagen.getWidth(), txtImagen.getWidth(), Image.SCALE_DEFAULT);
            Icon imagen=new ImageIcon(icon);
            txtImagen.setIcon(imagen);
            
            cTraba.setNumTrabaja(NuTr);
            cTraba.setNomTrabaja(nombre.getText()+" "+paterno.getText()+" "+materno.getText());
        } catch (MalformedURLException ex) {
            Logger.getLogger(cTrabaConsola.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tablatrabaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cTrabaConsola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cTrabaConsola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cTrabaConsola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cTrabaConsola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new cTrabaConsola().setVisible(true);
                } catch (MalformedURLException ex) {
                    Logger.getLogger(cTrabaConsola.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton benefi;
    private javax.swing.JTextField busmat;
    private javax.swing.JTextField busnom;
    private javax.swing.JTextField busnum;
    private javax.swing.JTextField buspat;
    private javax.swing.JTextField curp;
    private javax.swing.JButton datper;
    private javax.swing.JButton documenta;
    private javax.swing.JButton escolar;
    private javax.swing.JButton exper;
    private javax.swing.JButton famil;
    private javax.swing.JTextField fcam;
    private javax.swing.JTextField fecha;
    private javax.swing.JTextField fing;
    private javax.swing.JTextField fnacim;
    private javax.swing.JTextField fpla;
    private javax.swing.JTextField frei;
    private javax.swing.JTextField fstatra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField materno;
    private javax.swing.JTextField nacion;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField numtra;
    private javax.swing.JTextField observa;
    private javax.swing.JTextField paterno;
    private javax.swing.JTextField path;
    private javax.swing.JTextField rfc;
    private javax.swing.JButton salir;
    private javax.swing.JTextField sexo;
    private javax.swing.JTextField statra;
    private javax.swing.JTextField status;
    private javax.swing.JTable tablatraba;
    private javax.swing.JTextField txtEmpresa;
    private javax.swing.JLabel txtImagen;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
