
package sirh;

import java.awt.Image;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

public class cTrabaAConsola extends javax.swing.JFrame {


    public cTrabaAConsola() throws MalformedURLException {
        initComponents();
        setDefaultCloseOperation(0);
        Iniciar();
    }
    
    private void Limpiar(JTable tabla){
        while(tabla.getRowCount()>0){
            ((DefaultTableModel) tabla.getModel()).removeRow(0);
        }
    }
    
    private void Iniciar() throws MalformedURLException{
        Limpiar(tablatraba);
        busrfc.setText("");
        buspat.setText("");
        busmat.setText("");
        busnom.setText("");
        rfc.setText("");
        curp.setText("");
        paterno.setText("");
        materno.setText("");
        nombre.setText("");
        path.setText("ftp://sirh.dyndns.org/Trabajadores/SINFOTO.GIF");
        String lugarImagen="ftp://sirh.dyndns.org/Trabajadores/SINFOTO.GIF";
        lugarImagen=path.getText();
        //Image icon=new ImageIcon(lugarImagen).getImage().getScaledInstance(txtImagen.getWidth(), txtImagen.getWidth(), Image.SCALE_DEFAULT);
        //Icon imagen=new ImageIcon(icon);
        //txtImagen.setIcon(imagen);
        
        Image icon= new javax.swing.ImageIcon(new URL(lugarImagen)).getImage().getScaledInstance(txtImagen.getWidth(), txtImagen.getWidth(), Image.SCALE_DEFAULT);
        Icon imagen=new ImageIcon(icon);
        txtImagen.setIcon(imagen);
        
        fnacim.setText("");
        sexo.setText("");
        nacion.setText("");
        observa.setText("");
        status.setText("");
        fecha.setText("");
        usuario.setText("");
        txtNombre.setText(Acceso.getNombreUsuario());
        txtEmpresa.setText(Acceso.getEmpresaUsuario());
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        salir = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        busrfc = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        buspat = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        busmat = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        busnom = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablatraba = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        rfc = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        curp = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        paterno = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        materno = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        path = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        fnacim = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        sexo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        nacion = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        observa = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        status = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        fecha = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();
        txtImagen = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        datper = new javax.swing.JButton();
        documenta = new javax.swing.JButton();
        escolar = new javax.swing.JButton();
        familiar = new javax.swing.JButton();
        exper = new javax.swing.JButton();
        benefi = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtEmpresa = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SNTIAISCRM Sistema de Recursos Humanos");
        setMaximumSize(new java.awt.Dimension(1000, 650));
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        jLabel15.setText("RFC:");

        busrfc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                busrfcMouseClicked(evt);
            }
        });
        busrfc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                busrfcKeyPressed(evt);
            }
        });

        jLabel16.setText("Paterno:");

        buspat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buspatMouseClicked(evt);
            }
        });
        buspat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                buspatKeyPressed(evt);
            }
        });

        jLabel17.setText("Materno:");

        busmat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                busmatMouseClicked(evt);
            }
        });
        busmat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                busmatKeyPressed(evt);
            }
        });

        jLabel18.setText("Nombre:");

        busnom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                busnomMouseClicked(evt);
            }
        });
        busnom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                busnomKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(busrfc, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buspat, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(busmat, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(busnom, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salir)
                    .addComponent(jLabel15)
                    .addComponent(busrfc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(buspat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(busmat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(busnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        tablatraba.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RFC", "Paterno", "Materno", "Nombre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablatraba.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablatrabaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablatraba);

        jLabel2.setText("RFC:");

        rfc.setEditable(false);

        jLabel3.setText("CURP:");

        curp.setEditable(false);

        jLabel4.setText("Paterno:");

        paterno.setEditable(false);

        jLabel5.setText("Materno:");

        materno.setEditable(false);

        jLabel6.setText("Nombre:");

        nombre.setEditable(false);

        jLabel7.setText("Path:");

        path.setEditable(false);

        jLabel8.setText("Fec. Nac:");

        fnacim.setEditable(false);

        jLabel9.setText("Género:");

        sexo.setEditable(false);

        jLabel10.setText("Nacionalidad:");

        nacion.setEditable(false);

        jLabel11.setText("Observa:");

        observa.setEditable(false);

        jLabel12.setText("Status:");

        status.setEditable(false);

        jLabel13.setText("Fecha:");

        fecha.setEditable(false);

        jLabel14.setText("Usuario:");

        usuario.setEditable(false);

        txtImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtImagen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        txtImagen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(rfc)
                            .addComponent(curp)
                            .addComponent(paterno)
                            .addComponent(materno)
                            .addComponent(nombre)
                            .addComponent(path)
                            .addComponent(fnacim, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sexo)
                            .addComponent(nacion)
                            .addComponent(observa, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(status)
                            .addComponent(fecha)
                            .addComponent(usuario))
                        .addGap(44, 44, 44)
                        .addComponent(txtImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(rfc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(curp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(nacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(paterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(observa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(materno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(path, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(txtImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(fnacim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        datper.setForeground(new java.awt.Color(0, 0, 153));
        datper.setText("Datos Personales");
        datper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datperActionPerformed(evt);
            }
        });

        documenta.setForeground(new java.awt.Color(0, 0, 153));
        documenta.setText("Documentación");
        documenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                documentaActionPerformed(evt);
            }
        });

        escolar.setForeground(new java.awt.Color(0, 0, 153));
        escolar.setText("Escolaridad");
        escolar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                escolarActionPerformed(evt);
            }
        });

        familiar.setForeground(new java.awt.Color(0, 0, 153));
        familiar.setText("Familiares");
        familiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                familiarActionPerformed(evt);
            }
        });

        exper.setForeground(new java.awt.Color(0, 0, 153));
        exper.setText("Experiencia");
        exper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                experActionPerformed(evt);
            }
        });

        benefi.setForeground(new java.awt.Color(0, 0, 153));
        benefi.setText("Beneficiarios");
        benefi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                benefiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(datper)
                .addGap(18, 18, 18)
                .addComponent(documenta)
                .addGap(18, 18, 18)
                .addComponent(escolar)
                .addGap(18, 18, 18)
                .addComponent(familiar)
                .addGap(18, 18, 18)
                .addComponent(exper)
                .addGap(18, 18, 18)
                .addComponent(benefi)
                .addContainerGap(179, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(datper)
                    .addComponent(documenta)
                    .addComponent(escolar)
                    .addComponent(familiar)
                    .addComponent(exper)
                    .addComponent(benefi))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("BUSQUEDA DE ASPIRANTES");

        txtEmpresa.setEditable(false);
        txtEmpresa.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        txtEmpresa.setForeground(new java.awt.Color(204, 0, 0));
        txtEmpresa.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtEmpresa.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtNombre.setEditable(false);
        txtNombre.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(204, 0, 0));
        txtNombre.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtNombre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        this.dispose();
    }//GEN-LAST:event_salirActionPerformed

    private void busrfcKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_busrfcKeyPressed
        cTrabaA e=new cTrabaA();
        Limpiar(tablatraba);
        DefaultTableModel modelo= (DefaultTableModel) tablatraba.getModel();
        e.BusRfc(modelo, busrfc.getText().toUpperCase());
    }//GEN-LAST:event_busrfcKeyPressed

    private void buspatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buspatKeyPressed
        cTrabaA e=new cTrabaA();
        Limpiar(tablatraba);
        DefaultTableModel modelo= (DefaultTableModel) tablatraba.getModel();
        e.BusPat(modelo, buspat.getText().toUpperCase());
    }//GEN-LAST:event_buspatKeyPressed

    private void busmatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_busmatKeyPressed
        cTrabaA e=new cTrabaA();
        Limpiar(tablatraba);
        DefaultTableModel modelo= (DefaultTableModel) tablatraba.getModel();
        e.BusMat(modelo, busmat.getText().toUpperCase());
    }//GEN-LAST:event_busmatKeyPressed

    private void busnomKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_busnomKeyPressed
        cTrabaA e=new cTrabaA();
        Limpiar(tablatraba);
        DefaultTableModel modelo= (DefaultTableModel) tablatraba.getModel();
        e.BusNom(modelo, busnom.getText().toUpperCase());
    }//GEN-LAST:event_busnomKeyPressed

    private void tablatrabaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablatrabaMouseClicked
        try {
            DefaultTableModel modelo= (DefaultTableModel) tablatraba.getModel();
            rfc.setText(modelo.getValueAt(tablatraba.getSelectedRow(), 0)+"");
            paterno.setText(modelo.getValueAt(tablatraba.getSelectedRow(), 1)+"");
            materno.setText(modelo.getValueAt(tablatraba.getSelectedRow(), 2)+"");
            nombre.setText(modelo.getValueAt(tablatraba.getSelectedRow(), 3)+"");
            
            String RegFed = rfc.getText();
            String PaAc = paterno.getText();
            String MaAc = materno.getText();
            String NoAc = nombre.getText();
            
            cTrabaA com=new cTrabaA();
            Object[] datos1=com.Comple(RegFed, PaAc, MaAc, NoAc);
            //rfc.setText(datos1[0]+"");
            curp.setText(datos1[1]+"");
            //paterno.setText(datos1[2]+"");
            //materno.setText(datos1[3]+"");
            //nombre.setText(datos1[4]+"");
            path.setText(datos1[5]+"");
            fnacim.setText(datos1[6]+"");
            sexo.setText(datos1[7]+"");
            nacion.setText(datos1[8]+"");
            observa.setText(datos1[9]+"");
            status.setText(datos1[10]+"");
            fecha.setText(datos1[11]+"");
            usuario.setText(datos1[12]+"");
            
            String lugarImagen="";
            lugarImagen=path.getText();
            //Image icon=new ImageIcon(lugarImagen).getImage().getScaledInstance(txtImagen.getWidth(), txtImagen.getWidth(), Image.SCALE_DEFAULT);
            //Icon imagen=new ImageIcon(icon);
            //txtImagen.setIcon(imagen);
            
            Image icon= new javax.swing.ImageIcon(new URL(lugarImagen)).getImage().getScaledInstance(txtImagen.getWidth(), txtImagen.getWidth(), Image.SCALE_DEFAULT);
            Icon imagen=new ImageIcon(icon);
            txtImagen.setIcon(imagen);
            
            cTrabaA.setRfcUsuario(rfc.getText());
            cTrabaA.setNomTrabaja(nombre.getText()+" "+paterno.getText()+" "+materno.getText());
        } catch (MalformedURLException ex) {
            Logger.getLogger(cTrabaAConsola.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tablatrabaMouseClicked

    private void busrfcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_busrfcMouseClicked
        try {
            Iniciar();
        } catch (MalformedURLException ex) {
            Logger.getLogger(cTrabaAConsola.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_busrfcMouseClicked

    private void buspatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buspatMouseClicked
        try {
            Iniciar();
        } catch (MalformedURLException ex) {
            Logger.getLogger(cTrabaAConsola.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buspatMouseClicked

    private void busmatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_busmatMouseClicked
        try {
            Iniciar();
        } catch (MalformedURLException ex) {
            Logger.getLogger(cTrabaAConsola.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_busmatMouseClicked

    private void busnomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_busnomMouseClicked
        try {
            Iniciar();
        } catch (MalformedURLException ex) {
            Logger.getLogger(cTrabaAConsola.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_busnomMouseClicked

    private void datperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datperActionPerformed
        String drfc=rfc.getText().toUpperCase();
        if(drfc.isEmpty()){
            try {
                JOptionPane.showMessageDialog(this, "Necesita proporcionar un Rfc válido, verifique .....");
                Iniciar();
            } catch (MalformedURLException ex) {
                Logger.getLogger(cTrabaAConsola.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            cDatosAConsola object=new cDatosAConsola();
            object.setLocationRelativeTo(null);
            object.setVisible(true);
        }
    }//GEN-LAST:event_datperActionPerformed

    private void documentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_documentaActionPerformed
        String drfc=rfc.getText().toUpperCase();
        if(drfc.isEmpty()){
            try {
                JOptionPane.showMessageDialog(this, "Necesita proporcionar un Rfc válido, verifique .....");
                Iniciar();
            } catch (MalformedURLException ex) {
                Logger.getLogger(cTrabaAConsola.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            cDocumAConsola object=new cDocumAConsola();
            object.setLocationRelativeTo(null);
            object.setVisible(true);
        }
    }//GEN-LAST:event_documentaActionPerformed

    private void escolarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_escolarActionPerformed
        String drfc=rfc.getText().toUpperCase();
        if(drfc.isEmpty()){
            try {
                JOptionPane.showMessageDialog(this, "Necesita proporcionar un Rfc válido, verifique .....");
                Iniciar();
            } catch (MalformedURLException ex) {
                Logger.getLogger(cTrabaAConsola.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            cEscolAConsola object=new cEscolAConsola();
            object.setLocationRelativeTo(null);
            object.setVisible(true);
        }
    }//GEN-LAST:event_escolarActionPerformed

    private void familiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_familiarActionPerformed
        String drfc=rfc.getText().toUpperCase();
        if(drfc.isEmpty()){
            try {
                JOptionPane.showMessageDialog(this, "Necesita proporcionar un Rfc válido, verifique .....");
                Iniciar();
            } catch (MalformedURLException ex) {
                Logger.getLogger(cTrabaAConsola.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            cFamilAConsola object=new cFamilAConsola();
            object.setLocationRelativeTo(null);
            object.setVisible(true);
        }
    }//GEN-LAST:event_familiarActionPerformed

    private void experActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_experActionPerformed
        String drfc=rfc.getText().toUpperCase();
        if(drfc.isEmpty()){
            try {
                JOptionPane.showMessageDialog(this, "Necesita proporcionar un Rfc válido, verifique .....");
                Iniciar();
            } catch (MalformedURLException ex) {
                Logger.getLogger(cTrabaAConsola.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            cExperAConsola object=new cExperAConsola();
            object.setLocationRelativeTo(null);
            object.setVisible(true);
        }
    }//GEN-LAST:event_experActionPerformed

    private void benefiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_benefiActionPerformed
        String drfc=rfc.getText().toUpperCase();
        if(drfc.isEmpty()){
            try {
                JOptionPane.showMessageDialog(this, "Necesita proporcionar un Rfc válido, verifique .....");
                Iniciar();
            } catch (MalformedURLException ex) {
                Logger.getLogger(cTrabaAConsola.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            cBenefAConsola object=new cBenefAConsola();
            object.setLocationRelativeTo(null);
            object.setVisible(true);
        }
    }//GEN-LAST:event_benefiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cTrabaAConsola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cTrabaAConsola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cTrabaAConsola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cTrabaAConsola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new cTrabaAConsola().setVisible(true);
                } catch (MalformedURLException ex) {
                    Logger.getLogger(cTrabaAConsola.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton benefi;
    private javax.swing.JTextField busmat;
    private javax.swing.JTextField busnom;
    private javax.swing.JTextField buspat;
    private javax.swing.JTextField busrfc;
    private javax.swing.JTextField curp;
    private javax.swing.JButton datper;
    private javax.swing.JButton documenta;
    private javax.swing.JButton escolar;
    private javax.swing.JButton exper;
    private javax.swing.JButton familiar;
    private javax.swing.JTextField fecha;
    private javax.swing.JTextField fnacim;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField materno;
    private javax.swing.JTextField nacion;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField observa;
    private javax.swing.JTextField paterno;
    private javax.swing.JTextField path;
    private javax.swing.JTextField rfc;
    private javax.swing.JButton salir;
    private javax.swing.JTextField sexo;
    private javax.swing.JTextField status;
    private javax.swing.JTable tablatraba;
    private javax.swing.JTextField txtEmpresa;
    private javax.swing.JLabel txtImagen;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
