
package sirh;

import java.text.*;
import java.util.*;
import javax.swing.JOptionPane;

public class DatosConsola extends javax.swing.JFrame {


    public DatosConsola() {
        initComponents();
        setResizable(false);
        setDefaultCloseOperation(0);
        Iniciar();
    }

    private void Iniciar(){
        padom.removeAllItems();
        padom.addItem("");
        Datos e=new Datos();
        e.LlenarPadom(padom);
        esdom.removeAllItems();
        esdom.addItem("");
        mddom.removeAllItems();
        mddom.addItem("");
        podom.removeAllItems();
        podom.addItem("");
        codom.removeAllItems();
        codom.addItem("");
        calle.setText("");
        exterior.setText("");
        interior.setText("");
        referencias.setText("");
        codigo.setText("");
        telefono.setText("");
        celular.setText("");
        correo.setText("");
        panac.removeAllItems();
        panac.addItem("");
        Datos e1=new Datos();
        e1.LlenarPanac(panac);
        esnac.removeAllItems();
        esnac.addItem("");
        mdnac.removeAllItems();
        mdnac.addItem("");
        ponac.removeAllItems();
        ponac.addItem("");
        religion.removeAllItems();
        religion.addItem("");
        Datos e2=new Datos();
        e2.LlenarReligion(religion);
        civil.removeAllItems();
        civil.addItem("");
        Datos e3=new Datos();
        e3.LlenarCivil(civil);
        sangre.removeAllItems();
        sangre.addItem("");
        Datos e4=new Datos();
        e4.LlenarSangre(sangre);
        peso.setText("");
        fpeso.setDate(null);
        estatura.setText("");
        festatura.setDate(null);
        extra1.setText("");
        extra2.setText("");
        camisa.setText("");
        vcamisa.setText("");
        fcamisa.setDate(null);
        pantalon.setText("");
        vpantalon.setText("");
        fpantalon.setDate(null);
        zapatos.setText("");
        vzapatos.setText("");
        fzapatos.setDate(null);
        recom1.setText("");
        miem1.removeAllItems();
        miem1.addItem("");
        Datos e5=new Datos();
        e5.LlenarSino(miem1);
        fam1.removeAllItems();
        fam1.addItem("");
        Datos e7=new Datos();
        e7.LlenarSino(fam1);
        recom2.setText("");
        miem2.removeAllItems();
        miem2.addItem("");
        Datos e6=new Datos();
        e6.LlenarSino(miem2);
        fam2.removeAllItems();
        fam2.addItem("");
        status.setText("");
        Datos e8=new Datos();
        e8.LlenarSino(fam2);
        crear.setEnabled(true);
       
        fecha.setText(fechaActual());
        usuario.setText(Acceso.getClaveUsuario());
        txtNombre.setText(Acceso.getNombreUsuario());
        txtEmpresa.setText(Acceso.getEmpresaUsuario());
        txtNumero.setText(String.valueOf(Traba.getNumTrabaja()));
        txtTrabaja.setText(Traba.getNomTrabaja());
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        padom = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        esdom = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        mddom = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        podom = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        codom = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        calle = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        referencias = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        exterior = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        interior = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        codigo = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        telefono = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        celular = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        correo = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        panac = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        esnac = new javax.swing.JComboBox();
        jLabel18 = new javax.swing.JLabel();
        mdnac = new javax.swing.JComboBox();
        jLabel19 = new javax.swing.JLabel();
        ponac = new javax.swing.JComboBox();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        religion = new javax.swing.JComboBox();
        jLabel22 = new javax.swing.JLabel();
        civil = new javax.swing.JComboBox();
        jLabel23 = new javax.swing.JLabel();
        sangre = new javax.swing.JComboBox();
        jLabel24 = new javax.swing.JLabel();
        extra1 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        extra2 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        festatura = new com.toedter.calendar.JDateChooser();
        fpeso = new com.toedter.calendar.JDateChooser();
        jLabel28 = new javax.swing.JLabel();
        camisa = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        pantalon = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        zapatos = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        recom1 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        miem1 = new javax.swing.JComboBox();
        jLabel35 = new javax.swing.JLabel();
        fam1 = new javax.swing.JComboBox();
        jLabel36 = new javax.swing.JLabel();
        recom2 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        miem2 = new javax.swing.JComboBox();
        jLabel38 = new javax.swing.JLabel();
        fam2 = new javax.swing.JComboBox();
        jLabel39 = new javax.swing.JLabel();
        status = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        fecha = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();
        peso = new javax.swing.JFormattedTextField();
        estatura = new javax.swing.JFormattedTextField();
        fcamisa = new com.toedter.calendar.JDateChooser();
        fpantalon = new com.toedter.calendar.JDateChooser();
        fzapatos = new com.toedter.calendar.JDateChooser();
        vcamisa = new javax.swing.JTextField();
        vpantalon = new javax.swing.JTextField();
        vzapatos = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        crear = new javax.swing.JButton();
        actualizar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtEmpresa = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        txtTrabaja = new javax.swing.JTextField();

        jFormattedTextField1.setText("jFormattedTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SNTIAISCRM Sistema de Recursos Humanos");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jLabel2.setText("Domicilio Particular:");

        padom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                padomActionPerformed(evt);
            }
        });

        jLabel3.setText("País");

        esdom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                esdomActionPerformed(evt);
            }
        });

        jLabel4.setText("Estado");

        mddom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mddomActionPerformed(evt);
            }
        });

        jLabel5.setText("Municipio / Delegación");

        podom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                podomActionPerformed(evt);
            }
        });

        jLabel6.setText("Población");

        codom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codomActionPerformed(evt);
            }
        });

        jLabel7.setText("Colonia");

        jLabel8.setText("Calle:");

        jLabel9.setText("Referencias:");

        jLabel10.setText("Num.Ext.:");

        jLabel11.setText("Num. Int.:");

        jLabel12.setText("Código Postal:");

        codigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                codigoKeyTyped(evt);
            }
        });

        jLabel13.setText("Teléfono:");

        jLabel14.setText("Celular:");

        jLabel15.setText("Correo:");

        jLabel16.setText("País");

        panac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panacActionPerformed(evt);
            }
        });

        jLabel17.setText("Lugar Nacim.:");

        esnac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                esnacActionPerformed(evt);
            }
        });

        jLabel18.setText("Estado");

        mdnac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mdnacActionPerformed(evt);
            }
        });

        jLabel19.setText("Municipio / Delegación");

        ponac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ponacActionPerformed(evt);
            }
        });

        jLabel20.setText("Población");

        jLabel21.setText("Religión:");

        jLabel22.setText("Estado Civil:");

        jLabel23.setText("Tipo Sangre:");

        jLabel24.setText("Act. Extra Curr 1:");

        jLabel25.setText("Act. Extra Curr 2:");

        jLabel26.setForeground(new java.awt.Color(204, 0, 51));
        jLabel26.setText("Peso (kgs):");

        jLabel27.setForeground(new java.awt.Color(204, 0, 51));
        jLabel27.setText("Estatura(m):");

        jLabel31.setForeground(new java.awt.Color(204, 0, 51));
        jLabel31.setText("Fecha:");

        jLabel32.setForeground(new java.awt.Color(204, 0, 51));
        jLabel32.setText("Fecha:");

        jLabel28.setText("Talla Camisa:");

        jLabel29.setText("Talla Pantalón:");

        jLabel30.setText("Talla Zapatos:");

        jLabel33.setText("Recomienda 1:");

        jLabel34.setText("Es miembro Sindicato:");

        jLabel35.setText("Tiene familiares en Sind.:");

        jLabel36.setText("Recomienda 2:");

        jLabel37.setText("Es miembro Sindicato:");

        jLabel38.setText("Tiene familiares en Sind.:");

        jLabel39.setText("Status:");

        status.setEditable(false);

        jLabel40.setText("Fecha:");

        fecha.setEditable(false);

        jLabel41.setText("Usuario:");

        usuario.setEditable(false);

        peso.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        peso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pesoKeyTyped(evt);
            }
        });

        estatura.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        estatura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                estaturaKeyTyped(evt);
            }
        });

        vcamisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                vcamisaKeyTyped(evt);
            }
        });

        vpantalon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                vpantalonKeyTyped(evt);
            }
        });

        vzapatos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                vzapatosKeyTyped(evt);
            }
        });

        jLabel42.setText("V:");

        jLabel43.setText("V:");

        jLabel44.setText("V:");

        jLabel45.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(204, 0, 51));
        jLabel45.setText("F:");

        jLabel46.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(204, 0, 51));
        jLabel46.setText("F:");

        jLabel47.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(204, 0, 51));
        jLabel47.setText("F:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel12)
                    .addComponent(jLabel17)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23)
                    .addComponent(jLabel26)
                    .addComponent(jLabel27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(referencias)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(calle, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(padom, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(esdom, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mddom, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(exterior))
                            .addComponent(podom, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(codom, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(interior))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(panac, 0, 156, Short.MAX_VALUE)
                            .addComponent(codigo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel18))
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mdnac, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(celular, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel15)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel20)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(correo)
                                    .addComponent(ponac, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(esnac, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(civil, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(peso, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                                    .addComponent(estatura))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel32)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(festatura, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel31)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(fpeso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addComponent(religion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sangre, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel29)
                                    .addComponent(jLabel30))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(pantalon, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                                    .addComponent(zapatos))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fpantalon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fzapatos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(extra1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel28))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(extra2, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(camisa, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel42)
                                                .addGap(14, 14, 14)
                                                .addComponent(vcamisa, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(60, 60, 60)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jLabel43)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(vpantalon, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jLabel44)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(vzapatos, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel45)
                                                .addGap(18, 18, 18)
                                                .addComponent(fcamisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel46)
                                            .addComponent(jLabel47))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel33)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(recom1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel34)
                                .addGap(18, 18, 18)
                                .addComponent(miem1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel35)
                                .addGap(18, 18, 18)
                                .addComponent(fam1, 0, 42, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel36)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(recom2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel37)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel39)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel40)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(fecha)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel41)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(miem2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel38)
                                        .addGap(18, 18, 18)
                                        .addComponent(fam2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(padom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(esdom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mddom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(podom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(calle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(exterior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(interior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(referencias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(celular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ponac, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(panac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel17)
                        .addComponent(esnac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(mdnac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(religion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(extra1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33)
                    .addComponent(recom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(civil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(extra2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34)
                    .addComponent(miem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35)
                    .addComponent(fam1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(sangre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel28)
                        .addComponent(camisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel36)
                        .addComponent(recom2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(vcamisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel42)
                        .addComponent(jLabel45))
                    .addComponent(fcamisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addComponent(jLabel31)
                    .addComponent(fpeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel29)
                        .addComponent(pantalon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel37)
                        .addComponent(miem2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel38)
                        .addComponent(fam2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(peso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fpantalon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(vpantalon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel43)
                        .addComponent(jLabel46)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fzapatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(jLabel32))
                        .addComponent(festatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel30)
                        .addComponent(zapatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel39)
                        .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel40)
                        .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel41)
                        .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(estatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(vzapatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel44)
                        .addComponent(jLabel47)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        crear.setText("Crear");
        crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearActionPerformed(evt);
            }
        });

        actualizar.setText("Actualizar");
        actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarActionPerformed(evt);
            }
        });

        eliminar.setText("Eliminar");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(crear)
                .addGap(18, 18, 18)
                .addComponent(actualizar)
                .addGap(18, 18, 18)
                .addComponent(eliminar)
                .addGap(18, 18, 18)
                .addComponent(cancelar)
                .addGap(18, 18, 18)
                .addComponent(salir)
                .addGap(310, 310, 310))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crear)
                    .addComponent(actualizar)
                    .addComponent(eliminar)
                    .addComponent(cancelar)
                    .addComponent(salir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("MOVIMIENTOS DE DATOS PERSONALES (Trabajadores)");

        txtEmpresa.setEditable(false);
        txtEmpresa.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        txtEmpresa.setForeground(new java.awt.Color(204, 0, 0));
        txtEmpresa.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtEmpresa.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtNombre.setEditable(false);
        txtNombre.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(204, 0, 0));
        txtNombre.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtNombre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtNumero.setEditable(false);

        txtTrabaja.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTrabaja, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                            .addComponent(txtEmpresa))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTrabaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(7, 7, 7)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearActionPerformed
        Datos e=new Datos();
        String ppso=peso.getText().toUpperCase();
        String estat=estatura.getText().toUpperCase();
        if(ppso.isEmpty()){
            JOptionPane.showMessageDialog(this, "Se requiere el peso del trabajador, verifique .....");
            peso.grabFocus();
        }
        else{
            if(estat.isEmpty()){
                JOptionPane.showMessageDialog(this, "Se requiere la estatura del trabajador, verifique .....");
                estatura.grabFocus();
            }
            else{
                if(fpeso.getDate() == null){
                    JOptionPane.showMessageDialog(this, "Se requiere la fecha del peso del trabajador, verifique .....");
                    fpeso.grabFocus();
                }
                else{        
                    if(festatura.getDate() == null){
                        JOptionPane.showMessageDialog(this, "Se requiere la fecha de la estatura del trabajador, verifique .....");
                        festatura.grabFocus();
                    }
                    else{
                        if(fcamisa.getDate() == null){
                            JOptionPane.showMessageDialog(this, "Se requiere la fecha de la camisa del trabajador, verifique .....");
                            fcamisa.grabFocus();
                        }
                        else{
                            if(fpantalon.getDate() == null){
                                JOptionPane.showMessageDialog(this, "Se requiere la fecha del pantalón del trabajador, verifique .....");
                                fpantalon.grabFocus();
                            }
                            else{
                                if(fzapatos.getDate() == null){
                                    JOptionPane.showMessageDialog(this, "Se requiere la fecha de los zapatos del trabajador, verifique .....");
                                    fzapatos.grabFocus();
                                }
                                else{
                                    String dpadom=padom.getSelectedItem().toString();
                                    String desdom=esdom.getSelectedItem().toString();
                                    String dmddom=mddom.getSelectedItem().toString();
                                    String dpodom=podom.getSelectedItem().toString();
                                    String dcodom=codom.getSelectedItem().toString();
                                    String dcalle=calle.getText().toUpperCase();
                                    String dexterior=exterior.getText().toUpperCase();
                                    String dinterior=interior.getText().toUpperCase();
                                    String dreferencias=referencias.getText().toUpperCase();
                                    int dcodigo=Integer.parseInt(codigo.getText());
                                    String dtelefono=telefono.getText().toUpperCase();
                                    String dcelular=celular.getText().toUpperCase();
                                    String dcorreo=correo.getText().toUpperCase();
                                    String dpanac=panac.getSelectedItem().toString();
                                    String desnac=esnac.getSelectedItem().toString();
                                    String dmdnac=mdnac.getSelectedItem().toString();
                                    String dponac=ponac.getSelectedItem().toString();
                                    String dreligion=religion.getSelectedItem().toString();
                                    String dcivil=civil.getSelectedItem().toString();
                                    String dsangre=sangre.getSelectedItem().toString();
                                    Float dpeso=Float.parseFloat(peso.getText());
                                    int añop=fpeso.getCalendar().get(Calendar.YEAR);
                                    int mesp=fpeso.getCalendar().get(Calendar.MONTH)+1;
                                    int diap=fpeso.getCalendar().get(Calendar.DAY_OF_MONTH);
                                    String dfpeso=(añop+"/"+mesp+"/"+diap);
                                    Float destatura=Float.parseFloat(estatura.getText());
                                    int añoe=festatura.getCalendar().get(Calendar.YEAR);
                                    int mese=festatura.getCalendar().get(Calendar.MONTH)+1;
                                    int diae=festatura.getCalendar().get(Calendar.DAY_OF_MONTH);
                                    String dfestatura=(añoe+"/"+mese+"/"+diae);
                                    String dextra1=extra1.getText().toUpperCase();
                                    String dextra2=extra2.getText().toUpperCase();
                                    String dcamisa=camisa.getText().toUpperCase();
                                    int dvcamisa=Integer.parseInt(vcamisa.getText());
                                    int añofc=fcamisa.getCalendar().get(Calendar.YEAR);
                                    int mesfc=fcamisa.getCalendar().get(Calendar.MONTH)+1;
                                    int diafc=fcamisa.getCalendar().get(Calendar.DAY_OF_MONTH);
                                    String dfcamisa=(añofc+"/"+mesfc+"/"+diafc);
                                    String dpantalon=pantalon.getText().toUpperCase();
                                    int dvpantalon=Integer.parseInt(vpantalon.getText());
                                    int añofp=fpantalon.getCalendar().get(Calendar.YEAR);
                                    int mesfp=fpantalon.getCalendar().get(Calendar.MONTH)+1;
                                    int diafp=fpantalon.getCalendar().get(Calendar.DAY_OF_MONTH);
                                    String dfpantalon=(añofp+"/"+mesfp+"/"+diafp);
                                    String dzapatos=zapatos.getText().toUpperCase();
                                    int dvzapatos=Integer.parseInt(vzapatos.getText());
                                    int añofz=fzapatos.getCalendar().get(Calendar.YEAR);
                                    int mesfz=fzapatos.getCalendar().get(Calendar.MONTH)+1;
                                    int diafz=fzapatos.getCalendar().get(Calendar.DAY_OF_MONTH);
                                    String dfzapatos=(añofz+"/"+mesfz+"/"+diafz);
                                    String drecom1=recom1.getText().toUpperCase();
                                    String dmiem1=miem1.getSelectedItem().toString();
                                    String dfam1=fam1.getSelectedItem().toString();
                                    String drecom2=recom2.getText().toUpperCase();
                                    String dmiem2=miem2.getSelectedItem().toString();
                                    String dfam2=fam2.getSelectedItem().toString();
                                    e.Agregar(Traba.getNumTrabaja(), dpadom, desdom, dmddom, dpodom, dcodom, dcalle, dexterior,
                                              dinterior, dreferencias, dcodigo, dtelefono, dcelular, dcorreo, dpanac, desnac, dmdnac,
                                              dponac, dreligion, dcivil, dsangre, dpeso, dfpeso, destatura, dfestatura, dextra1,
                                              dextra2, dcamisa, dvcamisa, dfcamisa, dpantalon, dvpantalon, dfpantalon, dzapatos,
                                              dvzapatos, dfzapatos, drecom1, dmiem1, dfam1, drecom2, dmiem2, dfam2, Acceso.getClaveUsuario());
                                    JOptionPane.showMessageDialog(this, "Registro creado .....");
                                    Iniciar();
                                }
                            }
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_crearActionPerformed

    private void actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarActionPerformed
        Datos e=new Datos();
        String ppso=peso.getText().toUpperCase();
        String estat=estatura.getText().toUpperCase();
        if(ppso.isEmpty()){
            JOptionPane.showMessageDialog(this, "Se requiere el peso del trabajador, verifique .....");
            peso.grabFocus();
        }
        else{
            if(estat.isEmpty()){
                JOptionPane.showMessageDialog(this, "Se requiere la estatura del trabajador, verifique .....");
                estatura.grabFocus();
            }
            else{
                if(fpeso.getDate() == null){
                    JOptionPane.showMessageDialog(this, "Se requiere la fecha del peso del trabajador, verifique .....");
                    fpeso.grabFocus();
                }
                else{        
                    if(festatura.getDate() == null){
                        JOptionPane.showMessageDialog(this, "Se requiere la fecha de la estatura del trabajador, verifique .....");
                        festatura.grabFocus();
                    }
                    else{
                        if(fcamisa.getDate() == null){
                            JOptionPane.showMessageDialog(this, "Se requiere la fecha de la camisa del trabajador, verifique .....");
                            fcamisa.grabFocus();
                        }
                        else{
                            if(fpantalon.getDate() == null){
                                JOptionPane.showMessageDialog(this, "Se requiere la fecha del pantalón del trabajador, verifique .....");
                                fpantalon.grabFocus();
                            }
                            else{
                                if(fzapatos.getDate() == null){
                                    JOptionPane.showMessageDialog(this, "Se requiere la fecha de los zapatos del trabajador, verifique .....");
                                    fzapatos.grabFocus();
                                }
                                else{
                                    String dpadom=padom.getSelectedItem().toString();
                                    String desdom=esdom.getSelectedItem().toString();
                                    String dmddom=mddom.getSelectedItem().toString();
                                    String dpodom=podom.getSelectedItem().toString();
                                    String dcodom=codom.getSelectedItem().toString();
                                    String dcalle=calle.getText().toUpperCase();
                                    String dexterior=exterior.getText().toUpperCase();
                                    String dinterior=interior.getText().toUpperCase();
                                    String dreferencias=referencias.getText().toUpperCase();
                                    int dcodigo=Integer.parseInt(codigo.getText());
                                    String dtelefono=telefono.getText().toUpperCase();
                                    String dcelular=celular.getText().toUpperCase();
                                    String dcorreo=correo.getText().toUpperCase();
                                    String dpanac=panac.getSelectedItem().toString();
                                    String desnac=esnac.getSelectedItem().toString();
                                    String dmdnac=mdnac.getSelectedItem().toString();
                                    String dponac=ponac.getSelectedItem().toString();
                                    String dreligion=religion.getSelectedItem().toString();
                                    String dcivil=civil.getSelectedItem().toString();
                                    String dsangre=sangre.getSelectedItem().toString();
                                    Float dpeso=Float.parseFloat(peso.getText());
                                    int añop=fpeso.getCalendar().get(Calendar.YEAR);
                                    int mesp=fpeso.getCalendar().get(Calendar.MONTH)+1;
                                    int diap=fpeso.getCalendar().get(Calendar.DAY_OF_MONTH);
                                    String dfpeso=(añop+"/"+mesp+"/"+diap);
                                    Float destatura=Float.parseFloat(estatura.getText());
                                    int añoe=festatura.getCalendar().get(Calendar.YEAR);
                                    int mese=festatura.getCalendar().get(Calendar.MONTH)+1;
                                    int diae=festatura.getCalendar().get(Calendar.DAY_OF_MONTH);
                                    String dfestatura=(añoe+"/"+mese+"/"+diae);
                                    String dextra1=extra1.getText().toUpperCase();
                                    String dextra2=extra2.getText().toUpperCase();
                                    String dcamisa=camisa.getText().toUpperCase();
                                    int dvcamisa=Integer.parseInt(vcamisa.getText());
                                    int añofc=fcamisa.getCalendar().get(Calendar.YEAR);
                                    int mesfc=fcamisa.getCalendar().get(Calendar.MONTH)+1;
                                    int diafc=fcamisa.getCalendar().get(Calendar.DAY_OF_MONTH);
                                    String dfcamisa=(añofc+"/"+mesfc+"/"+diafc);
                                    String dpantalon=pantalon.getText().toUpperCase();
                                    int dvpantalon=Integer.parseInt(vpantalon.getText());
                                    int añofp=fpantalon.getCalendar().get(Calendar.YEAR);
                                    int mesfp=fpantalon.getCalendar().get(Calendar.MONTH)+1;
                                    int diafp=fpantalon.getCalendar().get(Calendar.DAY_OF_MONTH);
                                    String dfpantalon=(añofp+"/"+mesfp+"/"+diafp);
                                    String dzapatos=zapatos.getText().toUpperCase();
                                    int dvzapatos=Integer.parseInt(vzapatos.getText());
                                    int añofz=fzapatos.getCalendar().get(Calendar.YEAR);
                                    int mesfz=fzapatos.getCalendar().get(Calendar.MONTH)+1;
                                    int diafz=fzapatos.getCalendar().get(Calendar.DAY_OF_MONTH);
                                    String dfzapatos=(añofz+"/"+mesfz+"/"+diafz);
                                    String drecom1=recom1.getText().toUpperCase();
                                    String dmiem1=miem1.getSelectedItem().toString();
                                    String dfam1=fam1.getSelectedItem().toString();
                                    String drecom2=recom2.getText().toUpperCase();
                                    String dmiem2=miem2.getSelectedItem().toString();
                                    String dfam2=fam2.getSelectedItem().toString();
                                    e.Actualizar(Traba.getNumTrabaja(), dpadom, desdom, dmddom, dpodom, dcodom, dcalle, dexterior,
                                                 dinterior, dreferencias, dcodigo, dtelefono, dcelular, dcorreo, dpanac, desnac, dmdnac,
                                                 dponac, dreligion, dcivil, dsangre, dpeso, dfpeso, destatura, dfestatura, dextra1,
                                                 dextra2, dcamisa, dvcamisa, dfcamisa, dpantalon, dvpantalon, dfpantalon, dzapatos,
                                                 dvzapatos, dfzapatos, drecom1, dmiem1, dfam1, drecom2, dmiem2, dfam2, Acceso.getClaveUsuario());
                                    JOptionPane.showMessageDialog(this, "Registro actualizado .....");
                                    Iniciar();
                                }
                            }
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_actualizarActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        Datos e=new Datos();
        e.Eliminar(Traba.getNumTrabaja(), Acceso.getClaveUsuario());
        JOptionPane.showMessageDialog(this, "Registro eliminado .....");
        Iniciar();
    }//GEN-LAST:event_eliminarActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        Iniciar();
    }//GEN-LAST:event_cancelarActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        this.dispose();
    }//GEN-LAST:event_salirActionPerformed

    private void padomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_padomActionPerformed
        esdom.removeAllItems();
        esdom.addItem("");
        mddom.removeAllItems();
        mddom.addItem("");
        podom.removeAllItems();
        podom.addItem("");
        codom.removeAllItems();
        codom.addItem("");
        String paiseleccionado=padom.getSelectedItem()+"";
        Datos ee1=new Datos();
        ee1.LlenarEsdom(esdom, paiseleccionado);
    }//GEN-LAST:event_padomActionPerformed

    private void esdomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_esdomActionPerformed
        mddom.removeAllItems();
        mddom.addItem("");
        podom.removeAllItems();
        podom.addItem("");
        codom.removeAllItems();
        codom.addItem("");
        String paiseleccionado=padom.getSelectedItem()+"";
        String edoseleccionado=esdom.getSelectedItem()+"";
        Datos ee2=new Datos();
        ee2.LlenarMddom(mddom, paiseleccionado, edoseleccionado);
    }//GEN-LAST:event_esdomActionPerformed

    private void podomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_podomActionPerformed
        codom.removeAllItems();
        codom.addItem("");
        String paiseleccionado=padom.getSelectedItem()+"";
        String edoseleccionado=esdom.getSelectedItem()+"";
        String mundelseleccionado=mddom.getSelectedItem()+"";
        String poblaseleccionado=podom.getSelectedItem()+"";
        Datos ee4=new Datos();
        ee4.LlenarCodom(codom, paiseleccionado, edoseleccionado, mundelseleccionado, poblaseleccionado);
    }//GEN-LAST:event_podomActionPerformed

    private void codomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codomActionPerformed
        // No se requiere
    }//GEN-LAST:event_codomActionPerformed

    private void mddomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mddomActionPerformed
        podom.removeAllItems();
        podom.addItem("");
        codom.removeAllItems();
        codom.addItem("");
        String paiseleccionado=padom.getSelectedItem()+"";
        String edoseleccionado=esdom.getSelectedItem()+"";
        String mundelseleccionado=mddom.getSelectedItem()+"";
        Datos ee3=new Datos();
        ee3.LlenarPodom(podom, paiseleccionado, edoseleccionado, mundelseleccionado);
    }//GEN-LAST:event_mddomActionPerformed

    private void panacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panacActionPerformed
        esnac.removeAllItems();
        esnac.addItem("");
        mdnac.removeAllItems();
        mdnac.addItem("");
        ponac.removeAllItems();
        ponac.addItem("");
        String paiseleccionado=panac.getSelectedItem()+"";
        Datos ee10=new Datos();
        ee10.LlenarEsnac(esnac, paiseleccionado);
    }//GEN-LAST:event_panacActionPerformed

    private void esnacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_esnacActionPerformed
        mdnac.removeAllItems();
        mdnac.addItem("");
        ponac.removeAllItems();
        ponac.addItem("");
        String paiseleccionado=panac.getSelectedItem()+"";
        String edoseleccionado=esnac.getSelectedItem()+"";
        Datos ee20=new Datos();
        ee20.LlenarMdnac(mdnac, paiseleccionado, edoseleccionado);
    }//GEN-LAST:event_esnacActionPerformed

    private void mdnacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mdnacActionPerformed
        ponac.removeAllItems();
        ponac.addItem("");
        String paiseleccionado=panac.getSelectedItem()+"";
        String edoseleccionado=esnac.getSelectedItem()+"";
        String mundelseleccionado=mdnac.getSelectedItem()+"";
        Datos ee30=new Datos();
        ee30.LlenarPonac(ponac, paiseleccionado, edoseleccionado, mundelseleccionado);
    }//GEN-LAST:event_mdnacActionPerformed

    private void ponacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ponacActionPerformed
        // No se utiliza
    }//GEN-LAST:event_ponacActionPerformed

    private void codigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codigoKeyTyped
        char car = evt.getKeyChar();
        if((car<'0' || car>'9')) evt.consume();
    }//GEN-LAST:event_codigoKeyTyped

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        int NumTra = Traba.getNumTrabaja();
        Datos val= new Datos();
        Object[] datos=val.Datos(NumTra);
        String checa=datos[0]+"";
        
        if(checa.trim().equals("null")){
            System.out.println("El registro NO existe ....");
            padom.grabFocus();
        }
        else{
            System.out.println("El registro SI existe ...");
            padom.setSelectedItem(datos[1]+"");   
            esdom.setSelectedItem(datos[2]+"");
            mddom.setSelectedItem(datos[3]+"");
            podom.setSelectedItem(datos[4]+"");
            codom.setSelectedItem(datos[5]+"");
            calle.setText(datos[6]+"");
            exterior.setText(datos[7]+"");
            interior.setText(datos[8]+"");
            codigo.setText(datos[9]+"");
            referencias.setText(datos[10]+"");
            telefono.setText(datos[11]+"");
            celular.setText(datos[12]+"");
            correo.setText(datos[13]+"");
            panac.setSelectedItem(datos[14]+"");
            esnac.setSelectedItem(datos[15]+"");
            mdnac.setSelectedItem(datos[16]+"");
            ponac.setSelectedItem(datos[17]+"");
            religion.setSelectedItem(datos[18]+"");
            civil.setSelectedItem(datos[19]+"");
            sangre.setSelectedItem(datos[20]+"");
            peso.setText(datos[21]+"");
            String fecpes = datos[22]+"";
            if("null".equals(fecpes)){
                //System.out.println("La fecha del peso esta vacia .....");
            }
            else{
                SimpleDateFormat formatofecha1=new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
                try{
                    Date fecha1 = formatofecha1.parse(fecpes);
                    fpeso.setDate(fecha1);
                }
                catch(ParseException pe1){
                    System.out.println("Error Parse1: "+pe1.getMessage());
                }
            }
            estatura.setText(datos[23]+"");
            String fecest = datos[24]+"";
            if("null".equals(fecest)){
                //System.out.println("La fecha de la estatura esta vacia .....");
            }
            else{
                SimpleDateFormat formatofecha2=new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
                try{
                    Date fecha2 = formatofecha2.parse(fecest);
                    festatura.setDate(fecha2);
                }
                catch(ParseException pe2){
                    System.out.println("Error Parse2: "+pe2.getMessage());
                }
            }
            extra1.setText(datos[25]+"");
            extra2.setText(datos[26]+"");
            camisa.setText(datos[27]+"");
            vcamisa.setText(datos[28]+"");
            String feccam = datos[29]+"";
            if("null".equals(feccam)){
                //System.out.println("La fecha de la camisa esta vacia .....");
            }
            else{
                SimpleDateFormat formatofecha3=new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
                try{
                    Date fecha3 = formatofecha3.parse(feccam);
                    fcamisa.setDate(fecha3);
                }
                catch(ParseException pe3){
                    System.out.println("Error Parse3: "+pe3.getMessage());
                }
            }
            pantalon.setText(datos[30]+"");
            vpantalon.setText(datos[31]+"");
            String fecpan = datos[32]+"";
            if("null".equals(fecpan)){
                //System.out.println("La fecha del pantalón esta vacia .....");
            }
            else{
                SimpleDateFormat formatofecha4=new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
                try{
                    Date fecha4 = formatofecha4.parse(fecpan);
                    fpantalon.setDate(fecha4);
                }
                catch(ParseException pe4){
                    System.out.println("Error Parse4: "+pe4.getMessage());
                }
            }
            zapatos.setText(datos[33]+"");
            vzapatos.setText(datos[34]+"");
            String feczap = datos[35]+"";
            if("null".equals(feczap)){
                //System.out.println("La fecha de los zapatos esta vacia .....");
            }
            else{
                SimpleDateFormat formatofecha5=new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
                try{
                    Date fecha5 = formatofecha5.parse(feczap);
                    fzapatos.setDate(fecha5);
                }
                catch(ParseException pe5){
                    System.out.println("Error Parse5: "+pe5.getMessage());
                }
            }
            recom1.setText(datos[36]+"");
            miem1.setSelectedItem(datos[37]+"");
            fam1.setSelectedItem(datos[38]+"");
            recom2.setText(datos[39]+"");
            miem2.setSelectedItem(datos[40]+"");
            fam2.setSelectedItem(datos[41]+"");
            status.setText(datos[42]+"");
            String freg = datos[43]+"";
            fecha.setText(freg);
            usuario.setText(datos[44]+"");
            crear.setEnabled(false);
            padom.grabFocus();
        }
    }//GEN-LAST:event_formWindowOpened

    private void pesoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pesoKeyTyped
        char car = evt.getKeyChar();
        if((car<'0' || car>'9') && (car != '.'))
        {
            evt.consume();
        }
    }//GEN-LAST:event_pesoKeyTyped

    private void estaturaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_estaturaKeyTyped
        char car = evt.getKeyChar();
        if((car<'0' || car>'9') && (car != '.'))
        {
            evt.consume();
        }
    }//GEN-LAST:event_estaturaKeyTyped

    private void vcamisaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_vcamisaKeyTyped
        char car = evt.getKeyChar();
        if((car<'0' || car>'9'))
        {
            evt.consume();
        }
    }//GEN-LAST:event_vcamisaKeyTyped

    private void vpantalonKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_vpantalonKeyTyped
        char car = evt.getKeyChar();
        if((car<'0' || car>'9'))
        {
            evt.consume();
        }
    }//GEN-LAST:event_vpantalonKeyTyped

    private void vzapatosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_vzapatosKeyTyped
        char car = evt.getKeyChar();
        if((car<'0' || car>'9'))
        {
            evt.consume();
        }
    }//GEN-LAST:event_vzapatosKeyTyped

    public static String fechaActual(){
        Date fecha= new Date();
        SimpleDateFormat formatoFecha=new SimpleDateFormat("dd/MM/YYYY HH:mm:ss");
        return formatoFecha.format(fecha);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DatosConsola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DatosConsola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DatosConsola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DatosConsola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DatosConsola().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizar;
    private javax.swing.JTextField calle;
    private javax.swing.JTextField camisa;
    private javax.swing.JButton cancelar;
    private javax.swing.JTextField celular;
    private javax.swing.JComboBox civil;
    private javax.swing.JTextField codigo;
    private javax.swing.JComboBox codom;
    private javax.swing.JTextField correo;
    private javax.swing.JButton crear;
    private javax.swing.JButton eliminar;
    private javax.swing.JComboBox esdom;
    private javax.swing.JComboBox esnac;
    private javax.swing.JFormattedTextField estatura;
    private javax.swing.JTextField exterior;
    private javax.swing.JTextField extra1;
    private javax.swing.JTextField extra2;
    private javax.swing.JComboBox fam1;
    private javax.swing.JComboBox fam2;
    private com.toedter.calendar.JDateChooser fcamisa;
    private javax.swing.JTextField fecha;
    private com.toedter.calendar.JDateChooser festatura;
    private com.toedter.calendar.JDateChooser fpantalon;
    private com.toedter.calendar.JDateChooser fpeso;
    private com.toedter.calendar.JDateChooser fzapatos;
    private javax.swing.JTextField interior;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox mddom;
    private javax.swing.JComboBox mdnac;
    private javax.swing.JComboBox miem1;
    private javax.swing.JComboBox miem2;
    private javax.swing.JComboBox padom;
    private javax.swing.JComboBox panac;
    private javax.swing.JTextField pantalon;
    private javax.swing.JFormattedTextField peso;
    private javax.swing.JComboBox podom;
    private javax.swing.JComboBox ponac;
    private javax.swing.JTextField recom1;
    private javax.swing.JTextField recom2;
    private javax.swing.JTextField referencias;
    private javax.swing.JComboBox religion;
    private javax.swing.JButton salir;
    private javax.swing.JComboBox sangre;
    private javax.swing.JTextField status;
    private javax.swing.JTextField telefono;
    private javax.swing.JTextField txtEmpresa;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtTrabaja;
    private javax.swing.JTextField usuario;
    private javax.swing.JTextField vcamisa;
    private javax.swing.JTextField vpantalon;
    private javax.swing.JTextField vzapatos;
    private javax.swing.JTextField zapatos;
    // End of variables declaration//GEN-END:variables
}
