
package sirh;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

public class EventConsola extends javax.swing.JFrame {


    public EventConsola() {
        initComponents();
        setDefaultCloseOperation(0);
        Iniciar();
    }
    
    private void Limpiar(JTable tabla){
        while(tabla.getRowCount()>0){
            ((DefaultTableModel) tabla.getModel()).removeRow(0);
        }
    }
    
    private void Iniciar(){
        Limpiar(tablaevent);
        DefaultTableModel modelo=(DefaultTableModel) tablaevent.getModel();
        Event e1=new Event();
        e1.LlenarDatos(modelo);
        numeve.setText("");
        cveemp.removeAllItems();
        cveemp.addItem("");
        Event e2=new Event();
        e2.LlenarCveempresa(cveemp);
        nomemp.setText("");
        feceve.setDate(null);
        horeve.setText("");
        numuni.removeAllItems();
        numuni.addItem("");
        Event e3=new Event();
        e3.LlenarCveunidad(numuni);
        maruni.setText("");
        moduni.setText("");
        plauni.setText("");
        numrut.removeAllItems();
        numrut.addItem("");
        Event e4=new Event();
        e4.LlenarCveruta(numrut);
        orirut.setText("");
        desrut.setText("");
        rfccho.removeAllItems();
        rfccho.addItem("");
        Event e5=new Event();
        e5.LlenarCvechofer(rfccho);
        nomcho.setText("");
        celcho.setText("");
        deseve.setText("");
        reseve.setText("");

        Limpiar(tablaevent1);
        busnum.setText("");
        busemp.setText("");
        busdes.setText("");
        numeve1.setText("");
        cveemp1.setText("");
        nomemp1.setText("");
        feceve1.setText("");
        horeve1.setText("");
        numuni1.setText("");
        maruni1.setText("");
        moduni1.setText("");
        plauni1.setText("");
        numrut1.setText("");
        orirut1.setText("");
        desrut1.setText("");
        rfccho1.setText("");
        nomcho1.setText("");
        celcho1.setText("");
        deseve1.setText("");
        reseve1.setText("");
        fecha1.setText("");
        usuario1.setText("");
        
        fecha.setText(fechaActual());
        usuario.setText(Acceso.getClaveUsuario());
        txtNombre.setText(Acceso.getNombreUsuario());
        txtEmpresa.setText(Acceso.getEmpresaUsuario());
        crear.setEnabled(true);
        cveemp.setEnabled(true);
        
    }
    
    public static String fechaActual(){
        Date fecha= new Date();
        SimpleDateFormat formatoFecha=new SimpleDateFormat("dd/MM/YYYY HH:mm:ss");
        return formatoFecha.format(fecha);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtEmpresa = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaevent1 = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        busnum = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        busemp = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        busdes = new javax.swing.JTextField();
        salir1 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        numeve1 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        nomemp1 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        horeve1 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        maruni1 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        moduni1 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        plauni1 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        orirut1 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        desrut1 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        nomcho1 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        celcho1 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        deseve1 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        reseve1 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        fecha1 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        usuario1 = new javax.swing.JTextField();
        cveemp1 = new javax.swing.JTextField();
        feceve1 = new javax.swing.JTextField();
        numuni1 = new javax.swing.JTextField();
        numrut1 = new javax.swing.JTextField();
        rfccho1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaevent = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        numeve = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cveemp = new javax.swing.JComboBox();
        nomemp = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        feceve = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        horeve = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        numuni = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        maruni = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        moduni = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        plauni = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        numrut = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        orirut = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        desrut = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        rfccho = new javax.swing.JComboBox();
        nomcho = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        celcho = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        deseve = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        reseve = new javax.swing.JTextField();
        crear = new javax.swing.JButton();
        actualizar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        fecha = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SNTIAISCRM Sistema de Recursos Humanos");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("EVENTOS DE TRANSPORTE DE PERSONAL");

        txtEmpresa.setEditable(false);
        txtEmpresa.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        txtEmpresa.setForeground(new java.awt.Color(204, 0, 0));
        txtEmpresa.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtEmpresa.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtNombre.setEditable(false);
        txtNombre.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(204, 0, 0));
        txtNombre.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtNombre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tablaevent1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Núm. Evento", "Empresa", "Fecha", "Hora", "Núm. Unidad", "Núm. Ruta", "Descripción", "Status", "Ultima Fecha", "Ultimo Usuario"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaevent1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaevent1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaevent1);

        jLabel19.setText("Número:");

        busnum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                busnumMouseClicked(evt);
            }
        });
        busnum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                busnumKeyPressed(evt);
            }
        });

        jLabel20.setText("Empresa:");

        busemp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                busempMouseClicked(evt);
            }
        });
        busemp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                busempKeyPressed(evt);
            }
        });

        jLabel21.setText("Descripción:");

        busdes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                busdesMouseClicked(evt);
            }
        });
        busdes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                busdesKeyPressed(evt);
            }
        });

        salir1.setText("Salir");
        salir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salir1ActionPerformed(evt);
            }
        });

        jLabel22.setText("Número de Evento:");

        numeve1.setEditable(false);

        jLabel23.setText("Clave Empresa:");

        nomemp1.setEditable(false);

        jLabel24.setText("Fecha Evento:");

        jLabel25.setText("Hora Evento:");

        horeve1.setEditable(false);

        jLabel26.setText("Número Unidad:");

        jLabel27.setText("Marca:");

        maruni1.setEditable(false);

        jLabel28.setText("Modelo:");

        moduni1.setEditable(false);

        jLabel29.setText("Placas:");

        plauni1.setEditable(false);

        jLabel30.setText("Número Ruta:");

        jLabel31.setText("Origen:");

        orirut1.setEditable(false);

        jLabel32.setText("Destino:");

        desrut1.setEditable(false);

        jLabel33.setText("Rfc Chofer:");

        nomcho1.setEditable(false);

        jLabel34.setText("Celular:");

        celcho1.setEditable(false);

        jLabel35.setText("Desc. Evento:");

        deseve1.setEditable(false);

        jLabel36.setText("Resolución:");

        reseve1.setEditable(false);

        jLabel37.setText("Fecha:");

        fecha1.setEditable(false);

        jLabel38.setText("Usuario:");

        usuario1.setEditable(false);

        cveemp1.setEditable(false);

        feceve1.setEditable(false);

        numuni1.setEditable(false);

        numrut1.setEditable(false);

        rfccho1.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(18, 18, 18)
                        .addComponent(busnum, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel20)
                        .addGap(18, 18, 18)
                        .addComponent(busemp, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel21)
                        .addGap(18, 18, 18)
                        .addComponent(busdes, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(salir1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel24)
                            .addComponent(jLabel26)
                            .addComponent(jLabel30)
                            .addComponent(jLabel33)
                            .addComponent(jLabel35)
                            .addComponent(jLabel36)
                            .addComponent(jLabel37))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(numuni1)
                                            .addComponent(numrut1, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel31))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel27)))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(orirut1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(maruni1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(feceve1)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(numeve1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel23)))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(cveemp1, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGap(33, 33, 33)
                                                .addComponent(jLabel25)))))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nomemp1)
                                    .addComponent(horeve1)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel28)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(moduni1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel29)
                                        .addGap(18, 18, 18)
                                        .addComponent(plauni1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel32)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(desrut1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rfccho1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(nomcho1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel34)
                                .addGap(18, 18, 18)
                                .addComponent(celcho1))
                            .addComponent(deseve1)
                            .addComponent(reseve1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(fecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel38)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(usuario1)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(busnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(busemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(busdes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salir1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(numeve1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(nomemp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cveemp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel24)
                        .addComponent(feceve1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel25)
                        .addComponent(horeve1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel26)
                        .addComponent(jLabel27)
                        .addComponent(maruni1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel28)
                        .addComponent(moduni1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(numuni1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(plauni1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel29)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel30)
                        .addComponent(numrut1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(orirut1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel32)
                        .addComponent(jLabel31))
                    .addComponent(desrut1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel33)
                    .addComponent(nomcho1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel34)
                        .addComponent(celcho1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(rfccho1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel35)
                    .addComponent(deseve1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel36)
                    .addComponent(reseve1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel37)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fecha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel38)
                        .addComponent(usuario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Búsqueda", jPanel1);

        tablaevent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Núm. Evento", "Empresa", "Fecha", "Hora", "Núm. Unidad", "Núm. Ruta", "Descripción", "Status", "Ultima Fecha", "Ultimo Usuario"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaevent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaeventMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaevent);

        jLabel2.setForeground(new java.awt.Color(204, 0, 51));
        jLabel2.setText("Número de Evento:");

        numeve.setEditable(false);

        jLabel3.setForeground(new java.awt.Color(204, 0, 51));
        jLabel3.setText("Clave Empresa:");

        cveemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cveempActionPerformed(evt);
            }
        });

        nomemp.setEditable(false);

        jLabel4.setForeground(new java.awt.Color(204, 0, 51));
        jLabel4.setText("Fecha Evento:");

        jLabel5.setText("Hora Evento:");

        jLabel6.setForeground(new java.awt.Color(204, 0, 51));
        jLabel6.setText("Número Unidad:");

        numuni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numuniActionPerformed(evt);
            }
        });

        jLabel7.setText("Marca:");

        maruni.setEditable(false);

        jLabel8.setText("Modelo:");

        moduni.setEditable(false);

        jLabel9.setText("Placas:");

        plauni.setEditable(false);

        jLabel10.setForeground(new java.awt.Color(204, 0, 51));
        jLabel10.setText("Número Ruta:");

        numrut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numrutActionPerformed(evt);
            }
        });

        jLabel11.setText("Origen:");

        orirut.setEditable(false);

        jLabel12.setText("Destino:");

        desrut.setEditable(false);

        jLabel13.setForeground(new java.awt.Color(204, 0, 51));
        jLabel13.setText("Rfc Chofer:");

        rfccho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rfcchoActionPerformed(evt);
            }
        });

        nomcho.setEditable(false);

        jLabel14.setText("Celular:");

        celcho.setEditable(false);

        jLabel15.setText("Desc. Evento:");

        jLabel16.setText("Resolución:");

        crear.setText("Crear");
        crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearActionPerformed(evt);
            }
        });

        actualizar.setText("Actualizar");
        actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarActionPerformed(evt);
            }
        });

        eliminar.setText("Eliminar");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        jLabel17.setText("Fecha:");

        fecha.setEditable(false);

        jLabel18.setText("Usuario:");

        usuario.setEditable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(crear)
                .addGap(18, 18, 18)
                .addComponent(actualizar)
                .addGap(18, 18, 18)
                .addComponent(eliminar)
                .addGap(18, 18, 18)
                .addComponent(cancelar)
                .addGap(18, 18, 18)
                .addComponent(salir)
                .addGap(232, 232, 232))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel10)
                            .addComponent(jLabel13)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(numeve, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel3)
                                        .addGap(33, 33, 33)
                                        .addComponent(cveemp, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(feceve, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel5))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(numuni, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel7))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(numrut, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel11)))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(orirut, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                                            .addComponent(maruni))))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nomemp)
                                    .addComponent(horeve)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(moduni, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel9)
                                                .addGap(18, 18, 18)
                                                .addComponent(plauni, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel12)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(desrut, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(rfccho, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(nomcho, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addComponent(celcho))
                            .addComponent(deseve)
                            .addComponent(reseve)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(usuario)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(numeve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(cveemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(feceve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(horeve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(numuni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)
                        .addComponent(maruni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)
                        .addComponent(moduni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(plauni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(numrut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(orirut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12))
                    .addComponent(desrut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rfccho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nomcho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(celcho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(deseve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(reseve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel18)
                        .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crear)
                    .addComponent(actualizar)
                    .addComponent(eliminar)
                    .addComponent(cancelar)
                    .addComponent(salir))
                .addGap(71, 71, 71))
        );

        jTabbedPane1.addTab("Movimientos", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearActionPerformed
        Event e=new Event();
        String dcveemp = cveemp.getSelectedItem().toString();
        if(dcveemp.isEmpty()){
            JOptionPane.showMessageDialog(this, "Se requiere una clave de empresa, verifique .....");
            cveemp.grabFocus();
        }
        else{
            if(feceve.getDate() == null){
                JOptionPane.showMessageDialog(this, "Se requiere la fecha del evento, verifique .....");
                feceve.grabFocus();
            }
            else{
                String dnumuni = numuni.getSelectedItem().toString();
                if(dnumuni.isEmpty()){
                    JOptionPane.showMessageDialog(this, "Se requiere un número o clave de unidad, verifique .....");
                    numuni.grabFocus();
                }
                else{
                    String dnumrut = numrut.getSelectedItem().toString();
                    if(dnumrut.isEmpty()){
                        JOptionPane.showMessageDialog(this, "Se requiere un número o clave de ruta, verifique .....");
                        numrut.grabFocus();
                    }
                    else{
                        String drfccho = rfccho.getSelectedItem().toString();
                        if(drfccho.isEmpty()){
                            JOptionPane.showMessageDialog(this, "Se requiere el rfc del chofer, verifique .....");
                            rfccho.grabFocus();
                        }
                        else{
                            String dnomemp = nomemp.getText().toUpperCase();
                            int añoe=feceve.getCalendar().get(Calendar.YEAR);
                            int mese=feceve.getCalendar().get(Calendar.MONTH)+1;
                            int diae=feceve.getCalendar().get(Calendar.DAY_OF_MONTH);
                            String dfeceve=(añoe+"/"+mese+"/"+diae);
                            String dhoreve = horeve.getText().toUpperCase();
                            String dmaruni = maruni.getText().toUpperCase();
                            String dmoduni = moduni.getText().toUpperCase();
                            String dplauni = plauni.getText().toUpperCase();
                            String dorirut = orirut.getText().toUpperCase();
                            String ddesrut = desrut.getText().toUpperCase();
                            String dnomcho = nomcho.getText().toUpperCase();
                            String dcelcho = celcho.getText().toUpperCase();
                            String ddeseve = deseve.getText().toUpperCase();
                            String dreseve = reseve.getText().toUpperCase();
                            e.Agregar(dcveemp, dnomemp, dfeceve, dhoreve, dnumuni, dmaruni, dmoduni, dplauni, dnumrut, dorirut, ddesrut,
                                      drfccho, dnomcho, dcelcho, ddeseve, dreseve, Acceso.getClaveUsuario());
                            JOptionPane.showMessageDialog(this, "Registro creado .....");
                            Iniciar();
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_crearActionPerformed

    private void actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarActionPerformed
        Event e=new Event();
        int dnumeve=Integer.parseInt(numeve.getText().toUpperCase());
        String dcveemp = cveemp.getSelectedItem().toString();
        if(dcveemp.isEmpty()){
            JOptionPane.showMessageDialog(this, "Se requiere una clave de empresa, verifique .....");
            cveemp.grabFocus();
        }
        else{
            if(feceve.getDate() == null){
                JOptionPane.showMessageDialog(this, "Se requiere la fecha del evento, verifique .....");
                feceve.grabFocus();
            }
            else{
                String dnumuni = numuni.getSelectedItem().toString();
                if(dnumuni.isEmpty()){
                    JOptionPane.showMessageDialog(this, "Se requiere un número o clave de unidad, verifique .....");
                    numuni.grabFocus();
                }
                else{
                    String dnumrut = numrut.getSelectedItem().toString();
                    if(dnumrut.isEmpty()){
                        JOptionPane.showMessageDialog(this, "Se requiere un número o clave de ruta, verifique .....");
                        numrut.grabFocus();
                    }
                    else{
                        String drfccho = rfccho.getSelectedItem().toString();
                        if(drfccho.isEmpty()){
                            JOptionPane.showMessageDialog(this, "Se requiere el rfc del chofer, verifique .....");
                            rfccho.grabFocus();
                        }
                        else{
                            String dnomemp = nomemp.getText().toUpperCase();
                            int añoe=feceve.getCalendar().get(Calendar.YEAR);
                            int mese=feceve.getCalendar().get(Calendar.MONTH)+1;
                            int diae=feceve.getCalendar().get(Calendar.DAY_OF_MONTH);
                            String dfeceve=(añoe+"/"+mese+"/"+diae);
                            String dhoreve = horeve.getText().toUpperCase();
                            String dmaruni = maruni.getText().toUpperCase();
                            String dmoduni = moduni.getText().toUpperCase();
                            String dplauni = plauni.getText().toUpperCase();
                            String dorirut = orirut.getText().toUpperCase();
                            String ddesrut = desrut.getText().toUpperCase();
                            String dnomcho = nomcho.getText().toUpperCase();
                            String dcelcho = celcho.getText().toUpperCase();
                            String ddeseve = deseve.getText().toUpperCase();
                            String dreseve = reseve.getText().toUpperCase();
                            e.Actualizar(dnumeve, dcveemp, dnomemp, dfeceve, dhoreve, dnumuni, dmaruni, dmoduni, dplauni, dnumrut, dorirut,
                                         ddesrut, drfccho, dnomcho, dcelcho, ddeseve, dreseve, Acceso.getClaveUsuario());
                            JOptionPane.showMessageDialog(this, "Registro actualizado .....");
                            Iniciar();
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_actualizarActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        Event e=new Event();
        int dnumeve=Integer.parseInt(numeve.getText().toUpperCase());
        String dcveemp = cveemp.getSelectedItem().toString();
        if(dcveemp.isEmpty()){
            JOptionPane.showMessageDialog(this, "Se requiere una clave de empresa, verifique .....");
            Iniciar();
        }
        else{
            String dnomemp = nomemp.getText().toUpperCase();
            e.Eliminar(dnumeve, dcveemp, dnomemp, Acceso.getClaveUsuario());
            JOptionPane.showMessageDialog(this, "Registro eliminado .....");
            Iniciar();
        }
    }//GEN-LAST:event_eliminarActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        Iniciar();
    }//GEN-LAST:event_cancelarActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        this.dispose();
    }//GEN-LAST:event_salirActionPerformed

    private void tablaeventMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaeventMouseClicked
        DefaultTableModel modelo= (DefaultTableModel) tablaevent.getModel();
        numeve.setText(modelo.getValueAt(tablaevent.getSelectedRow(), 0)+"");
        nomemp.setText(modelo.getValueAt(tablaevent.getSelectedRow(), 1)+"");
        String feve = (modelo.getValueAt(tablaevent.getSelectedRow(), 2)+"");
        if("null".equals(feve)){
            System.out.println("La fecha del evento esta vacia .....");
        }
        else{
            SimpleDateFormat formatofecha1=new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            try{
                Date fecha1 = formatofecha1.parse(feve);
                feceve.setDate(fecha1);
            }
            catch(ParseException pe1){
            System.out.println("Error Parse1: "+pe1.getMessage());
            }
        }
        horeve.setText(modelo.getValueAt(tablaevent.getSelectedRow(), 3)+"");
        numuni.setSelectedItem(modelo.getValueAt(tablaevent.getSelectedRow(), 4)+"");
        numrut.setSelectedItem(modelo.getValueAt(tablaevent.getSelectedRow(), 5)+"");
        deseve.setText(modelo.getValueAt(tablaevent.getSelectedRow(), 6)+"");
        fecha.setText(modelo.getValueAt(tablaevent.getSelectedRow(), 8)+"");
        usuario.setText(modelo.getValueAt(tablaevent.getSelectedRow(), 9)+"");
        crear.setEnabled(false);
        cveemp.setEnabled(false);
        
        int NumAct = Integer.parseInt(numeve.getText());
        
        Event com=new Event();
        Object[] datos=com.Comple(NumAct);
        cveemp.setSelectedItem(datos[0]+"");
        maruni.setText(datos[1]+"");
        moduni.setText(datos[2]+"");
        plauni.setText(datos[3]+"");
        orirut.setText(datos[4]+"");
        desrut.setText(datos[5]+"");
        rfccho.setSelectedItem(datos[6]+"");
        nomcho.setText(datos[7]+"");
        celcho.setText(datos[8]+"");
        reseve.setText(datos[9]+"");
    }//GEN-LAST:event_tablaeventMouseClicked

    private void cveempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cveempActionPerformed
        String claveseleccionada=cveemp.getSelectedItem()+"";
        Event e1=new Event();
        Object[] datos=e1.Datos1(claveseleccionada);
        nomemp.setText(datos[0]+"");
    }//GEN-LAST:event_cveempActionPerformed

    private void numuniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numuniActionPerformed
        String claveseleccionada=numuni.getSelectedItem()+"";
        Event e2=new Event();
        Object[] datos=e2.Datos2(claveseleccionada);
        maruni.setText(datos[0]+"");
        moduni.setText(datos[1]+"");
        plauni.setText(datos[2]+"");
    }//GEN-LAST:event_numuniActionPerformed

    private void numrutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numrutActionPerformed
        String claveseleccionada=numrut.getSelectedItem()+"";
        Event e3=new Event();
        Object[] datos=e3.Datos3(claveseleccionada);
        orirut.setText(datos[0]+"");
        desrut.setText(datos[1]+"");
    }//GEN-LAST:event_numrutActionPerformed

    private void rfcchoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rfcchoActionPerformed
        String claveseleccionada=rfccho.getSelectedItem()+"";
        Event e4=new Event();
        Object[] datos=e4.Datos4(claveseleccionada);
        nomcho.setText(datos[0]+"");
        celcho.setText(datos[1]+"");
    }//GEN-LAST:event_rfcchoActionPerformed

    private void tablaevent1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaevent1MouseClicked
        DefaultTableModel modelo= (DefaultTableModel) tablaevent1.getModel();
        numeve1.setText(modelo.getValueAt(tablaevent1.getSelectedRow(), 0)+"");
        nomemp1.setText(modelo.getValueAt(tablaevent1.getSelectedRow(), 1)+"");
        feceve1.setText(modelo.getValueAt(tablaevent1.getSelectedRow(), 2)+"");
        horeve1.setText(modelo.getValueAt(tablaevent1.getSelectedRow(), 3)+"");
        numuni1.setText(modelo.getValueAt(tablaevent1.getSelectedRow(), 4)+"");
        numrut1.setText(modelo.getValueAt(tablaevent1.getSelectedRow(), 5)+"");
        deseve1.setText(modelo.getValueAt(tablaevent1.getSelectedRow(), 6)+"");
        fecha1.setText(modelo.getValueAt(tablaevent1.getSelectedRow(), 8)+"");
        usuario1.setText(modelo.getValueAt(tablaevent1.getSelectedRow(), 9)+"");
        
        int NumAct1 = Integer.parseInt(numeve1.getText());
        
        Event com=new Event();
        Object[] datos=com.Comple(NumAct1);
        cveemp1.setText(datos[0]+"");
        maruni1.setText(datos[1]+"");
        moduni1.setText(datos[2]+"");
        plauni1.setText(datos[3]+"");
        orirut1.setText(datos[4]+"");
        desrut1.setText(datos[5]+"");
        rfccho1.setText(datos[6]+"");
        nomcho1.setText(datos[7]+"");
        celcho1.setText(datos[8]+"");
        reseve1.setText(datos[9]+"");
    }//GEN-LAST:event_tablaevent1MouseClicked

    private void busnumKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_busnumKeyPressed
        Event e=new Event();
        Limpiar(tablaevent1);
        DefaultTableModel modelo= (DefaultTableModel) tablaevent1.getModel();
        e.BusNum(modelo, busnum.getText().toUpperCase());
    }//GEN-LAST:event_busnumKeyPressed

    private void busnumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_busnumMouseClicked
        Iniciar();
    }//GEN-LAST:event_busnumMouseClicked

    private void busempKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_busempKeyPressed
        Event e=new Event();
        Limpiar(tablaevent1);
        DefaultTableModel modelo= (DefaultTableModel) tablaevent1.getModel();
        e.BusEmp(modelo, busemp.getText().toUpperCase());
    }//GEN-LAST:event_busempKeyPressed

    private void busempMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_busempMouseClicked
        Iniciar();
    }//GEN-LAST:event_busempMouseClicked

    private void busdesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_busdesKeyPressed
        Event e=new Event();
        Limpiar(tablaevent1);
        DefaultTableModel modelo= (DefaultTableModel) tablaevent1.getModel();
        e.BusDes(modelo, busdes.getText().toUpperCase());
    }//GEN-LAST:event_busdesKeyPressed

    private void busdesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_busdesMouseClicked
        Iniciar();
    }//GEN-LAST:event_busdesMouseClicked

    private void salir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salir1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_salir1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EventConsola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EventConsola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EventConsola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EventConsola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EventConsola().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizar;
    private javax.swing.JTextField busdes;
    private javax.swing.JTextField busemp;
    private javax.swing.JTextField busnum;
    private javax.swing.JButton cancelar;
    private javax.swing.JTextField celcho;
    private javax.swing.JTextField celcho1;
    private javax.swing.JButton crear;
    private javax.swing.JComboBox cveemp;
    private javax.swing.JTextField cveemp1;
    private javax.swing.JTextField deseve;
    private javax.swing.JTextField deseve1;
    private javax.swing.JTextField desrut;
    private javax.swing.JTextField desrut1;
    private javax.swing.JButton eliminar;
    private com.toedter.calendar.JDateChooser feceve;
    private javax.swing.JTextField feceve1;
    private javax.swing.JTextField fecha;
    private javax.swing.JTextField fecha1;
    private javax.swing.JTextField horeve;
    private javax.swing.JTextField horeve1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField maruni;
    private javax.swing.JTextField maruni1;
    private javax.swing.JTextField moduni;
    private javax.swing.JTextField moduni1;
    private javax.swing.JTextField nomcho;
    private javax.swing.JTextField nomcho1;
    private javax.swing.JTextField nomemp;
    private javax.swing.JTextField nomemp1;
    private javax.swing.JTextField numeve;
    private javax.swing.JTextField numeve1;
    private javax.swing.JComboBox numrut;
    private javax.swing.JTextField numrut1;
    private javax.swing.JComboBox numuni;
    private javax.swing.JTextField numuni1;
    private javax.swing.JTextField orirut;
    private javax.swing.JTextField orirut1;
    private javax.swing.JTextField plauni;
    private javax.swing.JTextField plauni1;
    private javax.swing.JTextField reseve;
    private javax.swing.JTextField reseve1;
    private javax.swing.JComboBox rfccho;
    private javax.swing.JTextField rfccho1;
    private javax.swing.JButton salir;
    private javax.swing.JButton salir1;
    private javax.swing.JTable tablaevent;
    private javax.swing.JTable tablaevent1;
    private javax.swing.JTextField txtEmpresa;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField usuario;
    private javax.swing.JTextField usuario1;
    // End of variables declaration//GEN-END:variables
}
