
package sirh;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

public class ExperAConsola extends javax.swing.JFrame {


    public ExperAConsola() {
        initComponents();
        setDefaultCloseOperation(0);
        Iniciar();
    }

    private void Limpiar(JTable tabla){
        while(tabla.getRowCount()>0){
            ((DefaultTableModel) tabla.getModel()).removeRow(0);
        }
    }
    
    private void Iniciar(){
        fecha.setText(fechaActual());
        usuario.setText(Acceso.getClaveUsuario());
        txtNombre.setText(Acceso.getNombreUsuario());
        txtEmpresa.setText(Acceso.getEmpresaUsuario());
        txtRfc.setText(TrabaA.getRfcUsuario());
        txtTrabaja.setText(TrabaA.getNomTrabaja());
        
        String RegFed = TrabaA.getRfcUsuario();
        Limpiar(tablaexper);
        DefaultTableModel modelo=(DefaultTableModel) tablaexper.getModel();
        ExperA e=new ExperA();
        e.LlenarDatos(modelo, RegFed);
        
        empresa.setText("");
        cargo.setText("");
        finicio.setDate(null);
        ftermino.setDate(null);
        causa.setText("");
        pais.removeAllItems();
        pais.addItem("");
        ExperA e1= new ExperA();
        e1.LlenarPais(pais);
        estado.removeAllItems();
        estado.addItem("");
        mundel.removeAllItems();
        mundel.addItem("");
        pobla.removeAllItems();
        pobla.addItem("");
        colonia.removeAllItems();
        colonia.addItem("");
        calle.setText("");
        codigo.setText("");
        telefono.setText("");
        jefe.setText("");
        carjefe.setText("");
        celjefe.setText("");
        corjefe.setText("");
        path.setText("C:/SIRH/EXPERIENCIA/EXPERIENCIA.GIF");
        observa.setText("");
        status.setText("");
        crear.setEnabled(true);
        cargo.setEnabled(true);
        empresa.setEnabled(true);
    }
    
    public static String fechaActual(){
        Date fecha= new Date();
        SimpleDateFormat formatoFecha=new SimpleDateFormat("dd/MM/YYYY HH:mm:ss");
        return formatoFecha.format(fecha);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaexper = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        empresa = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cargo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        finicio = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        ftermino = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        causa = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        pais = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        estado = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        mundel = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        pobla = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        colonia = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        calle = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        codigo = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        telefono = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jefe = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        carjefe = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        celjefe = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        corjefe = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        path = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        observa = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        status = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        fecha = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        crear = new javax.swing.JButton();
        actualizar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtEmpresa = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtRfc = new javax.swing.JTextField();
        txtTrabaja = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SNTIAISCRM Sistema de Recursos Humanos");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        tablaexper.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Empresa", "Cargo", "Inicio", "Término", "Causa", "Jefe", "Cargo Jefe", "Path", "Status", "Ultima Fecha", "Ultimo Usuario"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaexper.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaexperMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaexper);

        jLabel2.setForeground(new java.awt.Color(204, 0, 51));
        jLabel2.setText("Empresa:");

        jLabel3.setForeground(new java.awt.Color(204, 0, 51));
        jLabel3.setText("Cargo:");

        jLabel4.setForeground(new java.awt.Color(204, 0, 51));
        jLabel4.setText("Fec. Inicio:");

        jLabel5.setForeground(new java.awt.Color(204, 0, 51));
        jLabel5.setText("Fec. Término:");

        jLabel6.setText("Causa Separ:");

        jLabel7.setText("Dom. País:");

        pais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paisActionPerformed(evt);
            }
        });

        jLabel8.setText("Dom. Estado:");

        estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoActionPerformed(evt);
            }
        });

        jLabel9.setText("Dom. Mun-Del:");

        mundel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mundelActionPerformed(evt);
            }
        });

        jLabel10.setText("Dom. Pobla:");

        pobla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poblaActionPerformed(evt);
            }
        });

        jLabel11.setText("Dom. Colonia:");

        jLabel12.setText("Dom. Calle-No:");

        jLabel13.setText("Código Postal:");

        codigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                codigoKeyTyped(evt);
            }
        });

        jLabel14.setText("Tél. Empresa:");

        jLabel15.setText("Jefe Superior:");

        jLabel16.setText("Cargo Jefe:");

        jLabel17.setText("Celular Jefe:");

        jLabel18.setText("Correo Jefe:");

        jLabel19.setText("Path Carta Rec:");

        path.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pathMouseClicked(evt);
            }
        });

        jLabel20.setText("Observaciones:");

        jLabel21.setText("Status:");

        status.setEditable(false);

        jLabel22.setText("Fecha:");

        fecha.setEditable(false);

        jLabel23.setText("Usuario:");

        usuario.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cargo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(finicio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                            .addComponent(ftermino, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(empresa)
                            .addComponent(causa)
                            .addComponent(pais, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(estado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mundel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pobla, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(colonia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(calle))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(codigo)
                            .addComponent(telefono)
                            .addComponent(jefe)
                            .addComponent(carjefe)
                            .addComponent(celjefe)
                            .addComponent(corjefe, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(path)
                            .addComponent(observa)
                            .addComponent(status)
                            .addComponent(fecha)
                            .addComponent(usuario, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(empresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(finicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ftermino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel16)
                                .addComponent(carjefe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(causa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel17)
                            .addComponent(celjefe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(pais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18)
                            .addComponent(corjefe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel19)
                                .addComponent(path, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jefe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(mundel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel20)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pobla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(colonia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(calle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(observa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        crear.setText("Crear");
        crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearActionPerformed(evt);
            }
        });

        actualizar.setText("Actualizar");
        actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarActionPerformed(evt);
            }
        });

        eliminar.setText("Eliminar");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(288, Short.MAX_VALUE)
                .addComponent(crear)
                .addGap(18, 18, 18)
                .addComponent(actualizar)
                .addGap(18, 18, 18)
                .addComponent(eliminar)
                .addGap(18, 18, 18)
                .addComponent(cancelar)
                .addGap(18, 18, 18)
                .addComponent(salir)
                .addGap(283, 283, 283))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crear)
                    .addComponent(actualizar)
                    .addComponent(eliminar)
                    .addComponent(cancelar)
                    .addComponent(salir))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("MOVIMIENTOS DE EXPERIENCIAS (Aspirantes)");

        txtEmpresa.setEditable(false);
        txtEmpresa.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        txtEmpresa.setForeground(new java.awt.Color(204, 0, 0));
        txtEmpresa.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtEmpresa.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtNombre.setEditable(false);
        txtNombre.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(204, 0, 0));
        txtNombre.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtNombre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtRfc.setEditable(false);

        txtTrabaja.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtRfc, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTrabaja, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmpresa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRfc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTrabaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearActionPerformed
        ExperA e=new ExperA();
        String dempresa=empresa.getText().toUpperCase();
        if(dempresa.isEmpty()){
            JOptionPane.showMessageDialog(this, "Se requiere el nombre de la empresa (1), verifique .....");
            empresa.grabFocus();
        }
        else{
            if(dempresa.trim().equals("")){
                JOptionPane.showMessageDialog(this, "Se requiere el nombre de la empresa (2), verifique .....");
                empresa.setText("");
                empresa.grabFocus();
            }
            else{
                String dcargo=cargo.getText().toUpperCase();
                if(dcargo.isEmpty()){
                    JOptionPane.showMessageDialog(this, "Se requiere el cargo desempeñado (1), verifique .....");
                    cargo.grabFocus();
                }
                else{
                    if(dcargo.trim().equals("")){
                        JOptionPane.showMessageDialog(this, "Se requiere el cargo desempeñado (2), verifique .....");
                        cargo.setText("");
                        cargo.grabFocus();
                    }
                    else{
                        if(finicio.getDate() == null){
                            JOptionPane.showMessageDialog(this, "Se requiere la fecha de inicio, verifique .....");
                            finicio.grabFocus();
                        }
                        else{
                            if(ftermino.getDate() == null){
                                JOptionPane.showMessageDialog(this, "Se requiere la fecha de inicio, verifique .....");
                                ftermino.grabFocus();
                            }
                            else{
                                int añoi=finicio.getCalendar().get(Calendar.YEAR);
                                int mesi=finicio.getCalendar().get(Calendar.MONTH)+1;
                                int diai=finicio.getCalendar().get(Calendar.DAY_OF_MONTH);
                                String dfinicio=(añoi+"/"+mesi+"/"+diai);
                                int añot=ftermino.getCalendar().get(Calendar.YEAR);
                                int mest=ftermino.getCalendar().get(Calendar.MONTH)+1;
                                int diat=ftermino.getCalendar().get(Calendar.DAY_OF_MONTH);
                                String dftermino=(añot+"/"+mest+"/"+diat);
                                String dcausa=causa.getText().toUpperCase();
                                String dpais=pais.getSelectedItem().toString();
                                String destado=estado.getSelectedItem().toString();
                                String dmundel=mundel.getSelectedItem().toString();
                                String dpobla=pobla.getSelectedItem().toString();
                                String dcolonia=colonia.getSelectedItem().toString();
                                String dcalle=calle.getText().toUpperCase();
                                int dcodigo=Integer.parseInt(codigo.getText().toUpperCase());
                                String dtelefono=telefono.getText().toUpperCase();
                                String djefe=jefe.getText().toUpperCase();
                                String dcarjefe=carjefe.getText().toUpperCase();
                                String dceljefe=celjefe.getText().toUpperCase();
                                String dcorjefe=corjefe.getText().toUpperCase();
                                String dpath=path.getText().toUpperCase();
                                String dobserva=observa.getText().toUpperCase();
                                e.Agregar(TrabaA.getRfcUsuario(), dempresa, dcargo, dfinicio, dftermino, dcausa, dpais, destado, dmundel,
                                          dpobla, dcolonia, dcalle, dcodigo, dtelefono, djefe, dcarjefe, dceljefe, dcorjefe, dpath,
                                          dobserva, Acceso.getClaveUsuario());
                                JOptionPane.showMessageDialog(this, "Registro creado .....");
                                Iniciar();
                            }
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_crearActionPerformed

    private void actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarActionPerformed
        ExperA e=new ExperA();
        String dempresa=empresa.getText().toUpperCase();
        if(dempresa.isEmpty()){
            JOptionPane.showMessageDialog(this, "Se requiere el nombre de la empresa (1), verifique .....");
            empresa.grabFocus();
        }
        else{
            if(dempresa.trim().equals("")){
                JOptionPane.showMessageDialog(this, "Se requiere el nombre de la empresa (2), verifique .....");
                empresa.setText("");
                empresa.grabFocus();
            }
            else{
                String dcargo=cargo.getText().toUpperCase();
                if(dcargo.isEmpty()){
                    JOptionPane.showMessageDialog(this, "Se requiere el cargo desempeñado (1), verifique .....");
                    cargo.grabFocus();
                }
                else{
                    if(dcargo.trim().equals("")){
                        JOptionPane.showMessageDialog(this, "Se requiere el cargo desempeñado (2), verifique .....");
                        cargo.setText("");
                        cargo.grabFocus();
                    }
                    else{
                        if(finicio.getDate() == null){
                            JOptionPane.showMessageDialog(this, "Se requiere la fecha de inicio, verifique .....");
                            finicio.grabFocus();
                        }
                        else{
                            if(ftermino.getDate() == null){
                                JOptionPane.showMessageDialog(this, "Se requiere la fecha de inicio, verifique .....");
                                ftermino.grabFocus();
                            }
                            else{
                                int añoi=finicio.getCalendar().get(Calendar.YEAR);
                                int mesi=finicio.getCalendar().get(Calendar.MONTH)+1;
                                int diai=finicio.getCalendar().get(Calendar.DAY_OF_MONTH);
                                String dfinicio=(añoi+"/"+mesi+"/"+diai);
                                int añot=ftermino.getCalendar().get(Calendar.YEAR);
                                int mest=ftermino.getCalendar().get(Calendar.MONTH)+1;
                                int diat=ftermino.getCalendar().get(Calendar.DAY_OF_MONTH);
                                String dftermino=(añot+"/"+mest+"/"+diat);
                                String dcausa=causa.getText().toUpperCase();
                                String dpais=pais.getSelectedItem().toString();
                                String destado=estado.getSelectedItem().toString();
                                String dmundel=mundel.getSelectedItem().toString();
                                String dpobla=pobla.getSelectedItem().toString();
                                String dcolonia=colonia.getSelectedItem().toString();
                                String dcalle=calle.getText().toUpperCase();
                                int dcodigo=Integer.parseInt(codigo.getText().toUpperCase());
                                String dtelefono=telefono.getText().toUpperCase();
                                String djefe=jefe.getText().toUpperCase();
                                String dcarjefe=carjefe.getText().toUpperCase();
                                String dceljefe=celjefe.getText().toUpperCase();
                                String dcorjefe=corjefe.getText().toUpperCase();
                                String dpath=path.getText().toUpperCase();
                                String dobserva=observa.getText().toUpperCase();
                                e.Actualizar(TrabaA.getRfcUsuario(), dempresa, dcargo, dfinicio, dftermino, dcausa, dpais, destado, dmundel,
                                            dpobla, dcolonia, dcalle, dcodigo, dtelefono, djefe, dcarjefe, dceljefe, dcorjefe, dpath,
                                            dobserva, Acceso.getClaveUsuario());
                                JOptionPane.showMessageDialog(this, "Registro actualizado .....");
                                Iniciar();
                            }
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_actualizarActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        ExperA e=new ExperA();
        String dempresa=empresa.getText().toUpperCase();
        if(dempresa.isEmpty()){
            JOptionPane.showMessageDialog(this, "Se requiere el nombre de la empresa (1), verifique .....");
            empresa.grabFocus();
        }
        else{
            if(dempresa.trim().equals("")){
                JOptionPane.showMessageDialog(this, "Se requiere el nombre de la empresa (2), verifique .....");
                empresa.setText("");
                empresa.grabFocus();
            }
            else{
                String dcargo=cargo.getText().toUpperCase();
                if(dcargo.isEmpty()){
                    JOptionPane.showMessageDialog(this, "Se requiere el cargo desempeñado (1), verifique .....");
                    cargo.grabFocus();
                }
                else{
                    if(dcargo.trim().equals("")){
                        JOptionPane.showMessageDialog(this, "Se requiere el cargo desempeñado (2), verifique .....");
                        cargo.setText("");
                        cargo.grabFocus();
                    }
                    else{
                        e.Eliminar(TrabaA.getRfcUsuario(), dempresa, dcargo, Acceso.getClaveUsuario());
                        JOptionPane.showMessageDialog(this, "Registro eliminado .....");
                        Iniciar();
                    }
                }
            }
        }
    }//GEN-LAST:event_eliminarActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        Iniciar();
    }//GEN-LAST:event_cancelarActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        this.dispose();
    }//GEN-LAST:event_salirActionPerformed

    private void tablaexperMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaexperMouseClicked
        DefaultTableModel modelo= (DefaultTableModel) tablaexper.getModel();
        empresa.setText(modelo.getValueAt(tablaexper.getSelectedRow(), 0)+"");
        cargo.setText(modelo.getValueAt(tablaexper.getSelectedRow(), 1)+"");
        String fecini = (modelo.getValueAt(tablaexper.getSelectedRow(), 2)+"");
        if("null".equals(fecini)){
            System.out.println("La fecha de inicio esta vacia .....");
        }
        else{
            SimpleDateFormat formatofecha1=new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            try{
                Date fecha1 = formatofecha1.parse(fecini);
                finicio.setDate(fecha1);
            }
            catch(ParseException pe1){
            System.out.println("Error Parse1: "+pe1.getMessage());
            }
        }
        String fecter = (modelo.getValueAt(tablaexper.getSelectedRow(), 3)+"");
        if("null".equals(fecter)){
            System.out.println("La fecha de inicio esta vacia .....");
        }
        else{
            SimpleDateFormat formatofecha1=new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            try{
                Date fecha1 = formatofecha1.parse(fecter);
                ftermino.setDate(fecha1);
            }
            catch(ParseException pe1){
            System.out.println("Error Parse1: "+pe1.getMessage());
            }
        }
        causa.setText(modelo.getValueAt(tablaexper.getSelectedRow(), 4)+"");
        jefe.setText(modelo.getValueAt(tablaexper.getSelectedRow(), 5)+"");
        carjefe.setText(modelo.getValueAt(tablaexper.getSelectedRow(), 6)+"");
        path.setText(modelo.getValueAt(tablaexper.getSelectedRow(), 7)+"");
        status.setText(modelo.getValueAt(tablaexper.getSelectedRow(), 8)+"");
        fecha.setText(modelo.getValueAt(tablaexper.getSelectedRow(), 9)+"");
        usuario.setText(modelo.getValueAt(tablaexper.getSelectedRow(), 10)+"");
        
        String RegFed = TrabaA.getRfcUsuario();
        String EmAc = empresa.getText();
        String CaAc = cargo.getText();
        
        ExperA com=new ExperA();
        Object[] datos1=com.Comple(RegFed, EmAc, CaAc);
        pais.setSelectedItem(datos1[0]+"");
        estado.setSelectedItem(datos1[1]+"");
        mundel.setSelectedItem(datos1[2]+"");
        pobla.setSelectedItem(datos1[3]+"");
        colonia.setSelectedItem(datos1[4]+"");
        calle.setText(datos1[5]+"");
        codigo.setText(datos1[6]+"");
        telefono.setText(datos1[7]+"");
        celjefe.setText(datos1[8]+"");
        corjefe.setText(datos1[9]+"");
        observa.setText(datos1[10]+"");
        crear.setEnabled(false);
        cargo.setEnabled(false);
        empresa.setEnabled(false);
    }//GEN-LAST:event_tablaexperMouseClicked

    private void paisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paisActionPerformed
        estado.removeAllItems();
        estado.addItem("");
        mundel.removeAllItems();
        mundel.addItem("");
        pobla.removeAllItems();
        pobla.addItem("");
        colonia.removeAllItems();
        colonia.addItem("");
        String paiseleccionado=pais.getSelectedItem()+"";
        ExperA e2=new ExperA();
        e2.LlenarEstado(estado, paiseleccionado);
    }//GEN-LAST:event_paisActionPerformed

    private void estadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadoActionPerformed
        mundel.removeAllItems();
        mundel.addItem("");
        pobla.removeAllItems();
        pobla.addItem("");
        colonia.removeAllItems();
        colonia.addItem("");
        String paiseleccionado=pais.getSelectedItem()+"";
        String edoseleccionado=estado.getSelectedItem()+"";
        ExperA e3=new ExperA();
        e3.LlenarMundel(mundel, paiseleccionado, edoseleccionado);
    }//GEN-LAST:event_estadoActionPerformed

    private void mundelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mundelActionPerformed
        pobla.removeAllItems();
        pobla.addItem("");
        colonia.removeAllItems();
        colonia.addItem("");
        String paiseleccionado=pais.getSelectedItem()+"";
        String edoseleccionado=estado.getSelectedItem()+"";
        String mundelseleccionado=mundel.getSelectedItem()+"";
        ExperA e4=new ExperA();
        e4.LlenarPobla(pobla, paiseleccionado, edoseleccionado, mundelseleccionado);
    }//GEN-LAST:event_mundelActionPerformed

    private void poblaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poblaActionPerformed
        colonia.removeAllItems();
        colonia.addItem("");
        String paiseleccionado=pais.getSelectedItem()+"";
        String edoseleccionado=estado.getSelectedItem()+"";
        String mundelseleccionado=mundel.getSelectedItem()+"";
        String poblaseleccionado=pobla.getSelectedItem()+"";
        ExperA e5=new ExperA();
        e5.LlenarColonia(colonia, paiseleccionado, edoseleccionado, mundelseleccionado, poblaseleccionado);
    }//GEN-LAST:event_poblaActionPerformed

    private void pathMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pathMouseClicked
        ExperA.setPathUsuario(path.getText().toUpperCase());
        VExperAConsola object=new VExperAConsola();
        object.setVisible(true);
    }//GEN-LAST:event_pathMouseClicked

    private void codigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codigoKeyTyped
        char car = evt.getKeyChar();
        if((car<'0' || car>'9')) evt.consume();
    }//GEN-LAST:event_codigoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExperAConsola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExperAConsola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExperAConsola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExperAConsola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExperAConsola().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizar;
    private javax.swing.JTextField calle;
    private javax.swing.JButton cancelar;
    private javax.swing.JTextField cargo;
    private javax.swing.JTextField carjefe;
    private javax.swing.JTextField causa;
    private javax.swing.JTextField celjefe;
    private javax.swing.JTextField codigo;
    private javax.swing.JComboBox colonia;
    private javax.swing.JTextField corjefe;
    private javax.swing.JButton crear;
    private javax.swing.JButton eliminar;
    private javax.swing.JTextField empresa;
    private javax.swing.JComboBox estado;
    private javax.swing.JTextField fecha;
    private com.toedter.calendar.JDateChooser finicio;
    private com.toedter.calendar.JDateChooser ftermino;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jefe;
    private javax.swing.JComboBox mundel;
    private javax.swing.JTextField observa;
    private javax.swing.JComboBox pais;
    private javax.swing.JTextField path;
    private javax.swing.JComboBox pobla;
    private javax.swing.JButton salir;
    private javax.swing.JTextField status;
    private javax.swing.JTable tablaexper;
    private javax.swing.JTextField telefono;
    private javax.swing.JTextField txtEmpresa;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRfc;
    private javax.swing.JTextField txtTrabaja;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
