
package sirh;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

public class FamilConsola extends javax.swing.JFrame {


    public FamilConsola() {
        initComponents();
        setDefaultCloseOperation(0);
        Iniciar();
    }

    private void Limpiar(JTable tabla){
        while(tabla.getRowCount()>0){
            ((DefaultTableModel) tabla.getModel()).removeRow(0);
        }
    }
    
    private void Iniciar(){
        fecha.setText(fechaActual());
        usuario.setText(Acceso.getClaveUsuario());
        txtNombre.setText(Acceso.getNombreUsuario());
        txtEmpresa.setText(Acceso.getEmpresaUsuario());
        txtNumero.setText(String.valueOf(Traba.getNumTrabaja()));
        txtTrabaja.setText(Traba.getNomTrabaja());
        
        int NumTra = Traba.getNumTrabaja();
        Limpiar(tablafamil);
        DefaultTableModel modelo=(DefaultTableModel) tablafamil.getModel();
        Famil e=new Famil();
        e.LlenarDatos(modelo, NumTra);
        
        tipo.removeAllItems();
        tipo.addItem("");
        Famil e1=new Famil();
        e1.LlenarTipo(tipo);
        paterno.setText("");
        materno.setText("");
        nombre.setText("");
        vive.removeAllItems();
        vive.addItem("");
        Famil e2=new Famil();
        e2.LlenarSino(vive);
        sexo.removeAllItems();
        sexo.addItem("");
        Famil e3=new Famil();
        e3.LlenarSexo(sexo);
        fnacim.setDate(null);
        ocupa.setText("");
        pais.removeAllItems();
        pais.addItem("");
        Famil e4= new Famil();
        e4.LlenarPais(pais);
        estado.removeAllItems();
        estado.addItem("");
        mundel.removeAllItems();
        mundel.addItem("");
        pobla.removeAllItems();
        pobla.addItem("");
        colonia.removeAllItems();
        colonia.addItem("");
        calle.setText("");
        codigo.setText("");
        telefono.setText("");
        celular.setText("");
        correo.setText("");
        tidoc.removeAllItems();
        tidoc.addItem("");
        Famil e5=new Famil();
        e5.LlenarTidoc(tidoc);
        path.setText("C:/SIRH/FAMILIA/FAMILIA.GIF");
        observa.setText("");
        status.setText("");
        crear.setEnabled(true);
        paterno.setEnabled(true);
        materno.setEnabled(true);
        nombre.setEnabled(true);
    }
    
    public static String fechaActual(){
        Date fecha= new Date();
        SimpleDateFormat formatoFecha=new SimpleDateFormat("dd/MM/YYYY HH:mm:ss");
        return formatoFecha.format(fecha);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablafamil = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        tipo = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        paterno = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        materno = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        vive = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        fnacim = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        ocupa = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        pais = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        estado = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        mundel = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        pobla = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        colonia = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        calle = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        telefono = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        celular = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        tidoc = new javax.swing.JComboBox();
        jLabel19 = new javax.swing.JLabel();
        correo = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        path = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        observa = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        status = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        fecha = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();
        sexo = new javax.swing.JComboBox();
        jLabel25 = new javax.swing.JLabel();
        codigo = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        crear = new javax.swing.JButton();
        actualizar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtEmpresa = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        txtTrabaja = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SNTIAISCRM Sistema de Recursos Humanos");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        tablafamil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Parentesco", "Paterno", "Materno", "Nombre", "Vive", "Género", "Fec. Nacim.", "Tipo Docto.", "Path Docto.", "Status", "Ultima Fecha", "Ultimo Usuario"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablafamil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablafamilMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablafamil);

        jLabel2.setText("Parentesco:");

        jLabel3.setForeground(new java.awt.Color(204, 0, 51));
        jLabel3.setText("Paterno:");

        jLabel4.setForeground(new java.awt.Color(204, 0, 51));
        jLabel4.setText("Materno:");

        jLabel5.setForeground(new java.awt.Color(204, 0, 51));
        jLabel5.setText("Nombre:");

        jLabel6.setText("Vive:");

        jLabel7.setForeground(new java.awt.Color(204, 0, 51));
        jLabel7.setText("Fecha Nacim:");

        jLabel8.setText("Género::");

        jLabel9.setText("Dom. País:");

        pais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paisActionPerformed(evt);
            }
        });

        jLabel10.setText("Dom. Estado:");

        estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoActionPerformed(evt);
            }
        });

        jLabel11.setText("Dom. Mun-Del:");

        mundel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mundelActionPerformed(evt);
            }
        });

        jLabel12.setText("Dom. Pobla:");

        pobla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poblaActionPerformed(evt);
            }
        });

        jLabel13.setText("Dom. Colonia:");

        jLabel14.setText("Dom. Calle-No:");

        jLabel15.setText("Código Post:");

        jLabel16.setText("Teléfono:");

        jLabel17.setText("Celular:");

        jLabel18.setText("Correo:");

        jLabel19.setText("Docto. Tipo:");

        jLabel20.setText("Path Docto:");

        path.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pathMouseClicked(evt);
            }
        });

        jLabel21.setText("Observa:");

        jLabel22.setText("Status::");

        status.setEditable(false);

        jLabel23.setText("Fecha:");

        fecha.setEditable(false);

        jLabel24.setText("Usuario:");

        usuario.setEditable(false);

        jLabel25.setText("Ocupación:");

        codigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                codigoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 958, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(paterno)
                            .addComponent(materno)
                            .addComponent(nombre)
                            .addComponent(vive, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fnacim, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(pais, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(estado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mundel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pobla, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(colonia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(calle)
                            .addComponent(sexo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(codigo)
                            .addComponent(telefono)
                            .addComponent(celular)
                            .addComponent(tidoc, 0, 323, Short.MAX_VALUE)
                            .addComponent(correo)
                            .addComponent(path)
                            .addComponent(observa)
                            .addComponent(status)
                            .addComponent(fecha)
                            .addComponent(usuario)
                            .addComponent(ocupa))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15)
                        .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(paterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(ocupa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(materno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(celular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(vive, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(fnacim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tidoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel19)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(path, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel20)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(observa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(mundel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(pobla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(colonia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(calle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        crear.setText("Crear");
        crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearActionPerformed(evt);
            }
        });

        actualizar.setText("Actualizar");
        actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarActionPerformed(evt);
            }
        });

        eliminar.setText("Eliminar");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(283, 283, 283)
                .addComponent(crear)
                .addGap(18, 18, 18)
                .addComponent(actualizar)
                .addGap(18, 18, 18)
                .addComponent(eliminar)
                .addGap(18, 18, 18)
                .addComponent(cancelar)
                .addGap(18, 18, 18)
                .addComponent(salir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crear)
                    .addComponent(actualizar)
                    .addComponent(eliminar)
                    .addComponent(cancelar)
                    .addComponent(salir))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("MOVIMIENTOS DE FAMILIARES (Trabajadores)");

        txtEmpresa.setEditable(false);
        txtEmpresa.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        txtEmpresa.setForeground(new java.awt.Color(204, 0, 0));
        txtEmpresa.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtEmpresa.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtNombre.setEditable(false);
        txtNombre.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(204, 0, 0));
        txtNombre.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtNombre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtNumero.setEditable(false);

        txtTrabaja.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTrabaja, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmpresa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTrabaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearActionPerformed
        Famil e=new Famil();
        String dtipo=tipo.getSelectedItem().toString();
        String dpaterno=paterno.getText().toUpperCase();
        if(dpaterno.isEmpty()){
            JOptionPane.showMessageDialog(this, "Se requiere un apellido paterno (1), verifique .....");
            tipo.grabFocus();
        }
        else{
            if(dpaterno.trim().equals("")){
                JOptionPane.showMessageDialog(this, "Se requiere un apellido paterno (2), verifique .....");
                paterno.setText("");
                paterno.grabFocus();
            }
            else{
                String dmaterno=materno.getText().toUpperCase();
                if(dmaterno.isEmpty()){
                    JOptionPane.showMessageDialog(this, "Se requiere un apellido materno (1), verifique .....");
                    materno.grabFocus();
                }
                else{
                    if(dmaterno.trim().equals("")){
                        JOptionPane.showMessageDialog(this, "Se requiere un apellido materno (2), verifique .....");
                        materno.setText("");
                        materno.grabFocus();
                    }
                    else{
                        String dnombre=nombre.getText().toUpperCase();
                        if(dnombre.isEmpty()){
                            JOptionPane.showMessageDialog(this, "Se requiere un nombre (1), verifique .....");
                            nombre.grabFocus();
                        }
                        else{
                            if(dnombre.trim().equals("")){
                                JOptionPane.showMessageDialog(this, "Se requiere un nombre (2), verifique .....");
                                nombre.setText("");
                                nombre.grabFocus();
                            }
                            else{
                                if(fnacim.getDate() == null){
                                    JOptionPane.showMessageDialog(this, "Se requiere la fecha de nacimiento, verifique .....");
                                    fnacim.grabFocus();
                                }
                                else{
                                    String dvive=vive.getSelectedItem().toString();
                                    String dsexo=sexo.getSelectedItem().toString();
                                    int añoi=fnacim.getCalendar().get(Calendar.YEAR);
                                    int mesi=fnacim.getCalendar().get(Calendar.MONTH)+1;
                                    int diai=fnacim.getCalendar().get(Calendar.DAY_OF_MONTH);
                                    String dfnacim=(añoi+"/"+mesi+"/"+diai);
                                    String docupa=ocupa.getText().toUpperCase();
                                    String dpais=pais.getSelectedItem().toString();
                                    String destado=estado.getSelectedItem().toString();
                                    String dmundel=mundel.getSelectedItem().toString();
                                    String dpobla=pobla.getSelectedItem().toString();
                                    String dcolonia=colonia.getSelectedItem().toString();
                                    String dcalle=calle.getText().toUpperCase();
                                    int dcodigo=Integer.parseInt(codigo.getText().toUpperCase());
                                    String dtelefono=telefono.getText().toUpperCase();
                                    String dcelular=celular.getText().toUpperCase();
                                    String dcorreo=correo.getText().toUpperCase();
                                    String dtidoc=tidoc.getSelectedItem().toString();
                                    String dpath=path.getText().toUpperCase();
                                    String dobserva=observa.getText().toUpperCase();
                                    e.Agregar(Traba.getNumTrabaja(), dtipo, dpaterno, dmaterno, dnombre, dvive, dsexo, dfnacim, docupa,
                                              dpais, destado, dmundel, dpobla, dcolonia, dcalle, dcodigo, dtelefono, dcelular, dcorreo,
                                              dtidoc, dpath, dobserva, Acceso.getClaveUsuario());
                                    JOptionPane.showMessageDialog(this, "Registro creado .....");
                                    Iniciar();
                                }
                            }
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_crearActionPerformed

    private void actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarActionPerformed
        Famil e=new Famil();
        String dtipo=tipo.getSelectedItem().toString();
        String dpaterno=paterno.getText().toUpperCase();
        if(dpaterno.isEmpty()){
            JOptionPane.showMessageDialog(this, "Se requiere un apellido paterno (1), verifique .....");
            tipo.grabFocus();
        }
        else{
            if(dpaterno.trim().equals("")){
                JOptionPane.showMessageDialog(this, "Se requiere un apellido paterno (2), verifique .....");
                paterno.setText("");
                paterno.grabFocus();
            }
            else{
                String dmaterno=materno.getText().toUpperCase();
                if(dmaterno.isEmpty()){
                    JOptionPane.showMessageDialog(this, "Se requiere un apellido materno (1), verifique .....");
                    materno.grabFocus();
                }
                else{
                    if(dmaterno.trim().equals("")){
                        JOptionPane.showMessageDialog(this, "Se requiere un apellido materno (2), verifique .....");
                        materno.setText("");
                        materno.grabFocus();
                    }
                    else{
                        String dnombre=nombre.getText().toUpperCase();
                        if(dnombre.isEmpty()){
                            JOptionPane.showMessageDialog(this, "Se requiere un nombre (1), verifique .....");
                            nombre.grabFocus();
                        }
                        else{
                            if(dnombre.trim().equals("")){
                                JOptionPane.showMessageDialog(this, "Se requiere un nombre (2), verifique .....");
                                nombre.setText("");
                                nombre.grabFocus();
                            }
                            else{
                                if(fnacim.getDate() == null){
                                    JOptionPane.showMessageDialog(this, "Se requiere la fecha de nacimiento, verifique .....");
                                    fnacim.grabFocus();
                                }
                                else{
                                    String dvive=vive.getSelectedItem().toString();
                                    String dsexo=sexo.getSelectedItem().toString();
                                    int añoi=fnacim.getCalendar().get(Calendar.YEAR);
                                    int mesi=fnacim.getCalendar().get(Calendar.MONTH)+1;
                                    int diai=fnacim.getCalendar().get(Calendar.DAY_OF_MONTH);
                                    String dfnacim=(añoi+"/"+mesi+"/"+diai);
                                    String docupa=ocupa.getText().toUpperCase();
                                    String dpais=pais.getSelectedItem().toString();
                                    String destado=estado.getSelectedItem().toString();
                                    String dmundel=mundel.getSelectedItem().toString();
                                    String dpobla=pobla.getSelectedItem().toString();
                                    String dcolonia=colonia.getSelectedItem().toString();
                                    String dcalle=calle.getText().toUpperCase();
                                    int dcodigo=Integer.parseInt(codigo.getText().toUpperCase());
                                    String dtelefono=telefono.getText().toUpperCase();
                                    String dcelular=celular.getText().toUpperCase();
                                    String dcorreo=correo.getText().toUpperCase();
                                    String dtidoc=tidoc.getSelectedItem().toString();
                                    String dpath=path.getText().toUpperCase();
                                    String dobserva=observa.getText().toUpperCase();
                                    e.Actualizar(Traba.getNumTrabaja(), dtipo, dpaterno, dmaterno, dnombre, dvive, dsexo, dfnacim, docupa,
                                                 dpais, destado, dmundel, dpobla, dcolonia, dcalle, dcodigo, dtelefono, dcelular, dcorreo,
                                                 dtidoc, dpath, dobserva, Acceso.getClaveUsuario());
                                    JOptionPane.showMessageDialog(this, "Registro actualizado .....");
                                    Iniciar();
                                }
                            }
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_actualizarActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        Famil e=new Famil();
        String dpaterno=paterno.getText().toUpperCase();
        if(dpaterno.isEmpty()){
            JOptionPane.showMessageDialog(this, "Se requiere un apellido paterno (1), verifique .....");
            tipo.grabFocus();
        }
        else{
            if(dpaterno.trim().equals("")){
                JOptionPane.showMessageDialog(this, "Se requiere un apellido paterno (2), verifique .....");
                paterno.setText("");
                paterno.grabFocus();
            }
            else{
                String dmaterno=materno.getText().toUpperCase();
                if(dmaterno.isEmpty()){
                    JOptionPane.showMessageDialog(this, "Se requiere un apellido materno (1), verifique .....");
                    materno.grabFocus();
                }
                else{
                    if(dmaterno.trim().equals("")){
                        JOptionPane.showMessageDialog(this, "Se requiere un apellido materno (2), verifique .....");
                        materno.setText("");
                        materno.grabFocus();
                    }
                    else{
                        String dnombre=nombre.getText().toUpperCase();
                        if(dnombre.isEmpty()){
                            JOptionPane.showMessageDialog(this, "Se requiere un nombre (1), verifique .....");
                            nombre.grabFocus();
                        }
                        else{
                            if(dnombre.trim().equals("")){
                                JOptionPane.showMessageDialog(this, "Se requiere un nombre (2), verifique .....");
                                nombre.setText("");
                                nombre.grabFocus();
                            }
                            else{
                                e.Eliminar(Traba.getNumTrabaja(), dpaterno, dmaterno, dnombre, Acceso.getClaveUsuario());
                                JOptionPane.showMessageDialog(this, "Registro eliminado .....");
                                Iniciar();
                            }
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_eliminarActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        Iniciar();
    }//GEN-LAST:event_cancelarActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        this.dispose();
    }//GEN-LAST:event_salirActionPerformed

    private void tablafamilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablafamilMouseClicked
        DefaultTableModel modelo= (DefaultTableModel) tablafamil.getModel();
        tipo.setSelectedItem(modelo.getValueAt(tablafamil.getSelectedRow(), 0)+"");
        paterno.setText(modelo.getValueAt(tablafamil.getSelectedRow(), 1)+"");
        materno.setText(modelo.getValueAt(tablafamil.getSelectedRow(), 2)+"");
        nombre.setText(modelo.getValueAt(tablafamil.getSelectedRow(), 3)+"");
        vive.setSelectedItem(modelo.getValueAt(tablafamil.getSelectedRow(), 4)+"");
        sexo.setSelectedItem(modelo.getValueAt(tablafamil.getSelectedRow(), 5)+"");
        String fecnac = (modelo.getValueAt(tablafamil.getSelectedRow(), 6)+"");
        if("null".equals(fecnac)){
            System.out.println("La fecha de nacimiento esta vacia .....");
        }
        else{
            SimpleDateFormat formatofecha1=new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            try{
                Date fecha1 = formatofecha1.parse(fecnac);
                fnacim.setDate(fecha1);
            }
            catch(ParseException pe1){
            System.out.println("Error Parse1: "+pe1.getMessage());
            }
        }
        tidoc.setSelectedItem(modelo.getValueAt(tablafamil.getSelectedRow(), 7)+"");
        path.setText(modelo.getValueAt(tablafamil.getSelectedRow(), 8)+"");
        status.setText(modelo.getValueAt(tablafamil.getSelectedRow(), 9)+"");
        fecha.setText(modelo.getValueAt(tablafamil.getSelectedRow(), 10)+"");
        usuario.setText(modelo.getValueAt(tablafamil.getSelectedRow(), 11)+"");
        
        int NumTra = Traba.getNumTrabaja();
        String ApPat = paterno.getText();
        String ApMat = materno.getText();
        String ApNo = nombre.getText();
        
        Famil com=new Famil();
        Object[] datos1=com.Comple(NumTra, ApPat, ApMat, ApNo);
        ocupa.setText(datos1[0]+"");
        pais.setSelectedItem(datos1[1]+"");
        estado.setSelectedItem(datos1[2]+"");
        mundel.setSelectedItem(datos1[3]+"");
        pobla.setSelectedItem(datos1[4]+"");
        colonia.setSelectedItem(datos1[5]+"");
        calle.setText(datos1[6]+"");
        codigo.setText(datos1[7]+"");
        telefono.setText(datos1[8]+"");
        celular.setText(datos1[9]+"");
        correo.setText(datos1[10]+"");
        observa.setText(datos1[11]+"");
        crear.setEnabled(false);
        paterno.setEnabled(false);
        materno.setEnabled(false);
        nombre.setEnabled(false);
    }//GEN-LAST:event_tablafamilMouseClicked

    private void pathMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pathMouseClicked
        Famil.setPathUsuario(path.getText().toUpperCase());
        VFamilConsola object=new VFamilConsola();
        object.setVisible(true);
    }//GEN-LAST:event_pathMouseClicked

    private void paisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paisActionPerformed
        estado.removeAllItems();
        estado.addItem("");
        mundel.removeAllItems();
        mundel.addItem("");
        pobla.removeAllItems();
        pobla.addItem("");
        colonia.removeAllItems();
        colonia.addItem("");
        String paiseleccionado=pais.getSelectedItem()+"";
        Famil e2=new Famil();
        e2.LlenarEstado(estado, paiseleccionado);
    }//GEN-LAST:event_paisActionPerformed

    private void estadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadoActionPerformed
        mundel.removeAllItems();
        mundel.addItem("");
        pobla.removeAllItems();
        pobla.addItem("");
        colonia.removeAllItems();
        colonia.addItem("");
        String paiseleccionado=pais.getSelectedItem()+"";
        String edoseleccionado=estado.getSelectedItem()+"";
        Famil e3=new Famil();
        e3.LlenarMundel(mundel, paiseleccionado, edoseleccionado);
    }//GEN-LAST:event_estadoActionPerformed

    private void mundelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mundelActionPerformed
        pobla.removeAllItems();
        pobla.addItem("");
        colonia.removeAllItems();
        colonia.addItem("");
        String paiseleccionado=pais.getSelectedItem()+"";
        String edoseleccionado=estado.getSelectedItem()+"";
        String mundelseleccionado=mundel.getSelectedItem()+"";
        Famil e4=new Famil();
        e4.LlenarPobla(pobla, paiseleccionado, edoseleccionado, mundelseleccionado);
    }//GEN-LAST:event_mundelActionPerformed

    private void poblaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poblaActionPerformed
        colonia.removeAllItems();
        colonia.addItem("");
        String paiseleccionado=pais.getSelectedItem()+"";
        String edoseleccionado=estado.getSelectedItem()+"";
        String mundelseleccionado=mundel.getSelectedItem()+"";
        String poblaseleccionado=pobla.getSelectedItem()+"";
        Famil e5=new Famil();
        e5.LlenarColonia(colonia, paiseleccionado, edoseleccionado, mundelseleccionado, poblaseleccionado);
    }//GEN-LAST:event_poblaActionPerformed

    private void codigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codigoKeyTyped
        char car = evt.getKeyChar();
        if((car<'0' || car>'9')) evt.consume();
    }//GEN-LAST:event_codigoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FamilConsola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FamilConsola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FamilConsola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FamilConsola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FamilConsola().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizar;
    private javax.swing.JTextField calle;
    private javax.swing.JButton cancelar;
    private javax.swing.JTextField celular;
    private javax.swing.JTextField codigo;
    private javax.swing.JComboBox colonia;
    private javax.swing.JTextField correo;
    private javax.swing.JButton crear;
    private javax.swing.JButton eliminar;
    private javax.swing.JComboBox estado;
    private javax.swing.JTextField fecha;
    private com.toedter.calendar.JDateChooser fnacim;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField materno;
    private javax.swing.JComboBox mundel;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField observa;
    private javax.swing.JTextField ocupa;
    private javax.swing.JComboBox pais;
    private javax.swing.JTextField paterno;
    private javax.swing.JTextField path;
    private javax.swing.JComboBox pobla;
    private javax.swing.JButton salir;
    private javax.swing.JComboBox sexo;
    private javax.swing.JTextField status;
    private javax.swing.JTable tablafamil;
    private javax.swing.JTextField telefono;
    private javax.swing.JComboBox tidoc;
    private javax.swing.JComboBox tipo;
    private javax.swing.JTextField txtEmpresa;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtTrabaja;
    private javax.swing.JTextField usuario;
    private javax.swing.JComboBox vive;
    // End of variables declaration//GEN-END:variables
}
