
package sirh;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

public class InvenConsola extends javax.swing.JFrame {


    public InvenConsola() {
        initComponents();
        setDefaultCloseOperation(0);
        dispon.setVisible(false);
        Iniciar();
    }
    
    private void Limpiar(JTable tabla){
        while(tabla.getRowCount()>0){
            ((DefaultTableModel) tabla.getModel()).removeRow(0);
        }
    }
    
    private void Iniciar(){
        txtNombre.setText(Acceso.getNombreUsuario());
        txtEmpresa.setText("AUTOS TOLUCA");
        //txtEmpresa.setText(Acceso.getEmpresaUsuario());
        
        Limpiar(tablainven1);
        DefaultTableModel modelo1=(DefaultTableModel) tablainven1.getModel();
        Inven e1=new Inven();
        e1.LlenarDatos1(modelo1, txtEmpresa.getText());
        cveemp1.removeAllItems();
        cveemp1.addItem("");
        Inven e2=new Inven();
        e2.LlenarCveempresa(cveemp1);
        nomemp1.setText("");
        fecmov1.setDate(null);
        mod1.setText("");
        talla1.setText("");
        cant1.setText("");
        Limpiar(tablainven2);
        DefaultTableModel modelo2=(DefaultTableModel) tablainven2.getModel();
        Inven e3=new Inven();
        e3.LlenarDatos2(modelo2, txtEmpresa.getText());
        cveemp2.removeAllItems();
        cveemp2.addItem("");
        Inven e4=new Inven();
        e4.LlenarCveempresa(cveemp2);
        nomemp2.setText("");
        mod2.setText("");
        talla2.setText("");
        numtra.removeAllItems();
        numtra.addItem("0");
        Inven e5=new Inven();
        e5.LlenarCvetrabajador(numtra);
        nomtra.setText("");
        cant2.setText("");
        fecmov2.setDate(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtEmpresa = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        salidas = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cveemp1 = new javax.swing.JComboBox();
        nomemp1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        fecmov1 = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        art1 = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        mod1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        talla1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cant1 = new javax.swing.JTextField();
        crear1 = new javax.swing.JButton();
        eliminar1 = new javax.swing.JButton();
        cancelar1 = new javax.swing.JButton();
        salir1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablainven1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablainven2 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        nomemp2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        mod2 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        talla2 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        nomtra = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        cant2 = new javax.swing.JTextField();
        crear2 = new javax.swing.JButton();
        eliminar2 = new javax.swing.JButton();
        cancelar2 = new javax.swing.JButton();
        salir2 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        fecmov2 = new com.toedter.calendar.JDateChooser();
        cveemp2 = new javax.swing.JComboBox();
        art2 = new javax.swing.JComboBox();
        numtra = new javax.swing.JComboBox();
        dispon = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SNTIAISCRM Sistema de Recursos Humanos");
        setMaximumSize(new java.awt.Dimension(800, 460));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("MOVIMIENTOS DE INVENTARIOS");

        txtEmpresa.setEditable(false);
        txtEmpresa.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        txtEmpresa.setForeground(new java.awt.Color(204, 0, 0));
        txtEmpresa.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtEmpresa.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtNombre.setEditable(false);
        txtNombre.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(204, 0, 0));
        txtNombre.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtNombre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        salidas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salidasMouseClicked(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(204, 0, 51));
        jLabel2.setText("Empresa:");

        cveemp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cveemp1ActionPerformed(evt);
            }
        });

        nomemp1.setEditable(false);

        jLabel4.setForeground(new java.awt.Color(204, 0, 51));
        jLabel4.setText("Fecha Entrada:");

        jLabel6.setText("Artículo:");

        art1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CAMISA", "PANTALON", "ZAPATOS" }));

        jLabel7.setText("Modelo:");

        jLabel8.setText("Talla:");

        jLabel9.setForeground(new java.awt.Color(204, 0, 51));
        jLabel9.setText("Cantidad:");

        cant1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cant1KeyTyped(evt);
            }
        });

        crear1.setText("Crear");
        crear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crear1ActionPerformed(evt);
            }
        });

        eliminar1.setText("Eliminar");
        eliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminar1ActionPerformed(evt);
            }
        });

        cancelar1.setText("Cancelar");
        cancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelar1ActionPerformed(evt);
            }
        });

        salir1.setText("Salir");
        salir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salir1ActionPerformed(evt);
            }
        });

        tablainven1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cve Empresa", "Empresa", "Fecha Entrada", "Articulo", "Modelo", "Talla", "Cantidad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablainven1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablainven1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablainven1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 755, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(29, 29, 29))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(mod1, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
                                        .addComponent(talla1)
                                        .addComponent(cant1)
                                        .addComponent(art1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(fecmov1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cveemp1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(nomemp1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(61, 61, 61)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cancelar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(salir1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(crear1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(eliminar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(77, 77, 77))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomemp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cveemp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(crear1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fecmov1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(eliminar1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(art1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cancelar1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mod1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(salir1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(talla1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cant1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)))
                .addGap(193, 193, 193))
        );

        salidas.addTab("Entradas", jPanel1);

        tablainven2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cve Empresa", "Empresa", "Fecha Salida", "Artículo", "Modelo", "Talla", "Cantidad", "Num Trabajador", "Nombre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablainven2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablainven2MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablainven2);

        jLabel10.setForeground(new java.awt.Color(204, 0, 51));
        jLabel10.setText("Empresa:");

        nomemp2.setEditable(false);

        jLabel12.setForeground(new java.awt.Color(204, 0, 51));
        jLabel12.setText("Artículo:");

        jLabel13.setForeground(new java.awt.Color(204, 0, 51));
        jLabel13.setText("Modelo:");

        jLabel14.setForeground(new java.awt.Color(204, 0, 51));
        jLabel14.setText("Talla:");

        jLabel15.setForeground(new java.awt.Color(204, 0, 51));
        jLabel15.setText("Num Trabajador:");

        nomtra.setEditable(false);

        jLabel16.setForeground(new java.awt.Color(204, 0, 51));
        jLabel16.setText("Cantidad:");

        cant2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cant2KeyTyped(evt);
            }
        });

        crear2.setText("Crear");
        crear2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crear2ActionPerformed(evt);
            }
        });

        eliminar2.setText("Elimnar");
        eliminar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminar2ActionPerformed(evt);
            }
        });

        cancelar2.setText("Cancelar");
        cancelar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelar2ActionPerformed(evt);
            }
        });

        salir2.setText("Salir");
        salir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salir2ActionPerformed(evt);
            }
        });

        jLabel17.setForeground(new java.awt.Color(204, 0, 51));
        jLabel17.setText("Fecha:");

        cveemp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cveemp2ActionPerformed(evt);
            }
        });

        art2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CAMISA", "PANTALON", "ZAPATOS" }));

        numtra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numtraActionPerformed(evt);
            }
        });

        dispon.setEditable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 755, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(cveemp2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nomemp2, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(cant2)
                                    .addComponent(numtra, 0, 96, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(fecmov2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(nomtra)))
                            .addComponent(art2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mod2)
                            .addComponent(talla2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(salir2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(dispon)
                                .addComponent(eliminar2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cancelar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(crear2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(73, 73, 73))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(crear2)
                    .addComponent(nomemp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cveemp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eliminar2)
                    .addComponent(jLabel12)
                    .addComponent(art2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelar2)
                    .addComponent(mod2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salir2)
                    .addComponent(talla2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomtra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(numtra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dispon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cant2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16)
                        .addComponent(jLabel17))
                    .addComponent(fecmov2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        salidas.addTab("Salidas", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(salidas)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(salidas, javax.swing.GroupLayout.PREFERRED_SIZE, 375, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crear1ActionPerformed
        Inven e=new Inven();
        String dcveemp1 = cveemp1.getSelectedItem().toString();
        if(dcveemp1.isEmpty()){
            JOptionPane.showMessageDialog(this, "Se requiere una clave de empresa, verifique .....");
            Iniciar();
        }
        else{
            if(fecmov1.getDate() == null){
                JOptionPane.showMessageDialog(this, "Se requiere la fecha de la entrada, verifique .....");
                fecmov1.grabFocus();
            }
            else{
                String dk=cant1.getText();
                if("".equals(dk) || "0".equals(dk)){
                    JOptionPane.showMessageDialog(this, "Se requiere una cantidad, verifique .....");
                    cant1.setText("");
                    cant1.grabFocus();
                }
                else{
                    int dcant1=Integer.parseInt(cant1.getText());
                    if(dcant1==0){
                        JOptionPane.showMessageDialog(this, "Se requiere una cantidad, verifique .....");
                        cant1.setText("");
                        cant1.grabFocus();
                    }
                    else{
                        String dnomemp1=nomemp1.getText().toUpperCase();
                        int año1=fecmov1.getCalendar().get(Calendar.YEAR);
                        int mes1=fecmov1.getCalendar().get(Calendar.MONTH)+1;
                        int dia1=fecmov1.getCalendar().get(Calendar.DAY_OF_MONTH);
                        String dfecmov1=(año1+"/"+mes1+"/"+dia1);
                        String dtipmov1="ENTRADA";
                        String dart1 = art1.getSelectedItem().toString();
                        String dmod1=mod1.getText().toUpperCase();
                        String dtalla1=talla1.getText().toUpperCase();
                        int dnumtra = 0;
                        String dnomtra = "";
                        e.Agregar1(dcveemp1, dnomemp1, dfecmov1, dtipmov1, dart1, dmod1, dtalla1, dcant1, dnumtra, dnomtra, Acceso.getClaveUsuario());
                        JOptionPane.showMessageDialog(this, "Registro creado .....");
                        Iniciar();
                    }
                }
            }
        } 
    }//GEN-LAST:event_crear1ActionPerformed

    private void eliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminar1ActionPerformed
        Inven e=new Inven();
        String dcveemp1 = cveemp1.getSelectedItem().toString();
        if(dcveemp1.isEmpty()){
            JOptionPane.showMessageDialog(this, "Se requiere una clave de empresa, verifique .....");
            Iniciar();
        }
        else{
            if(fecmov1.getDate() == null){
                JOptionPane.showMessageDialog(this, "Se requiere la fecha de la entrada, verifique .....");
                fecmov1.grabFocus();
            }
            else{
                String dk=cant1.getText();
                if("".equals(dk) || "0".equals(dk)){
                    JOptionPane.showMessageDialog(this, "Se requiere una cantidad, verifique .....");
                    cant1.setText("");
                    cant1.grabFocus();
                }
                else{
                    int dcant1=Integer.parseInt(cant1.getText());
                    if(dcant1==0){
                        JOptionPane.showMessageDialog(this, "Se requiere una cantidad, verifique .....");
                        cant1.setText("");
                        cant1.grabFocus();
                    }
                    else{
                        int año1=fecmov1.getCalendar().get(Calendar.YEAR);
                        int mes1=fecmov1.getCalendar().get(Calendar.MONTH)+1;
                        int dia1=fecmov1.getCalendar().get(Calendar.DAY_OF_MONTH);
                        String dfecmov1=(año1+"/"+mes1+"/"+dia1);
                        String dtipmov1="ENTRADA";
                        String dart1 = art1.getSelectedItem().toString();
                        String dmod1=mod1.getText().toUpperCase();
                        String dtalla1=talla1.getText().toUpperCase();
                        e.Eliminar1(dcveemp1, dfecmov1, dtipmov1, dart1, dmod1, dtalla1, dcant1, Acceso.getClaveUsuario());
                        JOptionPane.showMessageDialog(this, "Registro eliminado .....");
                        Iniciar();
                    }
                }
            }
        }
    }//GEN-LAST:event_eliminar1ActionPerformed

    private void cancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelar1ActionPerformed
        Iniciar();
    }//GEN-LAST:event_cancelar1ActionPerformed

    private void salir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salir1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_salir1ActionPerformed

    private void cant1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cant1KeyTyped
        char car = evt.getKeyChar();
        if(car<'0' || car>'9') 
        {
            evt.consume();
        }
    }//GEN-LAST:event_cant1KeyTyped

    private void cveemp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cveemp1ActionPerformed
        String claveseleccionada=cveemp1.getSelectedItem()+"";
        Inven e=new Inven();
        Object[] datos1=e.Datos1(claveseleccionada);
        nomemp1.setText(datos1[0]+"");
    }//GEN-LAST:event_cveemp1ActionPerformed

    private void tablainven1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablainven1MouseClicked
        DefaultTableModel modelo1= (DefaultTableModel) tablainven1.getModel();
        cveemp1.setSelectedItem(modelo1.getValueAt(tablainven1.getSelectedRow(), 0)+"");
        nomemp1.setText(modelo1.getValueAt(tablainven1.getSelectedRow(), 1)+"");
        String fm1 = (modelo1.getValueAt(tablainven1.getSelectedRow(), 2)+"");
        if("null".equals(fm1)){
            System.out.println("La fecha de entrada esta vacia .....");
        }
        else{
            SimpleDateFormat formatofecha1=new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            try{
                Date fecha1 = formatofecha1.parse(fm1);
                fecmov1.setDate(fecha1);
            }
            catch(ParseException pe1){
            System.out.println("Error Parse1: "+pe1.getMessage());
            }
        }
        art1.setSelectedItem(modelo1.getValueAt(tablainven1.getSelectedRow(), 3)+"");
        mod1.setText(modelo1.getValueAt(tablainven1.getSelectedRow(), 4)+"");
        talla1.setText(modelo1.getValueAt(tablainven1.getSelectedRow(), 5)+"");
        cant1.setText(modelo1.getValueAt(tablainven1.getSelectedRow(), 6)+"");
    }//GEN-LAST:event_tablainven1MouseClicked

    private void crear2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crear2ActionPerformed
        String dcveemp2 = cveemp2.getSelectedItem().toString();
        int dnumtra=Integer.parseInt(numtra.getSelectedItem().toString());
        if(dcveemp2.isEmpty() || dnumtra == 0){
            JOptionPane.showMessageDialog(this, "Se requiere una clave de empresa y un número de trabajador, verifique .....");
            Iniciar();
        }
        else{
            if(fecmov2.getDate() == null){
                JOptionPane.showMessageDialog(this, "Se requiere la fecha de salida, verifique .....");
                fecmov2.grabFocus();
            }
            else{
                String dk=cant2.getText();
                if("".equals(dk) || "0".equals(dk)){
                    JOptionPane.showMessageDialog(this, "Se requiere una cantidad, verifique .....");
                    cant2.setText("");
                    cant2.grabFocus();
                }
                else{
                    int dcant2=Integer.parseInt(cant2.getText());
                    int dcant2x=dcant2*(-1);
                    if(dcant2==0){
                        JOptionPane.showMessageDialog(this, "Se requiere una cantidad, verifique .....");
                        cant2.setText("");
                        cant2.grabFocus();
                    }
                    else{
                        String dmod2=mod2.getText().toUpperCase();
                        String dtalla2=talla2.getText().toUpperCase();
                        if("".equals(dmod2) || "".equals(dtalla2)){
                            JOptionPane.showMessageDialog(this, "Falta el modelo y/o la talla, verifique .....");
                            mod2.grabFocus();
                        }
                        else{
                            String dnomemp2=nomemp2.getText().toUpperCase();
                            int año1=fecmov2.getCalendar().get(Calendar.YEAR);
                            int mes1=fecmov2.getCalendar().get(Calendar.MONTH)+1;
                            int dia1=fecmov2.getCalendar().get(Calendar.DAY_OF_MONTH);
                            String dfecmov2=(año1+"/"+mes1+"/"+dia1);
                            String dtipmov2="SALIDA";
                            String dart2 = art2.getSelectedItem().toString();
                            System.out.println("dart2: "+dart2);
                            int dart21 = 0;
                            switch(dart2){
                                case "CAMISA":
                                    dart21 =1;
                                    break;
                                case "PANTALON":
                                    dart21 = 2;
                                    break;
                                case "ZAPATOS":
                                    dart21 = 3;
                                    break;
                            }
                            String dnomtra = nomtra.getText().toUpperCase();
                            Inven e1=new Inven();
                            Object[] datos3=e1.Datos3(dcveemp2, dart2, dmod2, dtalla2);
                            dispon.setText(datos3[0]+"");
                            if(dispon.getText().trim().equals("null")){
                                JOptionPane.showMessageDialog(this, "No existe este artículo en inventarios, verifique .....");
                                Iniciar();
                            }
                            else{
                                int disponx = Integer.parseInt(dispon.getText());
                                if(disponx <= 0){
                                    JOptionPane.showMessageDialog(this, "No existe disponibilidad de este artículo en inventarios, verifique .....");
                                    Iniciar();
                                }
                                else{
                                    Inven e2=new Inven();
                                    e2.Agregar1(dcveemp2, dnomemp2, dfecmov2, dtipmov2, dart2, dmod2, dtalla2, dcant2x, dnumtra, dnomtra, Acceso.getClaveUsuario());
                                    Inven e3=new Inven();
                                    e3.ActCrear(dnumtra, dart21, dtalla2, dfecmov2, dcant2, Acceso.getClaveUsuario());
                                    JOptionPane.showMessageDialog(this, "Registro creado .....");
                                    Iniciar();
                                }
                            }
                        }
                    }
                }
            }
        } 
    }//GEN-LAST:event_crear2ActionPerformed

    private void eliminar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminar2ActionPerformed
        String dcveemp2 = cveemp2.getSelectedItem().toString();
        int dnumtra=Integer.parseInt(numtra.getSelectedItem().toString());
        if(dcveemp2.isEmpty() || dnumtra == 0){
            JOptionPane.showMessageDialog(this, "Se requiere una clave de empresa y un número de trabajador, verifique .....");
            Iniciar();
        }
        else{
            if(fecmov2.getDate() == null){
                JOptionPane.showMessageDialog(this, "Se requiere la fecha de salida, verifique .....");
                fecmov2.grabFocus();
            }
            else{
                String dk=cant2.getText();
                if("".equals(dk) || "0".equals(dk)){
                    JOptionPane.showMessageDialog(this, "Se requiere una cantidad, verifique .....");
                    cant2.setText("");
                    cant2.grabFocus();
                }
                else{
                    int dcant2=Integer.parseInt(cant2.getText());
                    int dcant2x=dcant2*(-1);
                    if(dcant2==0){
                        JOptionPane.showMessageDialog(this, "Se requiere una cantidad, verifique .....");
                        cant2.setText("");
                        cant2.grabFocus();
                    }
                    else{
                        String dmod2=mod2.getText().toUpperCase();
                        String dtalla2=talla2.getText().toUpperCase();
                        if("".equals(dmod2) || "".equals(dtalla2)){
                            JOptionPane.showMessageDialog(this, "Falta el modelo y/o la talla, verifique .....");
                            mod2.grabFocus();
                        }
                        else{
                            int año2=fecmov2.getCalendar().get(Calendar.YEAR);
                            int mes2=fecmov2.getCalendar().get(Calendar.MONTH)+1;
                            int dia2=fecmov2.getCalendar().get(Calendar.DAY_OF_MONTH);
                            String dfecmov2=(año2+"/"+mes2+"/"+dia2);
                            String dtipmov2="SALIDA";
                            String dart2 = art2.getSelectedItem().toString();
                            System.out.println("dart2: "+dart2);
                            int dart21 = 0;
                            switch(dart2){
                                case "CAMISA":
                                    dart21 =1;
                                    break;
                                case "PANTALON":
                                    dart21 = 2;
                                    break;
                                case "ZAPATOS":
                                    dart21 = 3;
                                    break;
                            }
                            System.out.println("dart21: "+dart21);
                            Inven e=new Inven();
                            e.Eliminar2(dcveemp2, dfecmov2, dtipmov2, dart2, dmod2, dtalla2, dcant2, dnumtra, Acceso.getClaveUsuario());
                            Inven e2=new Inven();
                            e2.ActEliminar(dnumtra, dart21, dtalla2, dfecmov2, dcant2x, Acceso.getClaveUsuario());
                            JOptionPane.showMessageDialog(this, "Registro eliminado .....");
                            Iniciar();
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_eliminar2ActionPerformed

    private void cancelar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelar2ActionPerformed
        Iniciar();
    }//GEN-LAST:event_cancelar2ActionPerformed

    private void salir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salir2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_salir2ActionPerformed

    private void salidasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salidasMouseClicked
        // NO SE UTILIZA
    }//GEN-LAST:event_salidasMouseClicked

    private void cveemp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cveemp2ActionPerformed
        String claveseleccionada=cveemp2.getSelectedItem()+"";
        Inven e=new Inven();
        Object[] datos1=e.Datos1(claveseleccionada);
        nomemp2.setText(datos1[0]+"");
    }//GEN-LAST:event_cveemp2ActionPerformed

    private void numtraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numtraActionPerformed
        try{
            int dnumtra=Integer.parseInt(numtra.getSelectedItem().toString());
            Inven e=new Inven();
            Object[] datos2=e.Datos2(dnumtra);
            nomtra.setText(datos2[0]+"");
        }
        catch (Exception ex){
            System.out.println("Exception: "+ex.getMessage());
        }
    }//GEN-LAST:event_numtraActionPerformed

    private void tablainven2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablainven2MouseClicked
        DefaultTableModel modelo2= (DefaultTableModel) tablainven2.getModel();
        cveemp2.setSelectedItem(modelo2.getValueAt(tablainven2.getSelectedRow(), 0)+"");
        nomemp2.setText(modelo2.getValueAt(tablainven2.getSelectedRow(), 1)+"");
        String fm2 = (modelo2.getValueAt(tablainven2.getSelectedRow(), 2)+"");
        if("null".equals(fm2)){
            System.out.println("La fecha de entrada esta vacia .....");
        }
        else{
            SimpleDateFormat formatofecha2=new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            try{
                Date fecha2 = formatofecha2.parse(fm2);
                fecmov2.setDate(fecha2);
            }
            catch(ParseException pe2){
            System.out.println("Error Parse2: "+pe2.getMessage());
            }
        }
        art2.setSelectedItem(modelo2.getValueAt(tablainven2.getSelectedRow(), 3)+"");
        mod2.setText(modelo2.getValueAt(tablainven2.getSelectedRow(), 4)+"");
        talla2.setText(modelo2.getValueAt(tablainven2.getSelectedRow(), 5)+"");
        cant2.setText(modelo2.getValueAt(tablainven2.getSelectedRow(), 6)+"");
        numtra.setSelectedItem(modelo2.getValueAt(tablainven2.getSelectedRow(), 7)+"");
        nomtra.setText(modelo2.getValueAt(tablainven2.getSelectedRow(), 8)+"");
    }//GEN-LAST:event_tablainven2MouseClicked

    private void cant2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cant2KeyTyped
        char car = evt.getKeyChar();
        if(car<'0' || car>'9')
        {
            evt.consume();
        }
    }//GEN-LAST:event_cant2KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InvenConsola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InvenConsola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InvenConsola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InvenConsola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InvenConsola().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox art1;
    private javax.swing.JComboBox art2;
    private javax.swing.JButton cancelar1;
    private javax.swing.JButton cancelar2;
    private javax.swing.JTextField cant1;
    private javax.swing.JTextField cant2;
    private javax.swing.JButton crear1;
    private javax.swing.JButton crear2;
    private javax.swing.JComboBox cveemp1;
    private javax.swing.JComboBox cveemp2;
    private javax.swing.JTextField dispon;
    private javax.swing.JButton eliminar1;
    private javax.swing.JButton eliminar2;
    private com.toedter.calendar.JDateChooser fecmov1;
    private com.toedter.calendar.JDateChooser fecmov2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField mod1;
    private javax.swing.JTextField mod2;
    private javax.swing.JTextField nomemp1;
    private javax.swing.JTextField nomemp2;
    private javax.swing.JTextField nomtra;
    private javax.swing.JComboBox numtra;
    private javax.swing.JTabbedPane salidas;
    private javax.swing.JButton salir1;
    private javax.swing.JButton salir2;
    private javax.swing.JTable tablainven1;
    private javax.swing.JTable tablainven2;
    private javax.swing.JTextField talla1;
    private javax.swing.JTextField talla2;
    private javax.swing.JTextField txtEmpresa;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
