
package sirh;

import java.awt.Desktop;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import java.net.*;
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;


public class Menu extends javax.swing.JFrame {


    public Menu() throws MalformedURLException {
        initComponents();
        setSize(800, 640);
        setResizable(false);
        setDefaultCloseOperation(0);
        setLocationRelativeTo(null);
        txtNombre.setText(Acceso.getNombreUsuario());
        txtEmpresa.setText(Acceso.getEmpresaUsuario());
        String lugarImagen="ftp://sirh.dyndns.org/Logo4b.png";
        Image icon= new javax.swing.ImageIcon(new URL(lugarImagen)).getImage().getScaledInstance(jLabel2.getWidth(), jLabel2.getWidth(), Image.SCALE_DEFAULT);
        Icon imagen=new ImageIcon(icon);
        jLabel2.setIcon(imagen);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JLabel();
        txtEmpresa = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuCatalogos = new javax.swing.JMenu();
        mnuCateg = new javax.swing.JMenuItem();
        mnuRazon = new javax.swing.JMenuItem();
        mnuDepar = new javax.swing.JMenuItem();
        mnuEmpre = new javax.swing.JMenuItem();
        mnuEspec = new javax.swing.JMenuItem();
        mnuCivil = new javax.swing.JMenuItem();
        mnuComit = new javax.swing.JMenuItem();
        mnuNacio = new javax.swing.JMenuItem();
        mnuEstud = new javax.swing.JMenuItem();
        mnuRelig = new javax.swing.JMenuItem();
        mnuSexoo = new javax.swing.JMenuItem();
        mnuStcon = new javax.swing.JMenuItem();
        mnuStrab = new javax.swing.JMenuItem();
        mnuTapri = new javax.swing.JMenuItem();
        mnuTicon = new javax.swing.JMenuItem();
        mnuTidoc = new javax.swing.JMenuItem();
        mnuTipar = new javax.swing.JMenuItem();
        mnuTipyp = new javax.swing.JMenuItem();
        mnuSangr = new javax.swing.JMenuItem();
        mnuTurno = new javax.swing.JMenuItem();
        mnuUbica = new javax.swing.JMenuItem();
        mnuUsuar = new javax.swing.JMenuItem();
        mnuAspirantes = new javax.swing.JMenu();
        mnuConsAspira = new javax.swing.JMenuItem();
        mnuMovsAspira = new javax.swing.JMenuItem();
        mnuTrabajadores = new javax.swing.JMenu();
        mnuConsTraba = new javax.swing.JMenuItem();
        mnuMovsTraba = new javax.swing.JMenuItem();
        mnuContratos = new javax.swing.JMenu();
        mnuConsContr = new javax.swing.JMenuItem();
        mnuMovsContr = new javax.swing.JMenuItem();
        mnuProcesos = new javax.swing.JMenu();
        mnuAspirTraba = new javax.swing.JMenuItem();
        mnuReportes = new javax.swing.JMenu();
        mnuInventarios = new javax.swing.JMenu();
        mnuEntInv = new javax.swing.JMenuItem();
        mnuSalInv = new javax.swing.JMenuItem();
        mnuExisInv = new javax.swing.JMenuItem();
        mnuMovInv = new javax.swing.JMenuItem();
        mnuInformacion = new javax.swing.JMenu();
        mnuTiinf = new javax.swing.JMenuItem();
        mnucInfor = new javax.swing.JMenuItem();
        mnuInfor = new javax.swing.JMenuItem();
        mnuTransporte = new javax.swing.JMenu();
        mnuChofe = new javax.swing.JMenuItem();
        mnuRutas = new javax.swing.JMenuItem();
        mnuUnida = new javax.swing.JMenuItem();
        mnuEvent = new javax.swing.JMenuItem();
        mnuAyuda = new javax.swing.JMenu();
        mnuAypdf = new javax.swing.JMenuItem();
        mnuSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SNTIAISCRM Sistema de Recursos Humanos");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("  ¡¡   B  I  E  N  V  E  N  I  D  O   !!");

        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sirh/LogoSirh.png"))); // NOI18N

        txtNombre.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        txtEmpresa.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        txtEmpresa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        mnuCatalogos.setText("Catálogos");

        mnuCateg.setText("Categorías");
        mnuCateg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCategActionPerformed(evt);
            }
        });
        mnuCatalogos.add(mnuCateg);

        mnuRazon.setText("Razones s/Docto");
        mnuRazon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRazonActionPerformed(evt);
            }
        });
        mnuCatalogos.add(mnuRazon);

        mnuDepar.setText("Departamentos");
        mnuDepar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDeparActionPerformed(evt);
            }
        });
        mnuCatalogos.add(mnuDepar);

        mnuEmpre.setText("Empresas");
        mnuEmpre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEmpreActionPerformed(evt);
            }
        });
        mnuCatalogos.add(mnuEmpre);

        mnuEspec.setText("Especialidades");
        mnuEspec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEspecActionPerformed(evt);
            }
        });
        mnuCatalogos.add(mnuEspec);

        mnuCivil.setText("Estados Civiles");
        mnuCivil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCivilActionPerformed(evt);
            }
        });
        mnuCatalogos.add(mnuCivil);

        mnuComit.setText("Miembros Comité");
        mnuComit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuComitActionPerformed(evt);
            }
        });
        mnuCatalogos.add(mnuComit);

        mnuNacio.setText("Nacionalidades");
        mnuNacio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuNacioActionPerformed(evt);
            }
        });
        mnuCatalogos.add(mnuNacio);

        mnuEstud.setText("Nivel Estudios");
        mnuEstud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEstudActionPerformed(evt);
            }
        });
        mnuCatalogos.add(mnuEstud);

        mnuRelig.setText("Religiones");
        mnuRelig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuReligActionPerformed(evt);
            }
        });
        mnuCatalogos.add(mnuRelig);

        mnuSexoo.setText("Géneros");
        mnuSexoo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSexooActionPerformed(evt);
            }
        });
        mnuCatalogos.add(mnuSexoo);

        mnuStcon.setText("Status Contratos");
        mnuStcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuStconActionPerformed(evt);
            }
        });
        mnuCatalogos.add(mnuStcon);

        mnuStrab.setText("Status Trabajadores");
        mnuStrab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuStrabActionPerformed(evt);
            }
        });
        mnuCatalogos.add(mnuStrab);

        mnuTapri.setText("Tipos APRIV");
        mnuTapri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTapriActionPerformed(evt);
            }
        });
        mnuCatalogos.add(mnuTapri);

        mnuTicon.setText("Tipos Contratos");
        mnuTicon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTiconActionPerformed(evt);
            }
        });
        mnuCatalogos.add(mnuTicon);

        mnuTidoc.setText("Tipos Documentos");
        mnuTidoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTidocActionPerformed(evt);
            }
        });
        mnuCatalogos.add(mnuTidoc);

        mnuTipar.setText("Tipos Parientes");
        mnuTipar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTiparActionPerformed(evt);
            }
        });
        mnuCatalogos.add(mnuTipar);

        mnuTipyp.setText("Tipos Premios/Prest");
        mnuTipyp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTipypActionPerformed(evt);
            }
        });
        mnuCatalogos.add(mnuTipyp);

        mnuSangr.setText("Tipos Sangre");
        mnuSangr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSangrActionPerformed(evt);
            }
        });
        mnuCatalogos.add(mnuSangr);

        mnuTurno.setText("Tipos Turnos");
        mnuTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTurnoActionPerformed(evt);
            }
        });
        mnuCatalogos.add(mnuTurno);

        mnuUbica.setText("Ubicaciones");
        mnuUbica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuUbicaActionPerformed(evt);
            }
        });
        mnuCatalogos.add(mnuUbica);

        mnuUsuar.setText("Usuarios");
        mnuUsuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuUsuarActionPerformed(evt);
            }
        });
        mnuCatalogos.add(mnuUsuar);

        jMenuBar1.add(mnuCatalogos);

        mnuAspirantes.setText("Aspirantes");

        mnuConsAspira.setText("Consultas");
        mnuConsAspira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuConsAspiraActionPerformed(evt);
            }
        });
        mnuAspirantes.add(mnuConsAspira);

        mnuMovsAspira.setText("Movimientos");
        mnuMovsAspira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMovsAspiraActionPerformed(evt);
            }
        });
        mnuAspirantes.add(mnuMovsAspira);

        jMenuBar1.add(mnuAspirantes);

        mnuTrabajadores.setText("Trabajadores");

        mnuConsTraba.setText("Consultas");
        mnuConsTraba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuConsTrabaActionPerformed(evt);
            }
        });
        mnuTrabajadores.add(mnuConsTraba);

        mnuMovsTraba.setText("Movimientos");
        mnuMovsTraba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMovsTrabaActionPerformed(evt);
            }
        });
        mnuTrabajadores.add(mnuMovsTraba);

        jMenuBar1.add(mnuTrabajadores);

        mnuContratos.setText("Contratos");

        mnuConsContr.setText("Consultas");
        mnuConsContr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuConsContrActionPerformed(evt);
            }
        });
        mnuContratos.add(mnuConsContr);

        mnuMovsContr.setText("Movimientos");
        mnuMovsContr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMovsContrActionPerformed(evt);
            }
        });
        mnuContratos.add(mnuMovsContr);

        jMenuBar1.add(mnuContratos);

        mnuProcesos.setText("Procesos");

        mnuAspirTraba.setText("Aspirante a Trabajador");
        mnuAspirTraba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAspirTrabaActionPerformed(evt);
            }
        });
        mnuProcesos.add(mnuAspirTraba);

        jMenuBar1.add(mnuProcesos);

        mnuReportes.setText("Reportes");
        mnuReportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuReportesMouseClicked(evt);
            }
        });
        mnuReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuReportesActionPerformed(evt);
            }
        });
        jMenuBar1.add(mnuReportes);

        mnuInventarios.setText("Inventarios");

        mnuEntInv.setText("Consulta Entradas");
        mnuEntInv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEntInvActionPerformed(evt);
            }
        });
        mnuInventarios.add(mnuEntInv);

        mnuSalInv.setText("Consulta Salidas");
        mnuSalInv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSalInvActionPerformed(evt);
            }
        });
        mnuInventarios.add(mnuSalInv);

        mnuExisInv.setText("Consulta Existencias");
        mnuExisInv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuExisInvActionPerformed(evt);
            }
        });
        mnuInventarios.add(mnuExisInv);

        mnuMovInv.setText("Movimientos");
        mnuMovInv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMovInvActionPerformed(evt);
            }
        });
        mnuInventarios.add(mnuMovInv);

        jMenuBar1.add(mnuInventarios);

        mnuInformacion.setText("Información");
        mnuInformacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuInformacionActionPerformed(evt);
            }
        });

        mnuTiinf.setText("Catálogo de Tipos de Información");
        mnuTiinf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTiinfActionPerformed(evt);
            }
        });
        mnuInformacion.add(mnuTiinf);

        mnucInfor.setText("Búsqueda de Información");
        mnucInfor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnucInforActionPerformed(evt);
            }
        });
        mnuInformacion.add(mnucInfor);

        mnuInfor.setText("Movimientos de Información");
        mnuInfor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuInforActionPerformed(evt);
            }
        });
        mnuInformacion.add(mnuInfor);

        jMenuBar1.add(mnuInformacion);

        mnuTransporte.setText("Transporte");

        mnuChofe.setText("Choferes");
        mnuChofe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuChofeActionPerformed(evt);
            }
        });
        mnuTransporte.add(mnuChofe);

        mnuRutas.setText("Rutas");
        mnuRutas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRutasActionPerformed(evt);
            }
        });
        mnuTransporte.add(mnuRutas);

        mnuUnida.setText("Unidades");
        mnuUnida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuUnidaActionPerformed(evt);
            }
        });
        mnuTransporte.add(mnuUnida);

        mnuEvent.setText("Eventos");
        mnuEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEventActionPerformed(evt);
            }
        });
        mnuTransporte.add(mnuEvent);

        jMenuBar1.add(mnuTransporte);

        mnuAyuda.setText("Ayuda");

        mnuAypdf.setText("Ayuda PDF");
        mnuAypdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAypdfActionPerformed(evt);
            }
        });
        mnuAyuda.add(mnuAypdf);

        jMenuBar1.add(mnuAyuda);

        mnuSalir.setText("Salir");
        mnuSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuSalirMouseClicked(evt);
            }
        });
        mnuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSalirActionPerformed(evt);
            }
        });
        jMenuBar1.add(mnuSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(223, 223, 223)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(222, 222, 222)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 213, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(386, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(66, 66, 66)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    private void mnuReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuReportesActionPerformed
        //
    }//GEN-LAST:event_mnuReportesActionPerformed

    private void mnuCategActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCategActionPerformed
        CategConsola object=new CategConsola();
        object.setSize(700, 500);
        object.setResizable(false);
        object.setLocationRelativeTo(null);
        object.setVisible(true);
    }//GEN-LAST:event_mnuCategActionPerformed

    private void mnuRazonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRazonActionPerformed
        RazonConsola object=new RazonConsola();
        object.setSize(700, 430);
        object.setResizable(false);
        object.setLocationRelativeTo(null);
        object.setVisible(true);
    }//GEN-LAST:event_mnuRazonActionPerformed

    private void mnuReportesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuReportesMouseClicked
        //
    }//GEN-LAST:event_mnuReportesMouseClicked

    private void mnuDeparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDeparActionPerformed
        DeparConsola object=new DeparConsola();
        object.setSize(900, 470);
        object.setResizable(false);
        object.setLocationRelativeTo(null);
        object.setVisible(true);
    }//GEN-LAST:event_mnuDeparActionPerformed

    private void mnuEmpreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEmpreActionPerformed
        EmpreConsola object=new EmpreConsola();
        object.setSize(1000, 470);
        object.setResizable(false);
        object.setLocationRelativeTo(null);
        object.setVisible(true);
    }//GEN-LAST:event_mnuEmpreActionPerformed

    private void mnuEspecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEspecActionPerformed
        EspecConsola object=new EspecConsola();
        object.setSize(700, 450);
        object.setResizable(false);
        object.setLocationRelativeTo(null);
        object.setVisible(true);
    }//GEN-LAST:event_mnuEspecActionPerformed

    private void mnuCivilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCivilActionPerformed
        CivilConsola object=new CivilConsola();
        object.setSize(700, 450);
        object.setResizable(false);
        object.setLocationRelativeTo(null);
        object.setVisible(true);
    }//GEN-LAST:event_mnuCivilActionPerformed

    private void mnuComitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuComitActionPerformed
        ComitConsola object=new ComitConsola();
        object.setSize(900, 450);
        object.setResizable(false);
        object.setLocationRelativeTo(null);
        object.setVisible(true);
    }//GEN-LAST:event_mnuComitActionPerformed

    private void mnuNacioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuNacioActionPerformed
        NacioConsola object=new NacioConsola();
        object.setSize(700, 450);
        object.setResizable(false);
        object.setLocationRelativeTo(null);
        object.setVisible(true);
    }//GEN-LAST:event_mnuNacioActionPerformed

    private void mnuReligActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuReligActionPerformed
        ReligConsola object=new ReligConsola();
        object.setSize(700, 450);
        object.setResizable(false);
        object.setLocationRelativeTo(null);
        object.setVisible(true);
    }//GEN-LAST:event_mnuReligActionPerformed

    private void mnuSexooActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSexooActionPerformed
        SexoConsola object=new SexoConsola();
        object.setSize(600, 420);
        object.setResizable(false);
        object.setLocationRelativeTo(null);
        object.setVisible(true);
    }//GEN-LAST:event_mnuSexooActionPerformed

    private void mnuStconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuStconActionPerformed
        StconConsola object=new StconConsola();
        object.setSize(600, 420);
        object.setResizable(false);
        object.setLocationRelativeTo(null);
        object.setVisible(true);
    }//GEN-LAST:event_mnuStconActionPerformed

    private void mnuStrabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuStrabActionPerformed
        StrabConsola object=new StrabConsola();
        object.setSize(700, 420);
        object.setResizable(false);
        object.setLocationRelativeTo(null);
        object.setVisible(true);
    }//GEN-LAST:event_mnuStrabActionPerformed

    private void mnuTapriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTapriActionPerformed
        TapriConsola object=new TapriConsola();
        object.setSize(600, 420);
        object.setResizable(false);
        object.setLocationRelativeTo(null);
        object.setVisible(true);
    }//GEN-LAST:event_mnuTapriActionPerformed

    private void mnuTiconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTiconActionPerformed
        TiconConsola object=new TiconConsola();
        object.setSize(600, 420);
        object.setResizable(false);
        object.setLocationRelativeTo(null);
        object.setVisible(true);
    }//GEN-LAST:event_mnuTiconActionPerformed

    private void mnuTidocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTidocActionPerformed
        TidocConsola object=new TidocConsola();
        object.setSize(600, 420);
        object.setResizable(false);
        object.setLocationRelativeTo(null);
        object.setVisible(true);
    }//GEN-LAST:event_mnuTidocActionPerformed

    private void mnuTiparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTiparActionPerformed
        TiparConsola object=new TiparConsola();
        object.setSize(600, 420);
        object.setResizable(false);
        object.setLocationRelativeTo(null);
        object.setVisible(true);
    }//GEN-LAST:event_mnuTiparActionPerformed

    private void mnuTipypActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTipypActionPerformed
        TipypConsola object=new TipypConsola();
        object.setSize(800, 420);
        object.setResizable(false);
        object.setLocationRelativeTo(null);
        object.setVisible(true);
    }//GEN-LAST:event_mnuTipypActionPerformed

    private void mnuSangrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSangrActionPerformed
        SangrConsola object=new SangrConsola();
        object.setSize(600, 420);
        object.setResizable(false);
        object.setLocationRelativeTo(null);
        object.setVisible(true);
    }//GEN-LAST:event_mnuSangrActionPerformed

    private void mnuTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTurnoActionPerformed
        TurnoConsola object=new TurnoConsola();
        object.setSize(600, 420);
        object.setResizable(false);
        object.setLocationRelativeTo(null);
        object.setVisible(true);
    }//GEN-LAST:event_mnuTurnoActionPerformed

    private void mnuUbicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuUbicaActionPerformed
        UbicaConsola object=new UbicaConsola();
        object.setSize(800, 530);
        object.setResizable(false);
        object.setLocationRelativeTo(null);
        object.setVisible(true);
    }//GEN-LAST:event_mnuUbicaActionPerformed

    private void mnuUsuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuUsuarActionPerformed
        UsuarConsola object=new UsuarConsola();
        object.setSize(800, 450);
        object.setResizable(false);
        object.setLocationRelativeTo(null);
        object.setVisible(true);
    }//GEN-LAST:event_mnuUsuarActionPerformed

    private void mnuEstudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEstudActionPerformed
        EstudConsola object=new EstudConsola();
        object.setSize(600, 420);
        object.setResizable(false);
        object.setLocationRelativeTo(null);
        object.setVisible(true);
    }//GEN-LAST:event_mnuEstudActionPerformed

    private void mnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalirActionPerformed
        //NO SIRVE
    }//GEN-LAST:event_mnuSalirActionPerformed

    private void mnuSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuSalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_mnuSalirMouseClicked

    private void mnuConsAspiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuConsAspiraActionPerformed
        try {
            cTrabaAConsola object=new cTrabaAConsola();
            object.setSize(1000,650);
            object.setResizable(false);
            object.setVisible(true);
        } catch (MalformedURLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mnuConsAspiraActionPerformed

    private void mnuMovsAspiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMovsAspiraActionPerformed
        try {
            TrabaAConsola object=new TrabaAConsola();
            object.setSize(760,540);
            object.setResizable(false);
            object.setVisible(true);
        } catch (MalformedURLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mnuMovsAspiraActionPerformed

    private void mnuConsTrabaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuConsTrabaActionPerformed
        cTrabaConsola object=new cTrabaConsola();
        object.setSize(1100,750);
        object.setResizable(false);
        object.setVisible(true);
    }//GEN-LAST:event_mnuConsTrabaActionPerformed

    private void mnuMovsTrabaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMovsTrabaActionPerformed
        TrabaConsola object=new TrabaConsola();
        object.setSize(750,650);
        object.setResizable(false);
        object.setVisible(true);
    }//GEN-LAST:event_mnuMovsTrabaActionPerformed

    private void mnuConsContrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuConsContrActionPerformed
        cContrConsola object=new cContrConsola();
        object.setSize(1100,750);
        object.setResizable(false);
        object.setVisible(true);
    }//GEN-LAST:event_mnuConsContrActionPerformed

    private void mnuMovsContrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMovsContrActionPerformed
        ContrConsola object=new ContrConsola();
        object.setSize(1100,750);
        object.setResizable(false);
        object.setVisible(true);
    }//GEN-LAST:event_mnuMovsContrActionPerformed

    private void mnuAspirTrabaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAspirTrabaActionPerformed
        ConvierteConsola object=new ConvierteConsola();
        object.setSize(700,500);
        object.setResizable(false);
        object.setLocationRelativeTo(null);
        object.setVisible(true);
    }//GEN-LAST:event_mnuAspirTrabaActionPerformed

    private void mnuEntInvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEntInvActionPerformed
        cEntradasConsola object=new cEntradasConsola();
        object.setSize(800,500);
        object.setResizable(false);
        object.setLocationRelativeTo(null);
        object.setVisible(true);
    }//GEN-LAST:event_mnuEntInvActionPerformed

    private void mnuSalInvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalInvActionPerformed
        cSalidasConsola object=new cSalidasConsola();
        object.setSize(800,500);
        object.setResizable(false);
        object.setLocationRelativeTo(null);
        object.setVisible(true);
    }//GEN-LAST:event_mnuSalInvActionPerformed

    private void mnuExisInvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuExisInvActionPerformed
        cExistenciasConsola object=new cExistenciasConsola();
        object.setSize(800,500);
        object.setResizable(false);
        object.setLocationRelativeTo(null);
        object.setVisible(true);
    }//GEN-LAST:event_mnuExisInvActionPerformed

    private void mnuMovInvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMovInvActionPerformed
        InvenConsola object=new InvenConsola();
        object.setSize(830,500);
        object.setResizable(false);
        object.setLocationRelativeTo(null);
        object.setVisible(true);
    }//GEN-LAST:event_mnuMovInvActionPerformed

    private void mnuInforActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuInforActionPerformed
        InforConsola object=new InforConsola();
        object.setSize(900,500);
        object.setResizable(false);
        object.setLocationRelativeTo(null);
        object.setVisible(true);
    }//GEN-LAST:event_mnuInforActionPerformed

    private void mnucInforActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnucInforActionPerformed
        cInforConsola object=new cInforConsola();
        object.setSize(900,600);
        object.setResizable(false);
        object.setLocationRelativeTo(null);
        object.setVisible(true);
    }//GEN-LAST:event_mnucInforActionPerformed

    private void mnuInformacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuInformacionActionPerformed
        // NO SE UTILIZA
    }//GEN-LAST:event_mnuInformacionActionPerformed

    private void mnuTiinfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTiinfActionPerformed
        TiinfConsola object=new TiinfConsola();
        object.setSize(700,440);
        object.setResizable(false);
        object.setLocationRelativeTo(null);
        object.setVisible(true);
    }//GEN-LAST:event_mnuTiinfActionPerformed

    private void mnuChofeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuChofeActionPerformed
        ChofeConsola object=new ChofeConsola();
        object.setSize(950,700);
        object.setResizable(false);
        object.setLocationRelativeTo(null);
        object.setVisible(true);
    }//GEN-LAST:event_mnuChofeActionPerformed

    private void mnuRutasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRutasActionPerformed
        RutasConsola object=new RutasConsola();
        object.setSize(900,500);
        object.setResizable(false);
        object.setLocationRelativeTo(null);
        object.setVisible(true);
    }//GEN-LAST:event_mnuRutasActionPerformed

    private void mnuUnidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuUnidaActionPerformed
        UnidaConsola object=new UnidaConsola();
        object.setSize(900,550);
        object.setResizable(false);
        object.setLocationRelativeTo(null);
        object.setVisible(true);
    }//GEN-LAST:event_mnuUnidaActionPerformed

    private void mnuEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEventActionPerformed
        EventConsola object=new EventConsola();
        object.setSize(970,600);
        object.setResizable(false);
        object.setLocationRelativeTo(null);
        object.setVisible(true);
    }//GEN-LAST:event_mnuEventActionPerformed

    private void mnuAypdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAypdfActionPerformed
        try{
            
            String lugarImagen="ftp://sirh.dyndns.org/ManualUsuarioGR.pdf";
            
            URL url1= new URL(lugarImagen);
            
            byte[] ba1 = new byte[1024];
            int baLength;
            File pdfFile =new File("ManualUsuarioGR.pdf");
            FileOutputStream fos1 = new FileOutputStream(pdfFile);
            
            URLConnection urlConn = url1.openConnection();
            
            InputStream is1 = url1.openStream();
            while ((baLength = is1.read(ba1)) != -1) {
                fos1.write(ba1, 0, baLength);
            }
            fos1.flush();
            fos1.close();
            is1.close();
            
            
            if (pdfFile.exists()) {
                
                if (Desktop.isDesktopSupported()) {
                    Desktop.getDesktop().open(pdfFile);
                } else {
                    System.out.println("Awt Desktop is not supported!");
                }
                
            } else {
                System.out.println("The file does't exists!");
            }
            
        }
        catch(Exception ex){
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_mnuAypdfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Menu().setVisible(true);
                } catch (MalformedURLException ex) {
                    Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnuAspirTraba;
    private javax.swing.JMenu mnuAspirantes;
    private javax.swing.JMenuItem mnuAypdf;
    private javax.swing.JMenu mnuAyuda;
    private javax.swing.JMenu mnuCatalogos;
    private javax.swing.JMenuItem mnuCateg;
    private javax.swing.JMenuItem mnuChofe;
    private javax.swing.JMenuItem mnuCivil;
    private javax.swing.JMenuItem mnuComit;
    private javax.swing.JMenuItem mnuConsAspira;
    private javax.swing.JMenuItem mnuConsContr;
    private javax.swing.JMenuItem mnuConsTraba;
    private javax.swing.JMenu mnuContratos;
    private javax.swing.JMenuItem mnuDepar;
    private javax.swing.JMenuItem mnuEmpre;
    private javax.swing.JMenuItem mnuEntInv;
    private javax.swing.JMenuItem mnuEspec;
    private javax.swing.JMenuItem mnuEstud;
    private javax.swing.JMenuItem mnuEvent;
    private javax.swing.JMenuItem mnuExisInv;
    private javax.swing.JMenuItem mnuInfor;
    private javax.swing.JMenu mnuInformacion;
    private javax.swing.JMenu mnuInventarios;
    private javax.swing.JMenuItem mnuMovInv;
    private javax.swing.JMenuItem mnuMovsAspira;
    private javax.swing.JMenuItem mnuMovsContr;
    private javax.swing.JMenuItem mnuMovsTraba;
    private javax.swing.JMenuItem mnuNacio;
    private javax.swing.JMenu mnuProcesos;
    private javax.swing.JMenuItem mnuRazon;
    private javax.swing.JMenuItem mnuRelig;
    private javax.swing.JMenu mnuReportes;
    private javax.swing.JMenuItem mnuRutas;
    private javax.swing.JMenuItem mnuSalInv;
    private javax.swing.JMenu mnuSalir;
    private javax.swing.JMenuItem mnuSangr;
    private javax.swing.JMenuItem mnuSexoo;
    private javax.swing.JMenuItem mnuStcon;
    private javax.swing.JMenuItem mnuStrab;
    private javax.swing.JMenuItem mnuTapri;
    private javax.swing.JMenuItem mnuTicon;
    private javax.swing.JMenuItem mnuTidoc;
    private javax.swing.JMenuItem mnuTiinf;
    private javax.swing.JMenuItem mnuTipar;
    private javax.swing.JMenuItem mnuTipyp;
    private javax.swing.JMenu mnuTrabajadores;
    private javax.swing.JMenu mnuTransporte;
    private javax.swing.JMenuItem mnuTurno;
    private javax.swing.JMenuItem mnuUbica;
    private javax.swing.JMenuItem mnuUnida;
    private javax.swing.JMenuItem mnuUsuar;
    private javax.swing.JMenuItem mnucInfor;
    private javax.swing.JLabel txtEmpresa;
    private javax.swing.JLabel txtNombre;
    // End of variables declaration//GEN-END:variables
}
