
package sirh;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

public class PryprConsola extends javax.swing.JFrame {


    public PryprConsola() {
        initComponents();
        setDefaultCloseOperation(0);
        Iniciar();
    }
    
    private void Limpiar(JTable tabla){
        while(tabla.getRowCount()>0){
            ((DefaultTableModel) tabla.getModel()).removeRow(0);
        }
    }
    
    private void Iniciar(){
        fecha.setText(fechaActual());
        usuario.setText(Acceso.getClaveUsuario());
        txtNombre.setText(Acceso.getNombreUsuario());
        txtEmpresa.setText(Acceso.getEmpresaUsuario());
        txtNumero.setText(String.valueOf(Contr.getNumTrabaja()));
        txtTrabaja.setText(Contr.getNomTrabaja());
        txtContrato.setText(Contr.getNcoTrabaja());
        //String NomEmp = Acceso.getEmpresaUsuario();
        String NomEmp = "AUTOS TOLUCA";
        
        int RegTra = Contr.getNumTrabaja();
        String NumCon = Contr.getNcoTrabaja();
        Limpiar(tablaprypr);
        DefaultTableModel modelo=(DefaultTableModel) tablaprypr.getModel();
        Prypr e1=new Prypr();
        e1.LlenarDatos(modelo, RegTra, NumCon);
        
        tipo.removeAllItems();
        tipo.addItem("");
        Prypr e2=new Prypr();
        e2.LlenarTipo(tipo, NomEmp);
        fecsol.setDate(null);
        caracte.setText("");
        aprob.removeAllItems();
        aprob.addItem("");
        Prypr e3=new Prypr();
        e3.LlenarSino(aprob);
        rechaz.setText("");
        fecres.setDate(null);
        importe.setText("");
        dias.setText("");
        benef.setText("");
        pariente.removeAllItems();
        pariente.addItem("");
        Prypr e4=new Prypr();
        e4.LlenarPariente(pariente);
        path.setText("FTP://SIRH.DYNDNS.ORG/PREMIOS/PREMIOS.GIF");
        status.setText("");
        crear.setEnabled(true);
        tipo.setEnabled(true);
        fecsol.setEnabled(true);
        
    }
    
    public static String fechaActual(){
        Date fecha= new Date();
        SimpleDateFormat formatoFecha=new SimpleDateFormat("dd/MM/YYYY HH:mm:ss");
        return formatoFecha.format(fecha);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaprypr = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        tipo = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        fecsol = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        caracte = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        aprob = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        rechaz = new javax.swing.JTextField();
        fecres = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        importe = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        dias = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        benef = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        pariente = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        path = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        status = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        fecha = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        crear = new javax.swing.JButton();
        actualizar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtEmpresa = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        txtTrabaja = new javax.swing.JTextField();
        txtContrato = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SNTIAISCRM Sistema de Recursos Humanos");
        setMaximumSize(new java.awt.Dimension(818, 542));
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        tablaprypr.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tipo", "Beneficiario", "Pariente", "Fecha Solicitud", "Aprobada", "Fecha Resolución"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaprypr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablapryprMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaprypr);

        jLabel2.setForeground(new java.awt.Color(204, 0, 51));
        jLabel2.setText("Tipo:");

        jLabel3.setForeground(new java.awt.Color(204, 0, 51));
        jLabel3.setText("Fec Solicitud:");

        jLabel4.setText("Carcateristicas:");

        jLabel5.setText("Aprobada:");

        jLabel6.setText("Causa Rech:");

        jLabel7.setForeground(new java.awt.Color(204, 0, 51));
        jLabel7.setText("F. Resolucion:");

        jLabel8.setText("Importe:");

        importe.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                importeKeyTyped(evt);
            }
        });

        jLabel9.setText("Días:");

        dias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diasActionPerformed(evt);
            }
        });
        dias.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                diasKeyTyped(evt);
            }
        });

        jLabel10.setText("Beneficario:");

        jLabel11.setText("Pariente:");

        jLabel12.setText("Path Recibo:");

        path.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pathMouseClicked(evt);
            }
        });

        jLabel13.setText("Status:");

        status.setEditable(false);

        jLabel14.setText("Fecha:");

        fecha.setEditable(false);

        jLabel15.setText("Usuario:");

        usuario.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(318, 318, 318)
                                .addComponent(jLabel14))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(fecsol, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel8))
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGap(19, 19, 19)
                                                    .addComponent(tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGap(18, 18, 18)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(dias, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(importe, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(fecres, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(rechaz, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(aprob, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(caracte))))))
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel15))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(path)
                            .addComponent(benef)
                            .addComponent(pariente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(status)
                            .addComponent(fecha)
                            .addComponent(usuario))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(benef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(fecsol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(pariente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(caracte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(path, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(aprob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(rechaz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fecres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(importe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(dias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        crear.setText("Crear");
        crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearActionPerformed(evt);
            }
        });

        actualizar.setText("Actualizar");
        actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarActionPerformed(evt);
            }
        });

        eliminar.setText("Eliminar");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(crear)
                .addGap(18, 18, 18)
                .addComponent(actualizar)
                .addGap(18, 18, 18)
                .addComponent(eliminar)
                .addGap(18, 18, 18)
                .addComponent(cancelar)
                .addGap(18, 18, 18)
                .addComponent(salir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crear)
                    .addComponent(actualizar)
                    .addComponent(eliminar)
                    .addComponent(cancelar)
                    .addComponent(salir))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("MOVIMIENTOS DE PREMIOS Y PRESTACIONES");

        txtEmpresa.setEditable(false);
        txtEmpresa.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        txtEmpresa.setForeground(new java.awt.Color(204, 0, 0));
        txtEmpresa.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtEmpresa.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtNombre.setEditable(false);
        txtNombre.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(204, 0, 0));
        txtNombre.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtNombre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtNumero.setEditable(false);

        txtTrabaja.setEditable(false);

        txtContrato.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTrabaja, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmpresa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTrabaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearActionPerformed
        try{
            Prypr e=new Prypr();
            String dtipo=tipo.getSelectedItem().toString();
            if(dtipo.isEmpty()){
                JOptionPane.showMessageDialog(this, "Se requiere un tipo de solicitud, verifique .....");
                Iniciar();
            }
            else{
                if(fecsol.getDate() == null){
                    JOptionPane.showMessageDialog(this, "Se requiere la fecha de solicitud, verifique .....");
                    fecsol.grabFocus();
                }
                else{
                    if(fecres.getDate() == null){
                        JOptionPane.showMessageDialog(this, "Se requiere la fecha de resolución, verifique .....");
                        fecres.grabFocus();
                    }
                    else{
                        String dbenef=benef.getText().toUpperCase();
                        String dpariente=pariente.getSelectedItem().toString();
                        int añox=fecsol.getCalendar().get(Calendar.YEAR);
                        int mesx=fecsol.getCalendar().get(Calendar.MONTH)+1;
                        int diax=fecsol.getCalendar().get(Calendar.DAY_OF_MONTH);
                        String dfecsol=(añox+"/"+mesx+"/"+diax);
                        String daprob=aprob.getSelectedItem().toString();
                        int añor=fecres.getCalendar().get(Calendar.YEAR);
                        int mesr=fecres.getCalendar().get(Calendar.MONTH)+1;
                        int diar=fecres.getCalendar().get(Calendar.DAY_OF_MONTH);
                        String dfecres=(añor+"/"+mesr+"/"+diar);
                        String dcaracte=caracte.getText().toUpperCase();
                        String drechaz=rechaz.getText().toUpperCase();
                        Float dimporte=Float.parseFloat(importe.getText());
                        int ddias=Integer.parseInt(dias.getText());
                        String dpath=path.getText().toUpperCase();
                        e.Agregar(Contr.getNumTrabaja(), Contr.getNomTrabaja(), Contr.getRfcTrabaja(), Contr.getPatTrabaja(),
                                  Contr.getStcTrabaja(), Contr.getFesTrabaja(), Contr.getNcoTrabaja(), Contr.getCemTrabaja(),
                                  Contr.getNemTrabaja(), Contr.getCdeTrabaja(), Contr.getNdeTrabaja(), Contr.getCseTrabaja(),
                                  Contr.getNseTrabaja(), Contr.getCcaTrabaja(), Contr.getNcaTrabaja(), Contr.getSxdTrabaja(),
                                  Contr.getCtuTrabaja(), Contr.getNtuTrabaja(), Contr.getCtiTrabaja(), Contr.getNtiTrabaja(),
                                  Contr.getFinTrabaja(), Contr.getFteTrabaja(), dtipo, dbenef, dpariente, dfecsol, daprob, dfecres,
                                  dcaracte, drechaz, dimporte, ddias, dpath, Acceso.getClaveUsuario());
                        JOptionPane.showMessageDialog(this, "Registro creado .....");
                        Iniciar();                    
                    }
                }
            }
        }
        catch(NumberFormatException nfe){
            System.out.println("No hay fecha: "+nfe);
        }
    }//GEN-LAST:event_crearActionPerformed

    private void actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarActionPerformed
        try{
            Prypr e=new Prypr();
            String dtipo=tipo.getSelectedItem().toString();
            if(dtipo.isEmpty()){
                JOptionPane.showMessageDialog(this, "Se requiere un tipo de solicitud, verifique .....");
                Iniciar();
            }
            else{
                if(fecsol.getDate() == null){
                    JOptionPane.showMessageDialog(this, "Se requiere la fecha de solicitud, verifique .....");
                    fecsol.grabFocus();
                }
                else{
                    if(fecres.getDate() == null){
                        JOptionPane.showMessageDialog(this, "Se requiere la fecha de resolución, verifique .....");
                        fecres.grabFocus();
                    }
                    else{
                        String dbenef=benef.getText().toUpperCase();
                        String dpariente=pariente.getSelectedItem().toString();
                        int añox=fecsol.getCalendar().get(Calendar.YEAR);
                        int mesx=fecsol.getCalendar().get(Calendar.MONTH)+1;
                        int diax=fecsol.getCalendar().get(Calendar.DAY_OF_MONTH);
                        String dfecsol=(añox+"/"+mesx+"/"+diax);
                        String daprob=aprob.getSelectedItem().toString();
                        int añor=fecres.getCalendar().get(Calendar.YEAR);
                        int mesr=fecres.getCalendar().get(Calendar.MONTH)+1;
                        int diar=fecres.getCalendar().get(Calendar.DAY_OF_MONTH);
                        String dfecres=(añor+"/"+mesr+"/"+diar);
                        String dcaracte=caracte.getText().toUpperCase();
                        String drechaz=rechaz.getText().toUpperCase();
                        Float dimporte=Float.parseFloat(importe.getText());
                        int ddias=Integer.parseInt(dias.getText());
                        String dpath=path.getText().toUpperCase();
                        e.Actualizar(Contr.getNumTrabaja(), Contr.getNomTrabaja(), Contr.getRfcTrabaja(), Contr.getPatTrabaja(),
                                     Contr.getStcTrabaja(), Contr.getFesTrabaja(), Contr.getNcoTrabaja(), Contr.getCemTrabaja(),
                                     Contr.getNemTrabaja(), Contr.getCdeTrabaja(), Contr.getNdeTrabaja(), Contr.getCseTrabaja(),
                                     Contr.getNseTrabaja(), Contr.getCcaTrabaja(), Contr.getNcaTrabaja(), Contr.getSxdTrabaja(),
                                     Contr.getCtuTrabaja(), Contr.getNtuTrabaja(), Contr.getCtiTrabaja(), Contr.getNtiTrabaja(),
                                     Contr.getFinTrabaja(), Contr.getFteTrabaja(), dtipo, dbenef, dpariente, dfecsol, daprob, dfecres,
                                     dcaracte, drechaz, dimporte, ddias, dpath, Acceso.getClaveUsuario());
                        JOptionPane.showMessageDialog(this, "Registro creado .....");
                        Iniciar();                    
                    }
                }
            }
        }
        catch(NumberFormatException nfe){
            System.out.println("No hay fecha: "+nfe);
        }
    }//GEN-LAST:event_actualizarActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        Prypr e=new Prypr();
        int dnumtra=Contr.getNumTrabaja();
        String dnumcon=Contr.getNcoTrabaja();
        String dtipo=tipo.getSelectedItem().toString();
        if(dtipo.isEmpty()){
            JOptionPane.showMessageDialog(this, "Se requiere un tipo de solicitud, verifique .....");
            Iniciar();
        }
        else{
            if(fecsol.getDate() == null){
                JOptionPane.showMessageDialog(this, "Se requiere la fecha de solicitud, verifique .....");
                fecsol.grabFocus();
            }
            else{
                if(fecres.getDate() == null){
                    JOptionPane.showMessageDialog(this, "Se requiere la fecha de resolución, verifique .....");
                    fecres.grabFocus();
                }
                else{
                    String dbenef=benef.getText().toUpperCase();
                    String dpariente=pariente.getSelectedItem().toString();
                    int añox=fecsol.getCalendar().get(Calendar.YEAR);
                    int mesx=fecsol.getCalendar().get(Calendar.MONTH)+1;
                    int diax=fecsol.getCalendar().get(Calendar.DAY_OF_MONTH);
                    String dfecsol=(añox+"/"+mesx+"/"+diax);
                    String daprob=aprob.getSelectedItem().toString();
                    int añor=fecres.getCalendar().get(Calendar.YEAR);
                    int mesr=fecres.getCalendar().get(Calendar.MONTH)+1;
                    int diar=fecres.getCalendar().get(Calendar.DAY_OF_MONTH);
                    String dfecres=(añor+"/"+mesr+"/"+diar);
                    e.Eliminar(dnumtra, dnumcon, dtipo, dbenef, dpariente, dfecsol, daprob, dfecres, Acceso.getClaveUsuario());
                    JOptionPane.showMessageDialog(this, "Registro eliminado .....");
                    Iniciar();                    
                }
            }
        }
    }//GEN-LAST:event_eliminarActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        Iniciar();
    }//GEN-LAST:event_cancelarActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        this.dispose();
    }//GEN-LAST:event_salirActionPerformed

    private void tablapryprMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablapryprMouseClicked
        DefaultTableModel modelo= (DefaultTableModel) tablaprypr.getModel();
        tipo.setSelectedItem(modelo.getValueAt(tablaprypr.getSelectedRow(), 0)+"");
        benef.setText(modelo.getValueAt(tablaprypr.getSelectedRow(), 1)+"");
        pariente.setSelectedItem(modelo.getValueAt(tablaprypr.getSelectedRow(), 2)+"");
        String fsol = (modelo.getValueAt(tablaprypr.getSelectedRow(), 3)+"");
        if("null".equals(fsol)){
            System.out.println("La fecha de solicitud esta vacia .....");
        }
        else{
            SimpleDateFormat formatofecha1=new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            try{
                Date fecha1 = formatofecha1.parse(fsol);
                fecsol.setDate(fecha1);
            }
            catch(ParseException pe1){
            System.out.println("Error Parse1: "+pe1.getMessage());
            }
        }
        aprob.setSelectedItem(modelo.getValueAt(tablaprypr.getSelectedRow(), 4)+"");
        String frec = (modelo.getValueAt(tablaprypr.getSelectedRow(), 5)+"");
        if("null".equals(frec)){
            System.out.println("La fecha de resolución esta vacia .....");
        }
        else{
            SimpleDateFormat formatofecha2=new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            try{
                Date fecha2 = formatofecha2.parse(frec);
                fecres.setDate(fecha2);
            }
            catch(ParseException pe2){
            System.out.println("Error Parse2: "+pe2.getMessage());
            }
        }

        Prypr com=new Prypr();
        int dnumtra=Contr.getNumTrabaja();
        String dnumcon=Contr.getNcoTrabaja();
        String dtipo=tipo.getSelectedItem().toString();
        String dbenef=benef.getText().toUpperCase();
        String dpariente=pariente.getSelectedItem().toString();
        int añox=fecsol.getCalendar().get(Calendar.YEAR);
        int mesx=fecsol.getCalendar().get(Calendar.MONTH)+1;
        int diax=fecsol.getCalendar().get(Calendar.DAY_OF_MONTH);
        String dfecsol=(añox+"/"+mesx+"/"+diax);
        String daprob=aprob.getSelectedItem().toString();
        int añor=fecres.getCalendar().get(Calendar.YEAR);
        int mesr=fecres.getCalendar().get(Calendar.MONTH)+1;
        int diar=fecres.getCalendar().get(Calendar.DAY_OF_MONTH);
        String dfecres=(añor+"/"+mesr+"/"+diar);
        Object[] datos1=com.Comple(dnumtra, dnumcon, dtipo, dbenef, dpariente, dfecsol, daprob, dfecres);
        caracte.setText(datos1[0]+"");
        rechaz.setText(datos1[1]+"");
        importe.setText(datos1[2]+"");
        dias.setText(datos1[3]+"");
        path.setText(datos1[4]+"");
        status.setText(datos1[5]+"");
        fecha.setText(datos1[6]+"");
        usuario.setText(datos1[7]+"");
        crear.setEnabled(false);
        tipo.setEnabled(false);
        fecsol.setEnabled(false);
    }//GEN-LAST:event_tablapryprMouseClicked

    private void pathMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pathMouseClicked
        Prypr.setPathUsuario(path.getText().toUpperCase());
        VPryprConsola object=new VPryprConsola();
        object.setVisible(true);
    }//GEN-LAST:event_pathMouseClicked

    private void importeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_importeKeyTyped
        char car = evt.getKeyChar();
        if((car<'0' || car>'9') && (car != '.'))
        {
            evt.consume();
        }
    }//GEN-LAST:event_importeKeyTyped

    private void diasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_diasKeyTyped
        char car = evt.getKeyChar();
        if((car<'0' || car>'9'))
        {
            evt.consume();
        }
    }//GEN-LAST:event_diasKeyTyped

    private void diasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diasActionPerformed
        // NO SE UTILIZA
    }//GEN-LAST:event_diasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PryprConsola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PryprConsola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PryprConsola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PryprConsola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PryprConsola().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizar;
    private javax.swing.JComboBox aprob;
    private javax.swing.JTextField benef;
    private javax.swing.JButton cancelar;
    private javax.swing.JTextField caracte;
    private javax.swing.JButton crear;
    private javax.swing.JTextField dias;
    private javax.swing.JButton eliminar;
    private javax.swing.JTextField fecha;
    private com.toedter.calendar.JDateChooser fecres;
    private com.toedter.calendar.JDateChooser fecsol;
    private javax.swing.JTextField importe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox pariente;
    private javax.swing.JTextField path;
    private javax.swing.JTextField rechaz;
    private javax.swing.JButton salir;
    private javax.swing.JTextField status;
    private javax.swing.JTable tablaprypr;
    private javax.swing.JComboBox tipo;
    private javax.swing.JTextField txtContrato;
    private javax.swing.JTextField txtEmpresa;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtTrabaja;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
