
package sirh;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

public class RutasConsola extends javax.swing.JFrame {


    public RutasConsola() {
        initComponents();
        setDefaultCloseOperation(0);
        Iniciar();
    }
    
    private void Limpiar(JTable tabla){
        while(tabla.getRowCount()>0){
            ((DefaultTableModel) tabla.getModel()).removeRow(0);
        }
    }

        
    private void Iniciar(){
        Limpiar(tablarutas);
        DefaultTableModel modelo=(DefaultTableModel) tablarutas.getModel();
        Rutas e1=new Rutas();
        e1.LlenarDatos(modelo);
        numrut.setText("");
        cveemp.removeAllItems();
        cveemp.addItem("");
        Rutas e2=new Rutas();
        e2.LlenarCveempresa(cveemp);
        nomemp.setText("");
        lugori.setText("");
        lugdes.setText("");
        path.setText("FTP://SIRH.DYNDNS.ORG/CROQUIS/CROQUIS.GIF");
        observa.setText("");
        Limpiar(tablarutas1);
        busnum.setText("");
        busemp.setText("");
        busori.setText("");
        busdes.setText("");
        
        fecha.setText(fechaActual());
        usuario.setText(Acceso.getClaveUsuario());
        txtNombre.setText(Acceso.getNombreUsuario());
        txtEmpresa.setText(Acceso.getEmpresaUsuario());
        crear.setEnabled(true);
        numrut.setEnabled(true);
        cveemp.setEnabled(true);
        
    }
    
    public static String fechaActual(){
        Date fecha= new Date();
        SimpleDateFormat formatoFecha=new SimpleDateFormat("dd/MM/YYYY HH:mm:ss");
        return formatoFecha.format(fecha);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtEmpresa = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablarutas1 = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        busnum = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        busemp = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        busori = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        busdes = new javax.swing.JTextField();
        salir1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablarutas = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        numrut = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cveemp = new javax.swing.JComboBox();
        nomemp = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lugori = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lugdes = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        path = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        observa = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        fecha = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();
        crear = new javax.swing.JButton();
        actualizar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        salir = new javax.swing.JButton();

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SNTIAISCRM Sistema de Recursos Humanos");
        setMaximumSize(new java.awt.Dimension(900, 500));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("RUTAS DE TRANSPORTE DE PERSONAL");

        txtEmpresa.setEditable(false);
        txtEmpresa.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        txtEmpresa.setForeground(new java.awt.Color(204, 0, 0));
        txtEmpresa.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtEmpresa.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtNombre.setEditable(false);
        txtNombre.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(204, 0, 0));
        txtNombre.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtNombre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tablarutas1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero Ruta", "Cve Empresa", "Nombre Empresa", "Origen", "Destino", "Path Croquis", "Observaciones", "Status", "Ultima Fecha", "Ultimo Usuario"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablarutas1);

        jLabel11.setText("Número:");

        busnum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                busnumMouseClicked(evt);
            }
        });
        busnum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                busnumKeyPressed(evt);
            }
        });

        jLabel12.setText("Empresa:");

        busemp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                busempMouseClicked(evt);
            }
        });
        busemp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                busempKeyPressed(evt);
            }
        });

        jLabel13.setText("Origen:");

        busori.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                busoriMouseClicked(evt);
            }
        });
        busori.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                busoriKeyPressed(evt);
            }
        });

        jLabel14.setText("Destino:");

        busdes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                busdesMouseClicked(evt);
            }
        });
        busdes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                busdesKeyPressed(evt);
            }
        });

        salir1.setText("Salir");
        salir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salir1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(busnum, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(busemp, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(busori, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(busdes, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                        .addComponent(salir1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(busnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(busemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(busori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(busdes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salir1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Búsqueda", jPanel1);

        tablarutas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero Ruta", "Cve Empresa", "Nombre Empresa", "Origen", "Destino", "Path Croquis", "Observaciones", "Status", "Ultima Fecha", "Ultimo Usuario"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablarutas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablarutasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablarutas);

        jLabel2.setForeground(new java.awt.Color(204, 0, 51));
        jLabel2.setText("Número de Ruta:");

        jLabel3.setForeground(new java.awt.Color(204, 0, 51));
        jLabel3.setText("Empresa:");

        cveemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cveempActionPerformed(evt);
            }
        });

        nomemp.setEditable(false);

        jLabel4.setText("Lugar Origen:");

        jLabel5.setText("Lugar Destino:");

        jLabel7.setText("Path Croquis:");

        path.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pathMouseClicked(evt);
            }
        });

        jLabel8.setText("Observaciones:");

        jLabel9.setText("Fecha:");

        fecha.setEditable(false);

        jLabel10.setText("Usuario:");

        usuario.setEditable(false);

        crear.setText("Crear");
        crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearActionPerformed(evt);
            }
        });

        actualizar.setText("Actualizar");
        actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarActionPerformed(evt);
            }
        });

        eliminar.setText("Eliminar");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(cveemp, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nomemp, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(numrut)
                            .addComponent(lugori)
                            .addComponent(lugdes)
                            .addComponent(path)
                            .addComponent(observa)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(usuario)))
                        .addGap(56, 56, 56)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(actualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(crear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(salir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 120, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(numrut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(crear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cveemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(actualizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lugori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lugdes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(path, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(observa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Movimientos", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 868, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 12, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearActionPerformed
        Rutas e=new Rutas();
        String dnumrut = numrut.getText().toUpperCase();
        if(dnumrut.isEmpty()){
            JOptionPane.showMessageDialog(this, "Se requiere un número o clave de ruta (1), verifique .....");
            numrut.grabFocus();
        }
        else{
            if(dnumrut.trim().equals("")){
                JOptionPane.showMessageDialog(this, "Se requiere un número o clave de ruta (2), verifique .....");
                numrut.setText("");
                numrut.grabFocus();
            }
            else{
                String dcveemp = cveemp.getSelectedItem().toString();
                if(dcveemp.isEmpty()){
                    JOptionPane.showMessageDialog(this, "Se requiere una clave de empresa, verifique .....");
                    cveemp.grabFocus(); 
                }
                else{
                    String dnomemp=nomemp.getText().toUpperCase();
                    String dlugori=lugori.getText().toUpperCase();
                    String dlugdes=lugdes.getText().toUpperCase();
                    String dpath=path.getText().toUpperCase();
                    String dobserva=observa.getText().toUpperCase();
                    e.Agregar(dnumrut, dcveemp, dnomemp, dlugori, dlugdes, dpath, dobserva, Acceso.getClaveUsuario());
                    JOptionPane.showMessageDialog(this, "Registro creado .....");
                    Iniciar();
                }
            }
        }
    }//GEN-LAST:event_crearActionPerformed

    private void actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarActionPerformed
        Rutas e=new Rutas();
        String dnumrut = numrut.getText().toUpperCase();
        if(dnumrut.isEmpty()){
            JOptionPane.showMessageDialog(this, "Se requiere un número o clave de ruta (1), verifique .....");
            numrut.grabFocus();
        }
        else{
            if(dnumrut.trim().equals("")){
                JOptionPane.showMessageDialog(this, "Se requiere un número o clave de ruta (2), verifique .....");
                numrut.setText("");
                numrut.grabFocus();
            }
            else{
                String dcveemp = cveemp.getSelectedItem().toString();
                if(dcveemp.isEmpty()){
                    JOptionPane.showMessageDialog(this, "Se requiere una clave de empresa, verifique .....");
                    cveemp.grabFocus(); 
                }
                else{
                    String dnomemp=nomemp.getText().toUpperCase();
                    String dlugori=lugori.getText().toUpperCase();
                    String dlugdes=lugdes.getText().toUpperCase();
                    String dpath=path.getText().toUpperCase();
                    String dobserva=observa.getText().toUpperCase();
                    e.Actualizar(dnumrut, dcveemp, dnomemp, dlugori, dlugdes, dpath, dobserva, Acceso.getClaveUsuario());
                    JOptionPane.showMessageDialog(this, "Registro actualizado .....");
                    Iniciar();
                }
            }
        }
    }//GEN-LAST:event_actualizarActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
       Rutas e=new Rutas();
        String dnumrut = numrut.getText().toUpperCase();
        if(dnumrut.isEmpty()){
            JOptionPane.showMessageDialog(this, "Se requiere un número o clave de ruta (1), verifique .....");
            Iniciar();
        }
        else{
            if(dnumrut.trim().equals("")){
                JOptionPane.showMessageDialog(this, "Se requiere un número o clave de ruta (2), verifique .....");
                Iniciar();
            }
            else{
                String dcveemp = cveemp.getSelectedItem().toString();
                if(dcveemp.isEmpty()){
                    JOptionPane.showMessageDialog(this, "Se requiere una clave de empresa, verifique .....");
                    Iniciar(); 
                }
                else{
                    String dnomemp=nomemp.getText().toUpperCase();
                    e.Eliminar(dnumrut, dcveemp, dnomemp, Acceso.getClaveUsuario());
                    JOptionPane.showMessageDialog(this, "Registro eliminado .....");
                    Iniciar();
                }
            }
        }
    }//GEN-LAST:event_eliminarActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        Iniciar();
    }//GEN-LAST:event_cancelarActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        this.dispose();
    }//GEN-LAST:event_salirActionPerformed

    private void busnumKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_busnumKeyPressed
        Rutas e=new Rutas();
        Limpiar(tablarutas1);
        DefaultTableModel modelo= (DefaultTableModel) tablarutas1.getModel();
        e.BusNumero(modelo, busnum.getText().toUpperCase());
    }//GEN-LAST:event_busnumKeyPressed

    private void busnumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_busnumMouseClicked
        Iniciar();
    }//GEN-LAST:event_busnumMouseClicked

    private void busempKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_busempKeyPressed
        Rutas e=new Rutas();
        Limpiar(tablarutas1);
        DefaultTableModel modelo= (DefaultTableModel) tablarutas1.getModel();
        e.BusEmpresa(modelo, busemp.getText().toUpperCase());
    }//GEN-LAST:event_busempKeyPressed

    private void busempMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_busempMouseClicked
        Iniciar();
    }//GEN-LAST:event_busempMouseClicked

    private void busoriKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_busoriKeyPressed
        Rutas e=new Rutas();
        Limpiar(tablarutas1);
        DefaultTableModel modelo= (DefaultTableModel) tablarutas1.getModel();
        e.BusOrigen(modelo, busori.getText().toUpperCase());
    }//GEN-LAST:event_busoriKeyPressed

    private void busoriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_busoriMouseClicked
        Iniciar();
    }//GEN-LAST:event_busoriMouseClicked

    private void busdesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_busdesKeyPressed
        Rutas e=new Rutas();
        Limpiar(tablarutas1);
        DefaultTableModel modelo= (DefaultTableModel) tablarutas1.getModel();
        e.BusDestino(modelo, busdes.getText().toUpperCase());
    }//GEN-LAST:event_busdesKeyPressed

    private void busdesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_busdesMouseClicked
        Iniciar();
    }//GEN-LAST:event_busdesMouseClicked

    private void salir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salir1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_salir1ActionPerformed

    private void cveempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cveempActionPerformed
        String claveseleccionada=cveemp.getSelectedItem()+"";
        Rutas e=new Rutas();
        Object[] datos=e.Datos(claveseleccionada);
        nomemp.setText(datos[0]+"");
    }//GEN-LAST:event_cveempActionPerformed

    private void tablarutasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablarutasMouseClicked
        DefaultTableModel modelo= (DefaultTableModel) tablarutas.getModel();
        numrut.setText(modelo.getValueAt(tablarutas.getSelectedRow(), 0)+"");
        cveemp.setSelectedItem(modelo.getValueAt(tablarutas.getSelectedRow(), 1)+"");
        nomemp.setText(modelo.getValueAt(tablarutas.getSelectedRow(), 2)+"");
        lugori.setText(modelo.getValueAt(tablarutas.getSelectedRow(), 3)+"");
        lugdes.setText(modelo.getValueAt(tablarutas.getSelectedRow(), 4)+"");
        path.setText(modelo.getValueAt(tablarutas.getSelectedRow(), 5)+"");
        observa.setText(modelo.getValueAt(tablarutas.getSelectedRow(), 6)+"");
        fecha.setText(modelo.getValueAt(tablarutas.getSelectedRow(), 8)+"");
        usuario.setText(modelo.getValueAt(tablarutas.getSelectedRow(), 9)+"");
        crear.setEnabled(false);
        numrut.setEnabled(false);
        cveemp.setEnabled(false);
    }//GEN-LAST:event_tablarutasMouseClicked

    private void pathMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pathMouseClicked
        Rutas.setPathUsuario(path.getText().toUpperCase());
        VRutasConsola object=new VRutasConsola();
        object.setVisible(true);
    }//GEN-LAST:event_pathMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RutasConsola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RutasConsola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RutasConsola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RutasConsola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RutasConsola().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizar;
    private javax.swing.JTextField busdes;
    private javax.swing.JTextField busemp;
    private javax.swing.JTextField busnum;
    private javax.swing.JTextField busori;
    private javax.swing.JButton cancelar;
    private javax.swing.JButton crear;
    private javax.swing.JComboBox cveemp;
    private javax.swing.JButton eliminar;
    private javax.swing.JTextField fecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField lugdes;
    private javax.swing.JTextField lugori;
    private javax.swing.JTextField nomemp;
    private javax.swing.JTextField numrut;
    private javax.swing.JTextField observa;
    private javax.swing.JTextField path;
    private javax.swing.JButton salir;
    private javax.swing.JButton salir1;
    private javax.swing.JTable tablarutas;
    private javax.swing.JTable tablarutas1;
    private javax.swing.JTextField txtEmpresa;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
