
package sirh;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

public class SanciConsola extends javax.swing.JFrame {


    public SanciConsola() {
        initComponents();
        setDefaultCloseOperation(0);
        Iniciar();
    }
    
    private void Limpiar(JTable tabla){
        while(tabla.getRowCount()>0){
            ((DefaultTableModel) tabla.getModel()).removeRow(0);
        }
    }
    
    private void Iniciar(){
        fecha.setText(fechaActual());
        usuario.setText(Acceso.getClaveUsuario());
        txtNombre.setText(Acceso.getNombreUsuario());
        txtEmpresa.setText(Acceso.getEmpresaUsuario());
        txtNumero.setText(String.valueOf(Contr.getNumTrabaja()));
        txtTrabaja.setText(Contr.getNomTrabaja());
        txtContrato.setText(Contr.getNcoTrabaja());
        
        int RegTra = Contr.getNumTrabaja();
        String NumCon = Contr.getNcoTrabaja();
        Limpiar(tablasanci);
        DefaultTableModel modelo=(DefaultTableModel) tablasanci.getModel();
        Sanci e1=new Sanci();
        e1.LlenarDatos(modelo, RegTra, NumCon);
        
        causa.setText("");
        descrip.setText("");
        fechec.setDate(null);
        horhec.setText("");
        sangen.setText("");
        diasan.setText("");
        finsan.setDate(null);
        ftesan.setDate(null);
        autoriza.removeAllItems();
        autoriza.addItem("");
        Sanci e2=new Sanci();
        e2.LlenarComite(autoriza);
        nomaut.setText("");
        path.setText("FTP://SIRH.DYNDNS.ORG/SANCIONES/SANCIONES.GIF");
        status.setText("");
        crear.setEnabled(true);
        causa.setEnabled(true);
        fechec.setEnabled(true);
        
    }
    
    public static String fechaActual(){
        Date fecha= new Date();
        SimpleDateFormat formatoFecha=new SimpleDateFormat("dd/MM/YYYY HH:mm:ss");
        return formatoFecha.format(fecha);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablasanci = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        causa = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        descrip = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        fechec = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        horhec = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        sangen = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        diasan = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        finsan = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        ftesan = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        autoriza = new javax.swing.JComboBox();
        nomaut = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        path = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        status = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        fecha = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtEmpresa = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        txtTrabaja = new javax.swing.JTextField();
        txtContrato = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        crear = new javax.swing.JButton();
        actualizar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SNTIAISCRM Sistema de Recursos Humanos");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        tablasanci.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Causa", "Fecha", "Sanción", "Autoriza", "Nombre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablasanci.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablasanciMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablasanci);

        jLabel2.setForeground(new java.awt.Color(204, 0, 51));
        jLabel2.setText("Causa:");

        jLabel3.setText("Descripción hechos:");

        jLabel4.setForeground(new java.awt.Color(204, 0, 51));
        jLabel4.setText("Fecha:");

        jLabel5.setText("Hora:");

        jLabel6.setText("Sanción Generada:");

        jLabel7.setForeground(new java.awt.Color(204, 0, 51));
        jLabel7.setText("Dias Sanción:");

        diasan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                diasanKeyTyped(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(204, 0, 51));
        jLabel8.setText("Fec. Inicio:");

        jLabel9.setForeground(new java.awt.Color(204, 0, 51));
        jLabel9.setText("Fec. Término:");

        jLabel10.setText("Autoriza:");

        autoriza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autorizaActionPerformed(evt);
            }
        });

        nomaut.setEditable(false);

        jLabel11.setText("Path Docto:");

        path.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pathMouseClicked(evt);
            }
        });

        jLabel12.setText("Status:");

        status.setEditable(false);

        jLabel13.setText("Fecha:");

        fecha.setEditable(false);

        jLabel14.setText("Usuario:");

        usuario.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(causa)
                            .addComponent(sangen)
                            .addComponent(path)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(autoriza, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(diasan, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel8)))
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(finsan, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)
                                        .addComponent(ftesan, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(nomaut)))
                            .addComponent(descrip, javax.swing.GroupLayout.PREFERRED_SIZE, 755, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(fechec, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(horhec, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel13)
                                .addGap(43, 43, 43)
                                .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(jLabel14)
                                .addGap(26, 26, 26)
                                .addComponent(usuario)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(causa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(descrip, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fechec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(horhec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sangen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(diasan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)
                        .addComponent(jLabel8))
                    .addComponent(finsan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftesan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(autoriza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nomaut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(path, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("MOVIMIENTOS DE SANCIONES");

        txtEmpresa.setEditable(false);
        txtEmpresa.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        txtEmpresa.setForeground(new java.awt.Color(204, 0, 0));
        txtEmpresa.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtEmpresa.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtNombre.setEditable(false);
        txtNombre.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(204, 0, 0));
        txtNombre.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtNombre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtNumero.setEditable(false);

        txtTrabaja.setEditable(false);

        txtContrato.setEditable(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        crear.setText("Crear");
        crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearActionPerformed(evt);
            }
        });

        actualizar.setText("Actualizar");
        actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarActionPerformed(evt);
            }
        });

        eliminar.setText("Eliminar");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(crear)
                .addGap(18, 18, 18)
                .addComponent(actualizar)
                .addGap(18, 18, 18)
                .addComponent(eliminar)
                .addGap(18, 18, 18)
                .addComponent(cancelar)
                .addGap(18, 18, 18)
                .addComponent(salir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crear)
                    .addComponent(actualizar)
                    .addComponent(eliminar)
                    .addComponent(cancelar)
                    .addComponent(salir))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTrabaja, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                            .addComponent(txtEmpresa))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTrabaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearActionPerformed
        try{
            Sanci e=new Sanci();
            String dcausa=causa.getText().toUpperCase();
            if(dcausa.isEmpty()){
                JOptionPane.showMessageDialog(this, "Se requiere una causa (1), verifique .....");
                Iniciar();
            }
            else{
                if(dcausa.trim().equals("")){
                    JOptionPane.showMessageDialog(this, "Se requiere una causa (2), verifique .....");
                    causa.setText("");
                    causa.grabFocus();
                }
                else{
                    if(fechec.getDate() == null){
                        JOptionPane.showMessageDialog(this, "Se requiere la fecha de los hechos, verifique .....");
                        fechec.grabFocus();
                    }
                    else{
                        String ds=diasan.getText().toUpperCase();
                        if(ds.isEmpty()){
                            JOptionPane.showMessageDialog(this, "Se requieren los días de sanción (1), verifique .....");
                            diasan.grabFocus();
                        }
                        else{
                            if(ds.trim().equals("")){
                                JOptionPane.showMessageDialog(this, "Se requieren los días de sanción (2), verifique .....");
                                diasan.setText("");
                                diasan.grabFocus();
                            }
                            else{
                                if(finsan.getDate() == null){
                                    JOptionPane.showMessageDialog(this, "Se requiere la fecha de inicio de la sanción, verifique .....");
                                    finsan.grabFocus();
                                }
                                else{
                                    if(ftesan.getDate() == null){
                                        JOptionPane.showMessageDialog(this, "Se requiere la fecha de término de la sanción, verifique .....");
                                        ftesan.grabFocus();
                                    }
                                    else{
                                        String ddescrip=descrip.getText().toUpperCase();
                                        int añoh=fechec.getCalendar().get(Calendar.YEAR);
                                        int mesh=fechec.getCalendar().get(Calendar.MONTH)+1;
                                        int diah=fechec.getCalendar().get(Calendar.DAY_OF_MONTH);
                                        String dfechec=(añoh+"/"+mesh+"/"+diah);
                                        String dhorhec=horhec.getText().toUpperCase();
                                        String dsangen=sangen.getText().toUpperCase();
                                        int ddiasan=Integer.parseInt(diasan.getText().toUpperCase());
                                        int añoi=finsan.getCalendar().get(Calendar.YEAR);
                                        int mesi=finsan.getCalendar().get(Calendar.MONTH)+1;
                                        int diai=finsan.getCalendar().get(Calendar.DAY_OF_MONTH);
                                        String dfinsan=(añoi+"/"+mesi+"/"+diai);
                                        int añot=ftesan.getCalendar().get(Calendar.YEAR);
                                        int mest=ftesan.getCalendar().get(Calendar.MONTH)+1;
                                        int diat=ftesan.getCalendar().get(Calendar.DAY_OF_MONTH);
                                        String dftesan=(añot+"/"+mest+"/"+diat);
                                        String dautoriza=autoriza.getSelectedItem().toString();
                                        String dnomaut=nomaut.getText().toUpperCase();
                                        String dpath=path.getText().toUpperCase();
                                        e.Agregar(Contr.getNumTrabaja(), Contr.getNomTrabaja(), Contr.getRfcTrabaja(), Contr.getPatTrabaja(),
                                                  Contr.getStcTrabaja(), Contr.getFesTrabaja(), Contr.getNcoTrabaja(), Contr.getCemTrabaja(),
                                                  Contr.getNemTrabaja(), Contr.getCdeTrabaja(), Contr.getNdeTrabaja(), Contr.getCseTrabaja(),
                                                  Contr.getNseTrabaja(), Contr.getCcaTrabaja(), Contr.getNcaTrabaja(), Contr.getSxdTrabaja(),
                                                  Contr.getCtuTrabaja(), Contr.getNtuTrabaja(), Contr.getCtiTrabaja(), Contr.getNtiTrabaja(),
                                                  Contr.getFinTrabaja(), Contr.getFteTrabaja(), dcausa, ddescrip, dfechec, dhorhec, dsangen,
                                                  ddiasan, dfinsan, dftesan, dautoriza, dnomaut, dpath, Acceso.getClaveUsuario());
                                        JOptionPane.showMessageDialog(this, "Registro creado .....");
                                        Iniciar();
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
        catch(NumberFormatException nfe){
            System.out.println("No hay fecha: "+nfe);
        }
    }//GEN-LAST:event_crearActionPerformed

    private void actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarActionPerformed
        try{
            Sanci e=new Sanci();
            String dcausa=causa.getText().toUpperCase();
            if(dcausa.isEmpty()){
                JOptionPane.showMessageDialog(this, "Se requiere una causa (1), verifique .....");
                Iniciar();
            }
            else{
                if(dcausa.trim().equals("")){
                    JOptionPane.showMessageDialog(this, "Se requiere una causa (2), verifique .....");
                    causa.setText("");
                    causa.grabFocus();
                }
                else{
                    if(fechec.getDate() == null){
                        JOptionPane.showMessageDialog(this, "Se requiere la fecha de los hechos, verifique .....");
                        fechec.grabFocus();
                    }
                    else{
                        String ds=diasan.getText().toUpperCase();
                        if(ds.isEmpty()){
                            JOptionPane.showMessageDialog(this, "Se requieren los días de sanción (1), verifique .....");
                            diasan.grabFocus();
                        }
                        else{
                            if(ds.trim().equals("")){
                                JOptionPane.showMessageDialog(this, "Se requieren los días de sanción (2), verifique .....");
                                diasan.setText("");
                                diasan.grabFocus();
                            }
                            else{
                                if(finsan.getDate() == null){
                                    JOptionPane.showMessageDialog(this, "Se requiere la fecha de inicio de la sanción, verifique .....");
                                    finsan.grabFocus();
                                }
                                else{
                                    if(ftesan.getDate() == null){
                                        JOptionPane.showMessageDialog(this, "Se requiere la fecha de término de la sanción, verifique .....");
                                        ftesan.grabFocus();
                                    }
                                    else{
                                        String ddescrip=descrip.getText().toUpperCase();
                                        int añoh=fechec.getCalendar().get(Calendar.YEAR);
                                        int mesh=fechec.getCalendar().get(Calendar.MONTH)+1;
                                        int diah=fechec.getCalendar().get(Calendar.DAY_OF_MONTH);
                                        String dfechec=(añoh+"/"+mesh+"/"+diah);
                                        String dhorhec=horhec.getText().toUpperCase();
                                        String dsangen=sangen.getText().toUpperCase();
                                        int ddiasan=Integer.parseInt(diasan.getText().toUpperCase());
                                        int añoi=finsan.getCalendar().get(Calendar.YEAR);
                                        int mesi=finsan.getCalendar().get(Calendar.MONTH)+1;
                                        int diai=finsan.getCalendar().get(Calendar.DAY_OF_MONTH);
                                        String dfinsan=(añoi+"/"+mesi+"/"+diai);
                                        int añot=ftesan.getCalendar().get(Calendar.YEAR);
                                        int mest=ftesan.getCalendar().get(Calendar.MONTH)+1;
                                        int diat=ftesan.getCalendar().get(Calendar.DAY_OF_MONTH);
                                        String dftesan=(añot+"/"+mest+"/"+diat);
                                        String dautoriza=autoriza.getSelectedItem().toString();
                                        String dnomaut=nomaut.getText().toUpperCase();
                                        String dpath=path.getText().toUpperCase();
                                        e.Actualizar(Contr.getNumTrabaja(), Contr.getNomTrabaja(), Contr.getRfcTrabaja(), Contr.getPatTrabaja(),
                                                     Contr.getStcTrabaja(), Contr.getFesTrabaja(), Contr.getNcoTrabaja(), Contr.getCemTrabaja(),
                                                     Contr.getNemTrabaja(), Contr.getCdeTrabaja(), Contr.getNdeTrabaja(), Contr.getCseTrabaja(),
                                                     Contr.getNseTrabaja(), Contr.getCcaTrabaja(), Contr.getNcaTrabaja(), Contr.getSxdTrabaja(),
                                                     Contr.getCtuTrabaja(), Contr.getNtuTrabaja(), Contr.getCtiTrabaja(), Contr.getNtiTrabaja(),
                                                     Contr.getFinTrabaja(), Contr.getFteTrabaja(), dcausa, ddescrip, dfechec, dhorhec, dsangen,
                                                     ddiasan, dfinsan, dftesan, dautoriza, dnomaut, dpath, Acceso.getClaveUsuario());
                                        JOptionPane.showMessageDialog(this, "Registro creado .....");
                                        Iniciar();
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
        catch(NumberFormatException nfe){
            System.out.println("No hay fecha: "+nfe);
        }
    }//GEN-LAST:event_actualizarActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        Sanci e=new Sanci();
        int dnumtra=Contr.getNumTrabaja();
        String dnumcon=Contr.getNcoTrabaja();
        String dcausa=causa.getText().toUpperCase();
        if(dcausa.isEmpty()){
            JOptionPane.showMessageDialog(this, "Se requiere una causa (1), verifique .....");
            Iniciar();
        }
        else{
            if(dcausa.trim().equals("")){
                JOptionPane.showMessageDialog(this, "Se requiere una causa (2), verifique .....");
                causa.setText("");
                causa.grabFocus();
            }
            else{
                if(fechec.getDate() == null){
                    JOptionPane.showMessageDialog(this, "Se requiere la fecha de los hechos, verifique .....");
                    fechec.grabFocus();
                }
                else{
                    int añoh=fechec.getCalendar().get(Calendar.YEAR);
                    int mesh=fechec.getCalendar().get(Calendar.MONTH)+1;
                    int diah=fechec.getCalendar().get(Calendar.DAY_OF_MONTH);
                    String dfechec=(añoh+"/"+mesh+"/"+diah);
                    String dsangen=sangen.getText().toUpperCase();
                    String dautoriza=autoriza.getSelectedItem().toString();
                    String dnomaut=nomaut.getText().toUpperCase();
                    e.Eliminar(dnumtra, dnumcon, dcausa, dfechec, dsangen, dautoriza, dnomaut, Acceso.getClaveUsuario());
                    JOptionPane.showMessageDialog(this, "Registro eliminado .....");
                    Iniciar();
                }
            }
        }
    }//GEN-LAST:event_eliminarActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        Iniciar();
    }//GEN-LAST:event_cancelarActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        this.dispose();
    }//GEN-LAST:event_salirActionPerformed

    private void tablasanciMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablasanciMouseClicked
        DefaultTableModel modelo= (DefaultTableModel) tablasanci.getModel();
        causa.setText(modelo.getValueAt(tablasanci.getSelectedRow(), 0)+"");
        String fsan = (modelo.getValueAt(tablasanci.getSelectedRow(), 1)+"");
        if("null".equals(fsan)){
            System.out.println("La fecha de los hechos esta vacia .....");
        }
        else{
            SimpleDateFormat formatofecha1=new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            try{
                Date fecha1 = formatofecha1.parse(fsan);
                fechec.setDate(fecha1);
            }
            catch(ParseException pe1){
            System.out.println("Error Parse1: "+pe1.getMessage());
            }
        }
        sangen.setText(modelo.getValueAt(tablasanci.getSelectedRow(), 2)+"");
        autoriza.setSelectedItem(modelo.getValueAt(tablasanci.getSelectedRow(), 3)+"");
        nomaut.setText(modelo.getValueAt(tablasanci.getSelectedRow(), 4)+"");

        Sanci com=new Sanci();
        int dnumtra=Contr.getNumTrabaja();
        String dnumcon=Contr.getNcoTrabaja();
        String dcausa=causa.getText().toUpperCase();
        int añoh=fechec.getCalendar().get(Calendar.YEAR);
        int mesh=fechec.getCalendar().get(Calendar.MONTH)+1;
        int diah=fechec.getCalendar().get(Calendar.DAY_OF_MONTH);
        String dfechec=(añoh+"/"+mesh+"/"+diah);
        String dsangen=sangen.getText().toUpperCase();
        String dautoriza=autoriza.getSelectedItem().toString();
        String dnomaut=nomaut.getText().toUpperCase();
        Object[] datos1=com.Comple(dnumtra, dnumcon, dcausa, dfechec, dsangen, dautoriza, dnomaut);
        descrip.setText(datos1[0]+"");
        horhec.setText(datos1[1]+"");
        diasan.setText(datos1[2]+"");
        String fini = datos1[3]+"";
        if("null".equals(fini)){
            System.out.println("La fecha de inicio de la sanción esta vacia .....");
        }
        else{
            SimpleDateFormat formatofecha2=new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            try{
                Date fecha2 = formatofecha2.parse(fini);
                finsan.setDate(fecha2);
            }
            catch(ParseException pe2){
            System.out.println("Error Parse2: "+pe2.getMessage());
            }
        }
        String fter = datos1[4]+"";
        if("null".equals(fter)){
            System.out.println("La fecha de término de la sanción esta vacia .....");
        }
        else{
            SimpleDateFormat formatofecha3=new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            try{
                Date fecha3 = formatofecha3.parse(fter);
                ftesan.setDate(fecha3);
            }
            catch(ParseException pe3){
            System.out.println("Error Parse3: "+pe3.getMessage());
            }
        }
        path.setText(datos1[5]+"");
        status.setText(datos1[6]+"");
        fecha.setText(datos1[7]+"");
        usuario.setText(datos1[8]+"");
        crear.setEnabled(false);
        causa.setEnabled(false);
        fechec.setEnabled(false);
    }//GEN-LAST:event_tablasanciMouseClicked

    private void diasanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_diasanKeyTyped
        char car = evt.getKeyChar();
        if((car<'0' || car>'9'))
        {
            evt.consume();
        }
    }//GEN-LAST:event_diasanKeyTyped

    private void pathMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pathMouseClicked
        Sanci.setPathUsuario(path.getText().toUpperCase());
        VSanciConsola object=new VSanciConsola();
        object.setVisible(true);
    }//GEN-LAST:event_pathMouseClicked

    private void autorizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autorizaActionPerformed
        String claveseleccionada=autoriza.getSelectedItem()+"";
        Sanci e=new Sanci();
        Object[] datos2=e.Empresa(claveseleccionada);
        nomaut.setText(datos2[0]+"");
    }//GEN-LAST:event_autorizaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SanciConsola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SanciConsola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SanciConsola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SanciConsola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SanciConsola().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizar;
    private javax.swing.JComboBox autoriza;
    private javax.swing.JButton cancelar;
    private javax.swing.JTextField causa;
    private javax.swing.JButton crear;
    private javax.swing.JTextField descrip;
    private javax.swing.JTextField diasan;
    private javax.swing.JButton eliminar;
    private javax.swing.JTextField fecha;
    private com.toedter.calendar.JDateChooser fechec;
    private com.toedter.calendar.JDateChooser finsan;
    private com.toedter.calendar.JDateChooser ftesan;
    private javax.swing.JTextField horhec;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nomaut;
    private javax.swing.JTextField path;
    private javax.swing.JButton salir;
    private javax.swing.JTextField sangen;
    private javax.swing.JTextField status;
    private javax.swing.JTable tablasanci;
    private javax.swing.JTextField txtContrato;
    private javax.swing.JTextField txtEmpresa;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtTrabaja;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
