
package sirh;

import java.awt.Image;
import java.net.MalformedURLException;
import java.net.URL;
import java.text.*;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class TrabaAConsola extends javax.swing.JFrame {


    public TrabaAConsola() throws MalformedURLException {
        initComponents();
        setResizable(false);
        setDefaultCloseOperation(0);
        Iniciar();
    }

    private void Iniciar() throws MalformedURLException{
        rfc.setText("");
        curp.setText("");
        paterno.setText("");
        materno.setText("");
        nombre.setText("");
        nacim.setDate(null);
        observa.setText("");
        path.setText("ftp://sirh.dyndns.org/Trabajadores/SINFOTO.GIF");
        String lugarImagen="ftp://sirh.dyndns.org/Trabajadores/SINFOTO.GIF";
        lugarImagen=path.getText();
        //Image icon=new ImageIcon(lugarImagen).getImage().getScaledInstance(txtImagen.getWidth(), txtImagen.getWidth(), Image.SCALE_DEFAULT);
        //Icon imagen=new ImageIcon(icon);
        //txtImagen.setIcon(imagen);
        Image icon= new javax.swing.ImageIcon(new URL(lugarImagen)).getImage().getScaledInstance(txtImagen.getWidth(), txtImagen.getWidth(), Image.SCALE_DEFAULT);
        Icon imagen=new ImageIcon(icon);
        txtImagen.setIcon(imagen);
        
        sexo.removeAllItems();
        sexo.addItem("");
        TrabaA e=new TrabaA();
        e.LlenarSexo(sexo);
        nacion.removeAllItems();
        nacion.addItem("");
        TrabaA e1=new TrabaA();
        e1.LlenarNacion(nacion);
        crear.setEnabled(true);
        rfc.setEnabled(true);
        rfc.grabFocus();
       
        fecha.setText(fechaActual());
        usuario.setText(Acceso.getClaveUsuario());
        txtNombre.setText(Acceso.getNombreUsuario());
        txtEmpresa.setText(Acceso.getEmpresaUsuario());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        rfc = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        curp = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        paterno = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        materno = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        nacim = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        sexo = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        nacion = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        path = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        observa = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        fecha = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        datper = new javax.swing.JButton();
        documenta = new javax.swing.JButton();
        escolar = new javax.swing.JButton();
        familiar = new javax.swing.JButton();
        exper = new javax.swing.JButton();
        benefi = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtEmpresa = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        txtImagen = new javax.swing.JLabel();
        crear = new javax.swing.JButton();
        actualizar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SNTIAISCRM Sistema de Recursos Humanos");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jLabel2.setForeground(new java.awt.Color(204, 0, 51));
        jLabel2.setText("RFC:");

        rfc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                rfcFocusLost(evt);
            }
        });

        jLabel3.setText("CURP:");

        jLabel4.setText("Apellido Paterno:");

        jLabel5.setText("Apellido Materno:");

        jLabel6.setText("Nombre:");

        jLabel7.setForeground(new java.awt.Color(204, 0, 51));
        jLabel7.setText("Nacimiento:");

        jLabel8.setText("Sexo:");

        jLabel9.setText("Nacionalidad:");

        jLabel10.setText("Path Foto:");

        path.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                pathFocusLost(evt);
            }
        });

        jLabel11.setText("Observa:");

        observa.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel12.setText("Fecha:");

        fecha.setEditable(false);

        jLabel13.setText("Usuario:");

        usuario.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(materno)
                    .addComponent(curp)
                    .addComponent(paterno)
                    .addComponent(nombre)
                    .addComponent(nacim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sexo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nacion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(path)
                    .addComponent(fecha)
                    .addComponent(usuario)
                    .addComponent(rfc)
                    .addComponent(observa, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(rfc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(curp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(paterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(materno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(nacim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(nacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(path, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(observa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        datper.setForeground(new java.awt.Color(0, 0, 153));
        datper.setText("Datos Personales");
        datper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datperActionPerformed(evt);
            }
        });

        documenta.setForeground(new java.awt.Color(0, 0, 153));
        documenta.setText("Documentación");
        documenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                documentaActionPerformed(evt);
            }
        });

        escolar.setForeground(new java.awt.Color(0, 0, 153));
        escolar.setText("Escolaridad");
        escolar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                escolarActionPerformed(evt);
            }
        });

        familiar.setForeground(new java.awt.Color(0, 0, 153));
        familiar.setText("Familiares");
        familiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                familiarActionPerformed(evt);
            }
        });

        exper.setForeground(new java.awt.Color(0, 0, 153));
        exper.setText("Experiencia");
        exper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                experActionPerformed(evt);
            }
        });

        benefi.setForeground(new java.awt.Color(0, 0, 153));
        benefi.setText("Beneficiarios");
        benefi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                benefiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(datper)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(documenta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(escolar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(familiar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exper)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(benefi)
                .addGap(30, 30, 30))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(datper)
                    .addComponent(documenta)
                    .addComponent(escolar)
                    .addComponent(familiar)
                    .addComponent(exper)
                    .addComponent(benefi))
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("MOVIMIENTOS DE ASPIRANTES");

        txtEmpresa.setEditable(false);
        txtEmpresa.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        txtEmpresa.setForeground(new java.awt.Color(204, 0, 0));
        txtEmpresa.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtEmpresa.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtNombre.setEditable(false);
        txtNombre.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(204, 0, 0));
        txtNombre.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtNombre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        txtImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtImagen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        crear.setText("Crear");
        crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearActionPerformed(evt);
            }
        });

        actualizar.setText("Actualizar");
        actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarActionPerformed(evt);
            }
        });

        eliminar.setText("Eliminar");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(actualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(crear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(salir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(crear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(actualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(salir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearActionPerformed
        TrabaA e=new TrabaA();
        String drfc=rfc.getText().toUpperCase();
        if(drfc.isEmpty()){
            try {
                JOptionPane.showMessageDialog(this, "Se requiere un Rfc, verifique .....");
                Iniciar();
            } catch (MalformedURLException ex) {
                Logger.getLogger(TrabaAConsola.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            if(nacim.getDate() == null){
                JOptionPane.showMessageDialog(this, "Se requiere una fecha de nacimiento, verifique .....");
                nacim.grabFocus();
            }
            else{
                try {
                    String dcurp=curp.getText().toUpperCase();
                    String dpaterno=paterno.getText().toUpperCase();
                    String dmaterno=materno.getText().toUpperCase();
                    String dnombre=nombre.getText().toUpperCase();
                    String dpath=path.getText().toUpperCase();
                    int año=nacim.getCalendar().get(Calendar.YEAR);
                    int mes=nacim.getCalendar().get(Calendar.MONTH)+1;
                    int dia=nacim.getCalendar().get(Calendar.DAY_OF_MONTH);
                    String dnacim=(año+"/"+mes+"/"+dia);
                    String dsexo=sexo.getSelectedItem().toString();
                    String dnacion=nacion.getSelectedItem().toString();
                    String dobserva=observa.getText().toUpperCase();
                    e.Agregar(drfc, dcurp, dpaterno, dmaterno, dnombre, dpath, dnacim, dsexo, dnacion, dobserva, Acceso.getClaveUsuario());
                    JOptionPane.showMessageDialog(this, "Registro creado .....");  
                    Iniciar();
                } catch (MalformedURLException ex) {
                    Logger.getLogger(TrabaAConsola.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } 
    }//GEN-LAST:event_crearActionPerformed

    private void actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarActionPerformed
        TrabaA e=new TrabaA();
        String drfc=rfc.getText().toUpperCase();
        String dcurp=curp.getText().toUpperCase();
        String dpaterno=paterno.getText().toUpperCase();
        String dmaterno=materno.getText().toUpperCase();
        String dnombre=nombre.getText().toUpperCase();
        String dpath=path.getText().toUpperCase();
        if(nacim.getDate() == null){
            JOptionPane.showMessageDialog(this, "Se requiere una fecha de nacimiento, verifique .....");
            nacim.grabFocus();
        }
        else{
            try {
                int año=nacim.getCalendar().get(Calendar.YEAR);
                int mes=nacim.getCalendar().get(Calendar.MONTH)+1;
                int dia=nacim.getCalendar().get(Calendar.DAY_OF_MONTH);
                String dnacim=(año+"/"+mes+"/"+dia);
                String dsexo=sexo.getSelectedItem().toString();
                String dnacion=nacion.getSelectedItem().toString();
                String dobserva=observa.getText().toUpperCase();
                e.Actualizar(drfc, dcurp, dpaterno, dmaterno, dnombre, dpath, dnacim, dsexo, dnacion, dobserva, Acceso.getClaveUsuario());
                JOptionPane.showMessageDialog(this, "Registro actualizado .....");
                Iniciar();
            } catch (MalformedURLException ex) {
                Logger.getLogger(TrabaAConsola.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_actualizarActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        String drfc=rfc.getText().toUpperCase();
        int ax = JOptionPane.showConfirmDialog(null, "Este proceso eliminará toda la información del aspirante \na trabajador de todo el sistema SIRH. \nDesea Continuar ?");
        if(ax == JOptionPane.YES_OPTION){
            try {
                TrabaA e01=new TrabaA();
                e01.Eliminar01(drfc, Acceso.getClaveUsuario());
                TrabaA e02=new TrabaA();
                e02.Eliminar02(drfc, Acceso.getClaveUsuario());
                TrabaA e03=new TrabaA();
                e03.Eliminar03(drfc, Acceso.getClaveUsuario());
                TrabaA e04=new TrabaA();
                e04.Eliminar04(drfc, Acceso.getClaveUsuario());
                TrabaA e05=new TrabaA();
                e05.Eliminar05(drfc, Acceso.getClaveUsuario());
                TrabaA e06=new TrabaA();
                e06.Eliminar06(drfc, Acceso.getClaveUsuario());
                TrabaA e07=new TrabaA();
                e07.Eliminar07(drfc, Acceso.getClaveUsuario());
                JOptionPane.showMessageDialog(this, "Aspirante a Trabajador eliminado .....");
                Iniciar();
            } catch (MalformedURLException ex) {
                Logger.getLogger(TrabaAConsola.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else if(ax == JOptionPane.NO_OPTION){
            try {
                Iniciar();
            } catch (MalformedURLException ex) {
                Logger.getLogger(TrabaAConsola.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_eliminarActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        try {
            Iniciar();
        } catch (MalformedURLException ex) {
            Logger.getLogger(TrabaAConsola.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cancelarActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        this.dispose();
    }//GEN-LAST:event_salirActionPerformed

    private void pathFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pathFocusLost
        try {
            String lugarImagen="";
            lugarImagen=path.getText();
            //Image icon=new ImageIcon(lugarImagen).getImage().getScaledInstance(txtImagen.getWidth(), txtImagen.getWidth(), Image.SCALE_DEFAULT);
            //Icon imagen=new ImageIcon(icon);
            //txtImagen.setIcon(imagen);
            
            Image icon= new javax.swing.ImageIcon(new URL(lugarImagen)).getImage().getScaledInstance(txtImagen.getWidth(), txtImagen.getWidth(), Image.SCALE_DEFAULT);
            Icon imagen=new ImageIcon(icon);
            txtImagen.setIcon(imagen);
        } catch (MalformedURLException ex) {
            Logger.getLogger(TrabaAConsola.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_pathFocusLost

    private void rfcFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rfcFocusLost
        String Rfc = rfc.getText().toUpperCase();
        
        if(Rfc.isEmpty()){
            JOptionPane.showMessageDialog(this, "Necesita proporcionar un Rfc válido, verifique .....");
            rfc.grabFocus();
        }
        else{
            TrabaA val= new TrabaA();
            Object[] datos=val.Datos(Rfc);
            String checa=datos[0]+"";
            TrabaA.setRfcUsuario(rfc.getText());
            
            if(checa.trim().equals("null")){
                JOptionPane.showMessageDialog(this, "Este RFC no existe .....");
            }
            else{
                try{
                    rfc.setText(datos[0]+"");
                    curp.setText(datos[1]+"");
                    paterno.setText(datos[2]+"");
                    materno.setText(datos[3]+"");
                    nombre.setText(datos[4]+"");
                    TrabaA.setNomTrabaja(nombre.getText()+" "+paterno.getText()+" "+materno.getText());
                    path.setText(datos[5]+"");
                    String fnacim = datos[6]+"";
                    SimpleDateFormat formatofecha=new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
                    try{
                        Date fecha1 = formatofecha.parse(fnacim);
                        nacim.setDate(fecha1);
                    }
                    catch(ParseException pe1){
                        System.out.println("Error Parse1: "+pe1.getMessage());
                    }
                    sexo.setSelectedItem(datos[7]+"");
                    nacion.setSelectedItem(datos[8]+"");
                    observa.setText(datos[9]+"");
                    String freg = datos[10]+"";
                    fecha.setText(freg);
                    usuario.setText(datos[11]+"");
                    String lugarImagen="";
                    lugarImagen=path.getText();
                    //Image icon=new ImageIcon(lugarImagen).getImage().getScaledInstance(txtImagen.getWidth(), txtImagen.getWidth(), Image.SCALE_DEFAULT);
                    //Icon imagen=new ImageIcon(icon);
                    //txtImagen.setIcon(imagen);
                    
                    Image icon= new javax.swing.ImageIcon(new URL(lugarImagen)).getImage().getScaledInstance(txtImagen.getWidth(), txtImagen.getWidth(), Image.SCALE_DEFAULT);
                    Icon imagen=new ImageIcon(icon);
                    txtImagen.setIcon(imagen);
                    crear.setEnabled(false);
                    rfc.setEnabled(false);
                    curp.grabFocus();
                }
                catch(MalformedURLException ex){
                    Logger.getLogger(TrabaAConsola.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_rfcFocusLost

    private void datperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datperActionPerformed
        String drfc=rfc.getText().toUpperCase();
        if(drfc.isEmpty()){
            try {
                Iniciar();
            } catch (MalformedURLException ex) {
                Logger.getLogger(TrabaAConsola.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            DatosAConsola object=new DatosAConsola();
            object.setLocationRelativeTo(null);
            object.setVisible(true);
        }
    }//GEN-LAST:event_datperActionPerformed

    private void documentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_documentaActionPerformed
        String drfc=rfc.getText().toUpperCase();
        if(drfc.isEmpty()){
            try {
                Iniciar();
            } catch (MalformedURLException ex) {
                Logger.getLogger(TrabaAConsola.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            DocumAConsola object=new DocumAConsola();
            object.setLocationRelativeTo(null);
            object.setVisible(true);
        }
    }//GEN-LAST:event_documentaActionPerformed

    private void escolarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_escolarActionPerformed
        String drfc=rfc.getText().toUpperCase();
        if(drfc.isEmpty()){
            try {
                Iniciar();
            } catch (MalformedURLException ex) {
                Logger.getLogger(TrabaAConsola.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            EscolAConsola object=new EscolAConsola();
            object.setLocationRelativeTo(null);
            object.setVisible(true);
        }
    }//GEN-LAST:event_escolarActionPerformed

    private void benefiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_benefiActionPerformed
        String drfc=rfc.getText().toUpperCase();
        if(drfc.isEmpty()){
            try {
                Iniciar();
            } catch (MalformedURLException ex) {
                Logger.getLogger(TrabaAConsola.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            BenefAConsola object=new BenefAConsola();
            object.setLocationRelativeTo(null);
            object.setVisible(true);
        }
    }//GEN-LAST:event_benefiActionPerformed

    private void familiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_familiarActionPerformed
        String drfc=rfc.getText().toUpperCase();
        if(drfc.isEmpty()){
            try {
                Iniciar();
            } catch (MalformedURLException ex) {
                Logger.getLogger(TrabaAConsola.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            FamilAConsola object=new FamilAConsola();
            object.setLocationRelativeTo(null);
            object.setVisible(true);
        }
    }//GEN-LAST:event_familiarActionPerformed

    private void experActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_experActionPerformed
        String drfc=rfc.getText().toUpperCase();
        if(drfc.isEmpty()){
            try {
                Iniciar();
            } catch (MalformedURLException ex) {
                Logger.getLogger(TrabaAConsola.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            ExperAConsola object=new ExperAConsola();
            object.setLocationRelativeTo(null);
            object.setVisible(true);
        }
    }//GEN-LAST:event_experActionPerformed

    public static String fechaActual(){
        Date fecha= new Date();
        SimpleDateFormat formatoFecha=new SimpleDateFormat("dd/MM/YYYY HH:mm:ss");
        return formatoFecha.format(fecha);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrabaAConsola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrabaAConsola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrabaAConsola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrabaAConsola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new TrabaAConsola().setVisible(true);
                } catch (MalformedURLException ex) {
                    Logger.getLogger(TrabaAConsola.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizar;
    private javax.swing.JButton benefi;
    private javax.swing.JButton cancelar;
    private javax.swing.JButton crear;
    private javax.swing.JTextField curp;
    private javax.swing.JButton datper;
    private javax.swing.JButton documenta;
    private javax.swing.JButton eliminar;
    private javax.swing.JButton escolar;
    private javax.swing.JButton exper;
    private javax.swing.JButton familiar;
    private javax.swing.JTextField fecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField materno;
    private com.toedter.calendar.JDateChooser nacim;
    private javax.swing.JComboBox nacion;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField observa;
    private javax.swing.JTextField paterno;
    private javax.swing.JTextField path;
    private javax.swing.JTextField rfc;
    private javax.swing.JButton salir;
    private javax.swing.JComboBox sexo;
    private javax.swing.JTextField txtEmpresa;
    private javax.swing.JLabel txtImagen;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
