
package sirh;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

public class UnidaConsola extends javax.swing.JFrame {


    public UnidaConsola() {
        initComponents();
        setDefaultCloseOperation(0);
        Iniciar();
    }
    
    private void Limpiar(JTable tabla){
        while(tabla.getRowCount()>0){
            ((DefaultTableModel) tabla.getModel()).removeRow(0);
        }
    }
    
    private void Iniciar(){
        Limpiar(tablaunida);
        DefaultTableModel modelo=(DefaultTableModel) tablaunida.getModel();
        Unida e1=new Unida();
        e1.LlenarDatos(modelo);
        numuni.setText("");
        cveemp.removeAllItems();
        cveemp.addItem("");
        Unida e2=new Unida();
        e2.LlenarCveempresa(cveemp);
        nomemp.setText("");
        marca.setText("");
        modello.setText("");
        año.setText("");
        capa.setText("");
        placas.setText("");
        propie.setText("");
        ultman.setDate(null);
        Limpiar(tablaunida1);
        busnum.setText("");
        busmar.setText("");
        buspla.setText("");
        
        fecha.setText(fechaActual());
        usuario.setText(Acceso.getClaveUsuario());
        txtNombre.setText(Acceso.getNombreUsuario());
        txtEmpresa.setText(Acceso.getEmpresaUsuario());
        crear.setEnabled(true);
        numuni.setEnabled(true);
        cveemp.setEnabled(true);
        
    }
    
    public static String fechaActual(){
        Date fecha= new Date();
        SimpleDateFormat formatoFecha=new SimpleDateFormat("dd/MM/YYYY HH:mm:ss");
        return formatoFecha.format(fecha);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtEmpresa = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaunida1 = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        busnum = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        busmar = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        buspla = new javax.swing.JTextField();
        salir1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaunida = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        numuni = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cveemp = new javax.swing.JComboBox();
        nomemp = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        marca = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        modello = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        año = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        capa = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        placas = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        propie = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        ultman = new com.toedter.calendar.JDateChooser();
        crear = new javax.swing.JButton();
        actualizar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        fecha = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SNTIAISCRM Sistema de Recursos Humanos");
        setMaximumSize(new java.awt.Dimension(900, 500));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("UNIDADES DE TRANSPORTE DE PERSONAL");

        txtEmpresa.setEditable(false);
        txtEmpresa.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        txtEmpresa.setForeground(new java.awt.Color(204, 0, 0));
        txtEmpresa.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtEmpresa.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtNombre.setEditable(false);
        txtNombre.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(204, 0, 0));
        txtNombre.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtNombre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tablaunida1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Num. Unidad", "Cve Empresa", "Nombre Empresa", "Marca", "Modelo", "Año", "Capacidad", "Placas", "Propietario", "Ultimo Mntto", "Status", "Ultimo Fecha", "Ultimo Usuario"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaunida1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaunida1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaunida1);

        jLabel13.setText("Número Unidad:");

        busnum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                busnumMouseClicked(evt);
            }
        });
        busnum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                busnumKeyPressed(evt);
            }
        });

        jLabel14.setText("Marca:");

        busmar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                busmarMouseClicked(evt);
            }
        });
        busmar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                busmarKeyPressed(evt);
            }
        });

        jLabel15.setText("Placas:");

        buspla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                busplaMouseClicked(evt);
            }
        });
        buspla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                busplaKeyPressed(evt);
            }
        });

        salir1.setText("Salir");
        salir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salir1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(busnum, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(busmar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buspla, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 213, Short.MAX_VALUE)
                .addComponent(salir1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(busnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(busmar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(buspla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salir1))
                .addContainerGap(353, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(46, 46, 46)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jTabbedPane1.addTab("Búsqueda", jPanel1);

        tablaunida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Num. Unidad", "Cve Empresa", "Nombre Empresa", "Marca", "Modelo", "Año", "Capacidad", "Placas", "Propietario", "Ultimo Mntto", "Status", "Ultimo Fecha", "Ultimo Usuario"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaunida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaunidaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaunida);

        jLabel2.setForeground(new java.awt.Color(204, 0, 51));
        jLabel2.setText("Número de Unidad:");

        jLabel3.setForeground(new java.awt.Color(204, 0, 51));
        jLabel3.setText("Clave Empresa:");

        cveemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cveempActionPerformed(evt);
            }
        });

        nomemp.setEditable(false);

        jLabel4.setText("Marca:");

        jLabel5.setText("Modelo:");

        jLabel6.setText("Año:");

        jLabel7.setText("Capacidad:");

        jLabel8.setText("Placas:");

        jLabel9.setText("Propietario:");

        jLabel10.setForeground(new java.awt.Color(204, 0, 51));
        jLabel10.setText("Ultimo Mntto:");

        crear.setText("Crear");
        crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearActionPerformed(evt);
            }
        });

        actualizar.setText("Actualizar");
        actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarActionPerformed(evt);
            }
        });

        eliminar.setText("Eliminar");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        jLabel11.setText("Fecha:");

        fecha.setEditable(false);

        jLabel12.setText("Usuario:");

        usuario.setEditable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(usuario, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
                            .addComponent(numuni)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(cveemp, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nomemp))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(año, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 10, Short.MAX_VALUE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(marca)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel5)
                                        .addGap(26, 26, 26)))
                                .addGap(2, 2, 2)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(modello)
                                    .addComponent(capa, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)))
                            .addComponent(placas)
                            .addComponent(propie)
                            .addComponent(ultman, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(65, 65, 65)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(actualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(crear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(salir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 187, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(numuni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(crear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cveemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(actualizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(modello, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(año, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(capa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(placas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(propie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(ultman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12)
                        .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Movimientos", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablaunidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaunidaMouseClicked
        DefaultTableModel modelo= (DefaultTableModel) tablaunida.getModel();
        numuni.setText(modelo.getValueAt(tablaunida.getSelectedRow(), 0)+"");
        cveemp.setSelectedItem(modelo.getValueAt(tablaunida.getSelectedRow(), 1)+"");
        nomemp.setText(modelo.getValueAt(tablaunida.getSelectedRow(), 2)+"");
        marca.setText(modelo.getValueAt(tablaunida.getSelectedRow(), 3)+"");
        modello.setText(modelo.getValueAt(tablaunida.getSelectedRow(), 4)+"");
        año.setText(modelo.getValueAt(tablaunida.getSelectedRow(), 5)+"");
        capa.setText(modelo.getValueAt(tablaunida.getSelectedRow(), 6)+"");
        placas.setText(modelo.getValueAt(tablaunida.getSelectedRow(), 7)+"");
        propie.setText(modelo.getValueAt(tablaunida.getSelectedRow(), 8)+"");
        String fultman = (modelo.getValueAt(tablaunida.getSelectedRow(), 9)+"");
        if("null".equals(fultman)){
            System.out.println("La fecha del último mantenimento esta vacia .....");
        }
        else{
            SimpleDateFormat formatofecha1=new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            try{
                Date fecha1 = formatofecha1.parse(fultman);
                ultman.setDate(fecha1);
            }
            catch(ParseException pe1){
            System.out.println("Error Parse1: "+pe1.getMessage());
            }
        }
        fecha.setText(modelo.getValueAt(tablaunida.getSelectedRow(), 11)+"");
        usuario.setText(modelo.getValueAt(tablaunida.getSelectedRow(), 12)+"");
        crear.setEnabled(false);
        numuni.setEnabled(false);
        cveemp.setEnabled(false);
    }//GEN-LAST:event_tablaunidaMouseClicked

    private void crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearActionPerformed
        Unida e=new Unida();
        String dnumuni = numuni.getText().toUpperCase();
        if(dnumuni.isEmpty()){
            JOptionPane.showMessageDialog(this, "Se requiere un número o clave de unidad (1), verifique .....");
            numuni.grabFocus();
        }
        else{
            if(dnumuni.trim().equals("")){
                JOptionPane.showMessageDialog(this, "Se requiere un número o clave de unidad (2), verifique .....");
                numuni.setText("");
                numuni.grabFocus();
            }
            else{
                String dcveemp = cveemp.getSelectedItem().toString();
                if(dcveemp.isEmpty()){
                    JOptionPane.showMessageDialog(this, "Se requiere una clave de empresa, verifique .....");
                    cveemp.grabFocus(); 
                }
                else{
                    if(ultman.getDate() == null){
                        JOptionPane.showMessageDialog(this, "Se requiere la fecha del último mantenimiento, verifique .....");
                        ultman.grabFocus();
                    }
                    else{
                        String dnomemp=nomemp.getText().toUpperCase();
                        int añou=ultman.getCalendar().get(Calendar.YEAR);
                        int mesu=ultman.getCalendar().get(Calendar.MONTH)+1;
                        int diau=ultman.getCalendar().get(Calendar.DAY_OF_MONTH);
                        String dultman=(añou+"/"+mesu+"/"+diau);
                        String dmarca=marca.getText().toUpperCase();
                        String dmodelo=modello.getText().toUpperCase();
                        String daño=año.getText().toUpperCase();
                        String dcapa=capa.getText().toUpperCase();
                        String dplacas=placas.getText().toUpperCase();
                        String dpropie=propie.getText().toUpperCase();
                        e.Agregar(dnumuni, dcveemp, dnomemp, dmarca, dmodelo, daño, dcapa, dplacas, dpropie, dultman, Acceso.getClaveUsuario());
                        JOptionPane.showMessageDialog(this, "Registro creado .....");
                        Iniciar();
                    }
                }
            }
        }
    }//GEN-LAST:event_crearActionPerformed

    private void actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarActionPerformed
        Unida e=new Unida();
        String dnumuni = numuni.getText().toUpperCase();
        if(dnumuni.isEmpty()){
            JOptionPane.showMessageDialog(this, "Se requiere un número o clave de unidad (1), verifique .....");
            numuni.grabFocus();
        }
        else{
            if(dnumuni.trim().equals("")){
                JOptionPane.showMessageDialog(this, "Se requiere un número o clave de unidad (2), verifique .....");
                numuni.setText("");
                numuni.grabFocus();
            }
            else{
                String dcveemp = cveemp.getSelectedItem().toString();
                if(dcveemp.isEmpty()){
                    JOptionPane.showMessageDialog(this, "Se requiere una clave de empresa, verifique .....");
                    cveemp.grabFocus(); 
                }
                else{
                    if(ultman.getDate() == null){
                        JOptionPane.showMessageDialog(this, "Se requiere la fecha del último mantenimiento, verifique .....");
                        ultman.grabFocus();
                    }
                    else{
                        String dnomemp=nomemp.getText().toUpperCase();
                        int añou=ultman.getCalendar().get(Calendar.YEAR);
                        int mesu=ultman.getCalendar().get(Calendar.MONTH)+1;
                        int diau=ultman.getCalendar().get(Calendar.DAY_OF_MONTH);
                        String dultman=(añou+"/"+mesu+"/"+diau);
                        String dmarca=marca.getText().toUpperCase();
                        String dmodelo=modello.getText().toUpperCase();
                        String daño=año.getText().toUpperCase();
                        String dcapa=capa.getText().toUpperCase();
                        String dplacas=placas.getText().toUpperCase();
                        String dpropie=propie.getText().toUpperCase();
                        e.Actualizar(dnumuni, dcveemp, dnomemp, dmarca, dmodelo, daño, dcapa, dplacas, dpropie, dultman, Acceso.getClaveUsuario());
                        JOptionPane.showMessageDialog(this, "Registro actualizado .....");
                        Iniciar();
                    }
                }
            }
        }
    }//GEN-LAST:event_actualizarActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        Unida e=new Unida();
        String dnumuni = numuni.getText().toUpperCase();
        if(dnumuni.isEmpty()){
            JOptionPane.showMessageDialog(this, "Se requiere un número o clave de unidad (1), verifique .....");
            numuni.grabFocus();
        }
        else{
            if(dnumuni.trim().equals("")){
                JOptionPane.showMessageDialog(this, "Se requiere un número o clave de unidad (2), verifique .....");
                numuni.setText("");
                numuni.grabFocus();
            }
            else{
                String dcveemp = cveemp.getSelectedItem().toString();
                if(dcveemp.isEmpty()){
                    JOptionPane.showMessageDialog(this, "Se requiere una clave de empresa, verifique .....");
                    cveemp.grabFocus(); 
                }
                else{
                    String dnomemp=nomemp.getText().toUpperCase();
                    e.Eliminar(dnumuni, dcveemp, dnomemp, Acceso.getClaveUsuario());
                    JOptionPane.showMessageDialog(this, "Registro eliminado .....");
                    Iniciar();
                }
            }
        }
    }//GEN-LAST:event_eliminarActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        Iniciar();
    }//GEN-LAST:event_cancelarActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        this.dispose();
    }//GEN-LAST:event_salirActionPerformed

    private void cveempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cveempActionPerformed
        String claveseleccionada=cveemp.getSelectedItem()+"";
        Infor e=new Infor();
        Object[] datos=e.Datos(claveseleccionada);
        nomemp.setText(datos[0]+"");
    }//GEN-LAST:event_cveempActionPerformed

    private void tablaunida1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaunida1MouseClicked
        // NO SE UTILIZA
    }//GEN-LAST:event_tablaunida1MouseClicked

    private void salir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salir1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_salir1ActionPerformed

    private void busnumKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_busnumKeyPressed
        Unida e=new Unida();
        Limpiar(tablaunida1);
        DefaultTableModel modelo= (DefaultTableModel) tablaunida1.getModel();
        e.BusNumero(modelo, busnum.getText().toUpperCase());
    }//GEN-LAST:event_busnumKeyPressed

    private void busnumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_busnumMouseClicked
        Iniciar();
    }//GEN-LAST:event_busnumMouseClicked

    private void busmarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_busmarKeyPressed
        Unida e=new Unida();
        Limpiar(tablaunida1);
        DefaultTableModel modelo= (DefaultTableModel) tablaunida1.getModel();
        e.BusMarca(modelo, busmar.getText().toUpperCase());
    }//GEN-LAST:event_busmarKeyPressed

    private void busmarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_busmarMouseClicked
        Iniciar();
    }//GEN-LAST:event_busmarMouseClicked

    private void busplaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_busplaKeyPressed
        Unida e=new Unida();
        Limpiar(tablaunida1);
        DefaultTableModel modelo= (DefaultTableModel) tablaunida1.getModel();
        e.BusPlacas(modelo, buspla.getText().toUpperCase());
    }//GEN-LAST:event_busplaKeyPressed

    private void busplaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_busplaMouseClicked
        Iniciar();
    }//GEN-LAST:event_busplaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UnidaConsola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UnidaConsola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UnidaConsola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UnidaConsola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UnidaConsola().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizar;
    private javax.swing.JTextField año;
    private javax.swing.JTextField busmar;
    private javax.swing.JTextField busnum;
    private javax.swing.JTextField buspla;
    private javax.swing.JButton cancelar;
    private javax.swing.JTextField capa;
    private javax.swing.JButton crear;
    private javax.swing.JComboBox cveemp;
    private javax.swing.JButton eliminar;
    private javax.swing.JTextField fecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField marca;
    private javax.swing.JTextField modello;
    private javax.swing.JTextField nomemp;
    private javax.swing.JTextField numuni;
    private javax.swing.JTextField placas;
    private javax.swing.JTextField propie;
    private javax.swing.JButton salir;
    private javax.swing.JButton salir1;
    private javax.swing.JTable tablaunida;
    private javax.swing.JTable tablaunida1;
    private javax.swing.JTextField txtEmpresa;
    private javax.swing.JTextField txtNombre;
    private com.toedter.calendar.JDateChooser ultman;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
